### ISSUE TITLE
Update the welcome screen text & link (onboarding)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#112]
When I first download the app, I want to retrieve logins that I have already saved, and need to understand what is required to do that (having saved logins in Firefox, FxA + Sync enabled)

## Acceptance criteria
- Should provide instruction to get a Firefox account & enable Sync
- Should provide context of what saved logins are in the browser, in case none are saved
- Content should provide context around safety and security

**NOTE** This requires changes to the already-implemented welcome screen

## Visual Design
**InVision**
https://mozilla.invisionapp.com/share/BQEUSO0S2#/267560515_Welcome

**Zeplin**
https://zpl.io/aBjB70q

**Comment by sandysage** [comment]
@nickbrandt I see the welcome screen has been updated. I'm unclear how you're proposing "show me how" works. I think we need to get that ironed out before this can be moved into the backlog with tasks.

**Comment by nickbrandt** [comment]
@sandysage This is related to comments made by @changecourse in #44 regarding having a designated area for instructions in our FAQs on how to sign-in to FxA for both desktop and mobile. The idea is this link would open to that section (anchor) in the FAQs.

**Comment by nickbrandt** [comment]
Covered now by #306
