### ISSUE TITLE
Remove test data

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#119]
~revert `2d9b54a1a6f19b50dab47cbacde0e63902331e6d` from master~

remove _all_ the test data

### acceptance criteria: 
test data is no longer populated when initializing app

Blocked by #141

**Comment by sashei** [comment]
@devinreams definitely a possibility.

**Comment by devinreams** [comment]
>instead of "remove" test data can there be a build-time flag or something to show/load the test data vs. actual Sync data?

We decided for QA and testing to use a test FxA account (`dreams+appletest@mozilla.com`) instead of test data and now that #314 is complete, the test data is gone. 🎉
