### ISSUE TITLE
Create app icon

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#126]
Provide necessary assets for ios app icon

**Comment by changecourse** [comment]
Initial designs for review:

![ios app icon](https://user-images.githubusercontent.com/6164801/36743560-cd42ba42-1ba7-11e8-987d-25952834f86c.png)

**Comment by changecourse** [comment]
@sandysage Is this ok for initial use on the app? Should anyone else give a thumbs up here? Once I get approval, I'll export the necessary assets for iOS.

**Comment by sandysage** [comment]
This looks good to me to start. Changing to "product verified"

**Comment by changecourse** [comment]
Sounds good, required png assets included in zip.

[iOS App Icon.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/1772939/iOS.App.Icon.zip)

**Comment by changecourse** [comment]
@sandysage now that the design is complete, do we mark as done, or do we want @sashei to do implementation work around the icon in this issue? (FWIW, I imagine the implementation work is minor LOE)

**Comment by sashei** [comment]
@changecourse a few sizes that I'm missing:
![Screen Shot 2018-03-06 at 2.53.18 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5948791808f380001b59534b/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f56b7191a37af117284f5e575ecc3c4a4356bcbbd671f3e57862804e0ee485690b7cc53e15ffecd418bd01ba228e4ad1e5eadb1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44be24a56a6153063e67e2431.png)

**Comment by sashei** [comment]
lookin' good!
