### ISSUE TITLE
Add interaction states

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#136]
## Acceptance Criteria
- [x] tap on item in list view (some color/indicator until you let go of your finger)
- [x] "Back" text in top of detail view (system blue is illegible when tapping)
- [x] "untap" color state on item entry/detail view (tap on web address and it stays gray background, go back to white?)
- [x] Larger "tap area" for the eyeball icon to show/hide password (entire square on right side of password field)

## Visual Design
**InVision**
Entry List Item - Pressed State: 
https://mozilla.invisionapp.com/share/XCEV238ZD#/283616647_Entry_List_-_Item_Pressed
Entry Detail - Back button - Pressed State: 
https://mozilla.invisionapp.com/share/XCEV238ZD#/283619706_Entry_Detail_-_Back_Pressed
Entry Detail - Username/Password - Pressed State:
https://mozilla.invisionapp.com/share/XCEV238ZD#/279385488_Entry_Detail_-_Copied_Pressed

**Zeplin Links**
Entry List Item - Pressed State: 
https://zpl.io/aRNpRvv
Entry Detail - Back button - Pressed State: 
https://zpl.io/agGJ1n9
Entry Detail - Username/Password - Pressed State:
https://zpl.io/a8W0Djx

**Comment by sashei** [comment]
@changecourse @nickbrandt I will need the color assets y'all want when I get to this (bullet points 1-3)
