### ISSUE TITLE
Blank screen after creating an account

### ISSUE THREAD

**Issue by hmcgaw** [mozilla-lockbox/lockbox-ios#140]
After installing Lockbox via Buddybuild and creating a new account the page that loaded was blank. Expected to see the empty state: https://mozilla.invisionapp.com/d/main#/console/12774944/268085847/preview

Once I quit the app and reopened the designed empty state was displayed.

**Comment by sandysage** [comment]
This is symptomatic of the test data. So for now this isn't something to fix. But we'll keep an eye out when this ships with real data.
