### ISSUE TITLE
Integrate Sync into application

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#141]
UPDATE: This no longer assumes use of datastore.

@jhugman investigating existing Sync from other apps
@sashei forming Sync Framework "MDP" document
@linuxwolf contributing and helping design framework/interfaces

**Comment by devinreams** [comment]
This needs to be re-written to match what we're doing with the FxA and Sync team.

- designing the Framework @sashei 
- reviewing that work @linuxwolf @jhugman
- FxA proposal for Milestones

**Comment by devinreams** [comment]
Quick update from this morning: @jhugman has some work in progress that we're hoping can be compiled/running and pulling passwords from Sync shortly. 🤞 

And we'll have our cross-team discussion "tonight" and potentially have updates on the Framework design...

**Comment by devinreams** [comment]
- @jhugman has posted the work in progress for review, at least ready for demo
  - next up: demo and get it Carthage-friendly
- @linuxwolf to take the next-level pass at drafting Framework specifics

**Comment by devinreams** [comment]
We've broken this story out into smaller tasks and will close the mega-issue accordingly (using feature-sync as the label for logically grouping):

- #240: rip Sync from Fx iOS
- #241: build lockbox-ios with that work
- #242: change Sync to use OAuth
- #243 Sync API definition

If you think of anything else just add a new issue, please. Thank you 😁
