### ISSUE TITLE
Touch item in DataStore after copy / paste

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#152]
After a username or password is copied from the app, modify the corresponding `lastUsed:` property on the item in the datastore.

**Comment by linuxwolf** [comment]
This one will require some changes in the DataStore, otherwise a change to lastUsed _also_ changes the _modified_ flag.

**Comment by sashei** [comment]
Corresponding datastore update issue: https://github.com/mozilla-lockbox/lockbox-datastore/issues/95
