### ISSUE TITLE
Entry List adjustments based on designs

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-ios#157]
Just a couple minor tweaks:

- [x] The bottom entry list item should have a bottom border/separator that extends full width. (note: for technical simplicity, removed bottom which allowed the filter bottom border to extend as expected)
- [x] Filter bottom border should extend full width 
- [x] Looks to be a bit more padding above each Entry Name in list compared to the bottom padding.
- [x] Page background color should be: **#EFEFF4**
- [x] Padding to right of clear button on filter should be **16px**

## Visual Design

**Zeplin**
https://zpl.io/aBOOd4L

Current build screenshot:
![list](https://user-images.githubusercontent.com/5185090/37432837-6836fb28-279f-11e8-87ee-539e1537d4d7.png)

![filter](https://user-images.githubusercontent.com/5185090/37476934-08494606-283c-11e8-9f08-ed527e73f36f.png)

![filter](https://user-images.githubusercontent.com/5185090/38099623-59d90cc0-3338-11e8-8434-0767afd99ca8.png)

**Comment by devinreams** [comment]
To @nickbrandt to revisit again and reduce number of times we touch/rework.

Make sure this is complete/accurate still, please? :heart:

**Comment by nickbrandt** [comment]
@devinreams Yes, this all still applies.

**Comment by devinreams** [comment]
Thanks, @nickbrandt. I spoke with @sashei and I will _try_ to see about possibly fixing these up. 🤞
