### ISSUE TITLE
Web address launches site/app (entry detail)

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#164]
When viewing an entry detail, I want to tap on the web address to launch a corresponding site in my default browser to log in.

## Acceptance Criteria
* Should be able to tap on the web address field on the item detail screen
* App should send`openURL` call to the system to open the URL in the system browser, or in an app with the associated site.

## Visual Design

**InVision**
https://mozilla.invisionapp.com/share/XCEV238ZD#/267560603_Entry_Detail

**Zeplin**
https://zpl.io/VK4vXDX

**Comment by joeyg** [comment]
@sashei This seems great but could there be an user setting to control which app to open the link in? Firefox, Focus, Safari, or Chrome?

**Comment by sashei** [comment]
@joeyg for right now this is just using the system call, implementing the options controls will be a separate feature

cc @sandysage
