### ISSUE TITLE
Engineering exploration around options for sharing in browser

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#165]
Questions to be addressed:
- [x] can the extension be enabled by default
- [x] app icon possibilities
- [x] what information can we get from the browser (i.e., to filter the list of entries on the popover)
- [x] can (how can) we manipulate data on the web from the application?
- [x] what work is required to make this work with the 1password extension interface?

**Comment by changecourse** [comment]
Based on the findings of this effort, we can plan out an appropriate design approach and corresponding stories.

**Comment by sashei** [comment]
@sandysage @changecourse @nickbrandt 

I think what @nickbrandt designed is exactly what we'd have to do to enable the action extension from the onboarding flow. There's not a way to enable the extension by default.

I will also say that the action extension is going to involve a *lot* of work to get basic functionality put together, especially with the app group data-sharing model & (I can only imagine) needing security work around that. Pocket includes an FAQ page telling users how to enable their share extension, which might be a better option for us in the short term as the extension itself will be a lot of work even without implementing this onboarding piece.

**Comment by sashei** [comment]
A few divergences from the current onboarding flow:
- Users may need to go to the `More` page  at the far end of the share sheet row to be able to see the Lockbox icon & enable sharing with the app
- I didn't explore this in great depth, but with some data fanciness we can definitely make it so that our app is the only one that shows up in the share sheet (it is still possible that users will need to go to the `More` page in this case)

**Comment by sashei** [comment]
Added a list of questions to be addressed as I continue this... Just saw the conversation in #85 >.<

feel free to add to the above list if you have more @sandysage @changecourse @nickbrandt

**Comment by sashei** [comment]
[icon] we can make our own greyscale icon for this. I gather from poking around online that the asset requirements / sizes aren’t well defined, so maybe we can pair on it when getting to that step in the process.

**Comment by sashei** [comment]
[communicating with the webpage] According to the [Accessing a Webpage](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW1) section of the documentation on this, we will be able to provide our own `.js` script to do pre processing (before we pass any information up to the Swift code that comprises the app extension) and post processing with information from the Swift code (autofill!) of the webpage that the user is currently on. I will probably need to pair with someone who knows Javascript to put those pieces together.

Getting the URL from the page will be as simple as running `document.URL` and making sure that information gets passed up to the extension.

**Comment by sashei** [comment]
[1password] The documentation on this is available on the [app extension github page](https://github.com/agilebits/onepassword-app-extension), although you need to peruse the code in order to understand what's required for _registering_ to integrate with applications that implement the protocol. There are several scenarios handled by 1Password (form login in the app itself, filling webpage forms in the app etc) that we would need to address to fully integrate in this way.

**Comment by jhugman** [comment]
I implemented the Share Action Controller (including UIActivityViewController) on Firefox for iOS.

We spent quite a lot of time getting password managers to implement the [1Password extension API][1]. So far: [LastPass, DashLane, Bitwarden][2] have already got their apps working with Firefox.

Rad Azzouz (@radazzouz) was pretty helpful during that time.

My 2 euro cents: supporting minimal filling of native apps should be part of our MVP. Account creation and filling of Safari/SafariViewController, can wait, but without this, we do not have a viable product.

[1]: https://github.com/agilebits/onepassword-app-extension
[2]: https://github.com/mozilla-mobile/firefox-ios/blob/master/Client/Frontend/Share/ShareExtensionHelper.swift#L109

**Comment by nickbrandt** [comment]
@sandysage This looks to be a list of the apps currently supporting the 1Password extension
https://blog.agilebits.com/1password-apps/

**Comment by devinreams** [comment]
From today: there are a few more questions from #82 to be addressed here before considered "Done"

**Comment by sandysage** [comment]
Implementing native app filling has a few benefits:
- indicates where we aim to go with the product with retrieval, going next to mobile browsers and then our hopes and dreams on Android (openyolo) -- a progressive step?
- solidifies our position of "get your passwords outside the Firefox browser" -- optics
- gives us something that is (potentially) more achievable for the initial launch to provide _some_ autofill -- launch with more functionality
- gives users a secure way to log in as opposed to current methods which include copy/pasting from Notes, Contacts, etc. -- make Lockbox users safer!

That said, I have 2 big product concerns here:
1. offering this capability provides limited, at best, filling for a handful of apps that aren't commonly used. Attached is the data appannie provides around the most popular apps of all time, where Twitter is the only crossover app with this list: [The-Most-Popular-iPhone-and-iPad-Apps-of-All-Time-EN.pdf](https://github.com/mozilla-lockbox/lockbox-ios/files/1904741/The-Most-Popular-iPhone-and-iPad-Apps-of-All-Time-EN.pdf)
2. our intended audience has less familiarity with password managers and we have to consider a couple of things.
   - Will our users know what the '1password' icon is and how that is expected to function. And if not, what do we have to do to inform them?
   -  How does this inform our product position in the market? It sets Lockbox squarely as a "password manager", which may not be in our favor just yet. As we're trying to reach users who store their information in a note or contact (mixed methods of saving, storing, and accessing).

What I need to do next is: get a better understanding of the work involved here and the trade-offs (eg pushes enable in browser down the line but also puts in place some of the big rocks to get there). @jhugman would you be available to chat sometime soon?

**Comment by devinreams** [comment]
@sandysage can this be closed in favor of #476?
