### ISSUE TITLE
Add highlighted states for settingsview

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#166]
The rows in the settings page stay grey when tapped. They should only be grey while the user is touching them from #147 and the tableViewCellHighlighted color when selected/highlighted

**Comment by nickbrandt** [comment]
@sashei I think for consistency the tap state for any clickable elements similar to this should be the same as what we have for the entry list as well as clicking on fields within the entry detail (the light blue color).

**Comment by devinreams** [comment]
@sashei I looked around and not quite sure how to do this.

- I see `TableViewCell`s and assume we'd want a `SettingsCell` or similar in there
- I see the idea being the class extends UITableViewCell
- But the implementation of the Settings view (and subsequent views like Auto Lock) are different enough I can't quite figure out what to do

Perhaps if you give me a pointer I can help tackle this and take on thing off your plate?

**Comment by sashei** [comment]
oops sorry I dropped the ball on this one @devinreams ....

I would look into the possible `UITableViewCell` states (`highlighted`, `selected` etc). These are configurable in the `configureCell` method in `SettingsView.swift`.

**Comment by devinreams** [comment]
Resolved by @joeyg at #257 and just confirmed by me on-device 😍
