### ISSUE TITLE
Allow user to set a default/preferred browser (settings)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#170]
When I use Lockbox to access my various online accounts, I want to be able to choose which mobile browser (Fx, Chrome, Focus, etc) to have the web addresses launch within

## Acceptance criteria

* should be able to select which browser to have web addresses launch into
* Location: Available within Settings
* TBD metrics requirements for tracking which browsers are selected (initial thought was to support Safari, Firefox, Focus, and Chrome)
* Would be nice to device detect which browsers are on a device and hide those that aren't installed (TBD)

## Visual Design
**InVision**
Settings w/ Browser Option: https://mozilla.invisionapp.com/share/BQEUSO0S2#/267560609_Settings_-_Touch_ID_Enabled
Browser Option Screen: https://mozilla.invisionapp.com/share/XCEV238ZD#/288925709_Settings_-_Browser_Option

**Zeplin**
Settings w/ Browser Option: https://zpl.io/VKNMd5W
Browser Option Screen: https://zpl.io/b6lO4ZN

**Comment by joeyg** [comment]
I am a bit biased but any chance we could add Firefox Focus to the list? :)

**Comment by nickbrandt** [comment]
@joeyg My assumption is that we would show any browser (in alpha order) that the user has installed on their device.

**Comment by joeyg** [comment]
@nickbrandt As far as I know it requires a bit of work to determine to open URLs in each browser so I don't think we can just get a list of browsers installed. If a browser is in the list, say Chrome, but is not installed should it show up as disabled or be hidden?

**Comment by nickbrandt** [comment]
That makes sense. We will discuss what options we want to support and add that to the acceptance criteria. My first thought in terms of if the user doesn't have a specific browser installed would be to hide it from the list, but we will also include that in the criteria as well once a decision has been made. Thanks for letting me know how this works!
