### ISSUE TITLE
Sign-out to lock (settings)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#171]
When I want to lock my account manually, I need an option to 'sign out' with the ability to easily unlock the app again later.

## Acceptance criteria

- Should be able to lock saved logins
- Should be able to unlock with biometrics
- If biometrics access not set, should be able to sign back in with FxA "master password"

## Visual Design
**InVision**
Sign Out (settings): https://mozilla.invisionapp.com/share/XCEV238ZD#/267560609_Settings_-_Touch_ID_Enabled
Sign In - Returning User (screen after signing out): https://mozilla.invisionapp.com/share/XCEV238ZD#/267560535_Welcome_-_Returning_User

**Zeplin**
Sign Out (settings): https://zpl.io/VKNMd5W
Sign In - Returning User (screen after signing out): https://zpl.io/V0ZyORR

**Comment by nickbrandt** [comment]
@sashei I don't think we need an asset for this one. We will just lose the icon in that case.

**Comment by sashei** [comment]
great.

Per conversation with @rgaddis, in this view transition, after hitting the `Sign Out` button, the user sees the welcome screen come up over the settings screen. After successful login, the entries list is displayed.
