### ISSUE TITLE
App Information (app store)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#176]
https://docs.google.com/document/d/1VKopGUlWQmM0iBvUZNCTnmTJhvzuaS-aKhpQVmF_GIY/edit#

- [x] Name: The name of your app as it will appear on the App Store. This can't be longer than 30 characters.
- [x] Subtitle: A summary of your app that will appear under your app’s name on the App Store for customers with devices running iOS 11 or later.
- [x] Privacy Policy URL
- [x] Category: The category that best describes this app. For more information, see the App Store Category Definitions.
- [x] Price (Free)
- [x] [Territory](https://help.apple.com/itunes-connect/developer/#/dev997f9cf7c) Availability

App Store URL: https://itunes.apple.com/us/app/firefox-lockbox/id1314000270?ls=1&mt=8

Related promotional materials: #177

**Comment by devinreams** [comment]
@mozilla-lockbox/product I updated the original description above with all the actual items we will need populated for the app's core information/details.

**Comment by sandysage** [comment]
For territory availability, let's start with a pretty limited rollout to Tier 1 territories where English is a primary language:
- au (Australia)
- nz (New Zealand)
- uk (United Kingdom)
- us (United States)
- ca (Canada)

We can always add additional territories as we 1) better define our product offering and 2) see more of the app localized (eg Pontoon contributions).

**Comment by devinreams** [comment]
I've updated iTunes Connect with everything provided above in the original description.

The only open required item is the Privacy Policy URL. For now I'm pointing to the [metrics page](https://mozilla-lockbox.github.io/lockbox-ios/metrics/) on the website.

**Comment by devinreams** [comment]
iTunes Connect has been configured with all the details provided in the Google Doc (added to the original description above so it doesn't get lost in the comments) and marked each section as I double checked it. ✅ 

Closing as complete and marked accordingly in the doc.

Please re-open and flag any items that are changed after this point in time. 😁
