### ISSUE TITLE
App promotional materials (app store)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#177]
Related app information: #176 

- [x] Promotional Text: Promotional text lets you inform your App Store visitors of any current app features without requiring an updated submission. This text will appear above your description on the App Store for customers with devices running iOS 11 or later, and macOS 10.13 or later.
- [x] Description: A description of your app, detailing features and functionality. It will also be used for your Apple Watch app.
- [x] Keywords: One or more keywords that describe your app. Keywords make App Store search results more accurate. Separate keywords with a comma.
- [x] Support URL 
- [x] Marketing URL
- [x] Copyright: The name of the person or entity that owns the exclusive rights to your app, preceded by the year the rights were obtained (for example, "2008 Acme Inc."). Do not provide a URL.

## Screenshots

Screenshots must be in the JPG or PNG format, and in the RGB color space. App previews must be in the M4V, MP4, or MOV format and can’t exceed 500 MB. 

http://help.apple.com/itunes-connect/developer/#/dev910472ff2

- [x] App Previews / Screenshots for iPhone 5.5" display [3 previews, 10 screenshots]
- ~App Previews / Screenshots for iPhone 5.8" display (optional)~

### Assets
[screenshots.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/2028416/screenshots.zip)

https://docs.google.com/document/d/1VKopGUlWQmM0iBvUZNCTnmTJhvzuaS-aKhpQVmF_GIY/edit#

**Comment by devinreams** [comment]
@mozilla-lockbox/ux I updated the original description above with all the actual items we will need populated for the app's promotion, not just screenshots.

**Comment by sandysage** [comment]
Draft content here: https://docs.google.com/document/d/1VKopGUlWQmM0iBvUZNCTnmTJhvzuaS-aKhpQVmF_GIY/edit#

@nickbrandt is preparing the screenshots for our initial submission.

**Comment by changecourse** [comment]
@sandysage in anticipation of screenshots, we'll need to know the 4-5 key things we'll wish to feature (and have short content associated with) see attached for an example: 

<img width="1000" alt="screen shot 2018-05-22 at 1 16 31 pm" src="https://user-images.githubusercontent.com/6164801/40384977-68c6612e-5dc2-11e8-95d6-78dcf040955f.png">

**Comment by sandysage** [comment]
@changecourse Let's use content we've used elsewhere to describe our features

1. Access saved Firefox logins on mobile
2. Conveniently unlock with Touch  or Face ID
3. Securely sync between devices
4. Easily search and sort

I think that gives us a decent starting point.

**Comment by nickbrandt** [comment]
@devinreams attached are the screenshots for use on the app store. Let me know if these work or if any adjustments are needed. Thanks!

[screenshots.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/2028416/screenshots.zip)

**Comment by devinreams** [comment]
iTunes Connect has been configured with all the items provided in the Google Doc and marked each section as I double checked it. I also uploaded the four 5.5" screenshots in numeric order. ✅ 

Closing as complete and marked accordingly in the doc.

Please re-open and flag any items that are changed after this point in time. 😁

**Comment by nickbrandt** [comment]
> 1. the first screenshot with the Touch ID icon on Welcome is not accurate: can you consider a different shot of this screen? perhaps with the Touch ID prompt happening or without that icon on the screen?

Is the worry here that we currently don't have that icon/button to prompt authentication? I can just do an alternate screen of the initial Welcome screen (with "Get Started") to use in its place. Currently 2 of our other screenshots have a dialog/alert so leaning towards not doing another one.

> 2. the twitter.com screenshot showing "markfox": can we change that to a fake/test/real Firefox-owned account so we ensure it's not a "real user"?

Sounds good. @sandysage I'll let you choose what we use for this username :)

**Comment by devinreams** [comment]
>>

        the first screenshot with the Touch ID icon on Welcome is not accurate: can you consider a different shot of this screen? perhaps with the Touch ID prompt happening or without that icon on the screen?

>@devinreams Is the worry here that we currently don't have that icon/button to prompt authentication? 

Yes, exactly. The screenshot doesn't accurately reflect what the actual app looks like / does at this time...

>I can just do an alternate screen of the initial Welcome screen (with "Get Started") to use in its place.

Ah yes, that seems good.

>>the twitter.com screenshot showing "markfox": can we change that to a fake/test/real Firefox-owned account so we ensure it's not a "real user"?

>Sounds good. @sandysage I'll let you choose what we use for this username :)

Any opposition to just changing the username to "firefox"? 🔥 🦊

**Comment by nickbrandt** [comment]
@devinreams My only issue with using "firefox" would be for the Entry List screenshot. If we replace all the instances "markfox" with "firefox", it may not be as easily understood that those are usernames. Not sure if that's a big deal...

**Comment by nickbrandt** [comment]
Here are the screenshots with revised Welcome screen and the Entry Detail & Entry List screens replaced with "firefox" as the username. If you need any other changes just let me know.

[screenshots.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/2051430/screenshots.zip)

**Comment by sandysage** [comment]
@devinreams @nickbrandt I did some sleuthing with our marketing compatriots and got the advice that we use an active Mozillian username; a personal account of someone who largely uses their handle/username as a voice for Firefox.

Asa agreed to be our front-person for this need: https://twitter.com/asadotzler

I'm sure we'll want to do a bit more review before going live (eg do we want to create our own account? what screenshots should we even include in the app display?), but I think this is a fair starting point that actually provides a real username.

**Comment by devinreams** [comment]
Thank you @sandysage and @nickbrandt. I didn't meant for this to be a big PITA, but: I'd rather be overly nitpick-y now and avoid potential hassle during the review. 🙇

**Comment by changecourse** [comment]
@devinreams based on PR #458 being added, we may want to keep the Welcome Screen screenshot with the biometric button for the app store, yes?

**Comment by devinreams** [comment]
>we may want to keep the Welcome Screen screenshot with the biometric button for the app store, yes?

@rbillings Totally, I'll just swap the first screenshot back when that's in place 👍

**Comment by devinreams** [comment]
>I'll just swap the first screenshot back when that's in place

@nickbrandt @changecourse now the Welcome screen says "Unlock" instead of "Sign in" on the buttons so we'll need a revised "1 - access" screenshot.

**Comment by nickbrandt** [comment]
@devinreams nice catch, screenshot attached.

![1 - access](https://user-images.githubusercontent.com/5185090/40849239-98fbc6e0-657e-11e8-95ed-e1f607bcd4ed.png)
