### ISSUE TITLE
Enable biometric lock (onboarding)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#179]
When onboarding to Lockbox, I want to be able to set up my biometric access so I can quickly unlock and get access to my credentials.

## Acceptance criteria

* Should be able to set up FaceID or TouchID from the onboarding flow

**Permission Prompt Copy**
Title: Do you want to allow  “Lockbox” to use Face ID?
Subtitle: Enabling Face ID allows for quick and secure access to your account.

## Visual Design

**InVision**
Touch ID: https://mozilla.invisionapp.com/share/XCEV238ZD#/267560536_Touch_ID
Face ID: https://mozilla.invisionapp.com/share/XCEV238ZD#/267560537_Face_ID

**Zeplin**
Touch ID: https://zpl.io/bok4D9m
Face ID: https://zpl.io/VxBOL0R

**Comment by sashei** [comment]
FaceID specific onboarding: when prompting for the FaceID permission, launch biometrics WITHOUT a fallback on the passcode. If the user fails biometric auth in this scenario, keep the on the `Enable FaceID` screen. Followup stories will have confirmation & `You failed, retry` messaging.
