### ISSUE TITLE
"No Entries Found" state for search/filter

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#186]
Current: When a user types in a search term that doesn't match any entries, they get an 'empty' state of the entry container

Expected: some sort of message stating "No entries found" to display once all entries have been filtered out.

"Learn more" link directs to: https://lockbox.firefox.com/faq.html#how-do-i-create-new-entries

## Visual Design
**InVision**
https://mozilla.invisionapp.com/share/BQEUSO0S2#/290436294_Entry_List_-_Searching_-_No_Matches

**Zeplin**
https://zpl.io/agn84N0

**Comment by nickbrandt** [comment]
@changecourse @sandysage do we have a prioritization of this story in terms of P1, P2, etc.?

**Comment by joeyg** [comment]
@changecourse where does the link in the mock up go?

**Comment by changecourse** [comment]
Blocked until we have the specific URL path in the FAQ to link to.

**Comment by changecourse** [comment]
Link updated in description, unblocked, ready for eng.

**Comment by joeyg** [comment]
Just to confirm - the difference between the empty state and the "no entries found for search/filter" is that the first displays the fake empty rows and the second does not. Is that correct?

**Comment by changecourse** [comment]
@joeyg difference between this effort (no matching entries) and the empty state (no entries total)

![screen shot 2018-06-22 at 8 19 08 am](https://user-images.githubusercontent.com/6164801/41781577-3290c900-75f5-11e8-934f-e4d186d1244e.png)
