### ISSUE TITLE
Browser access tutorial/enable (settings)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#194]
Placeholder for providing users access to the 'fill in browser' tutorial and steps to enable

**Comment by nickbrandt** [comment]
@sandysage Based on #82 being a P2, should this also be a P2? We will need to account for users being able to enable this outside of the onboarding flow.

**Comment by sandysage** [comment]
That's true. I was trying to keep the scope of work as narrow as reasonably possible - provide it in onboarding, circle back to giving later access. Let's bump it up to P2. It's still blocked pending decisions for _how_ we can best provide instructions for doing this. (Discussed in #82)

**Comment by nickbrandt** [comment]
@sandysage  Do we want to deprioritize this for the time being (and remove labels) since we aren't planning to include this in the MVP?

**Comment by nickbrandt** [comment]
@sandysage should we go ahead and close out this issue now that iOS 12 AutoFill is the better option and direction we're heading?

**Comment by sashei** [comment]
No longer relevant with iOS 12 autofill.
