### ISSUE TITLE
Update show/hide password toggle (entry detail)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#196]
Update icon to the latest photon provided

## Visual Design
**InVision**
Show icon: https://mozilla.invisionapp.com/share/BQEUSO0S2#/267560603_Entry_Detail
Hide icon: https://mozilla.invisionapp.com/share/BQEUSO0S2#/267560607_Entry_Detail_-_Show_Password

**Zeplin**
Show icon: https://zpl.io/VK4vXDX
Hide icon: https://zpl.io/aM5NyW3

**Change Specs**
New size: 18px
New padding: 8px further to the left
New color: Grey50 instead of Blue60

Related to #223

**Comment by nickbrandt** [comment]
@changecourse Can you provide me with this icon? This is a pretty quick and easy change from the design standpoint.
