### ISSUE TITLE
Refresh FxA Account Information

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#198]
Depends on #141 
Depends on #392

Currently, there is no refresh behavior around FxA account information or OAuth scoped keys.

The details on this will get shaken out when the Sync framework errors & logic are better defined.

Borrowed from https://github.com/mozilla-lockbox/lockbox-extension/issues/685

**Comment by devinreams** [comment]
Probably easier to do after we have OAuth and not worth considering now. Moving back into inbox.

**Comment by sashei** [comment]
This happens automatically via FxAClient library.
