### ISSUE TITLE
Metrics dashboard

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#202]
iOS dashboard: https://sql.telemetry.mozilla.org/dashboard/lockbox-for-ios_1

Depends on #180 
Depends on #58

**Comment by devinreams** [comment]
Telemetry is now "in production" in the iOS app and events _should_ be appearing in the events ping immediately, if not already...

Discussed with @sandysage @irrationalagent today and it's on the todo list. Moving from blocked to backlog. ➡️

**Comment by irrationalagent** [comment]
start of the dash: https://sql.telemetry.mozilla.org/dashboard/lockbox-for-ios_1

**Comment by devinreams** [comment]
@irrationalagent is there a configuration thing to force the dashboard refresh itself automatically every day? Every morning when I check I need to manually "refresh" but maybe that's just due to when I'm looking at it?

**Comment by irrationalagent** [comment]
I went ahead and changed all the queries to refresh every 24 hrs, you have to go into the queries individually and set that, I think refreshing at the dashboard level is broken.

I also can't schedule when in the day it refreshes (i think it has to be queued with all the other queries so it might vary)

**Comment by devinreams** [comment]
>I went ahead and changed all the queries to refresh every 24 hrs, you have to go into the queries individually and set that, I think refreshing at the dashboard level is broken.

Ah interesting. I was mostly curious. Thanks for doing that! ⚡️

**Comment by sandysage** [comment]
Per our discussion today, we have the initial dashboards. Future dashboards are being considered in #414. Nothing in the list is blocking us from launch at this stage.
