### ISSUE TITLE
Legal review & sign-off

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#203]
- [x] Complete [legal data form](https://docs.google.com/document/d/1GHdgHZu9zqUmRsYwEnHn8vs2uTo85fz51sp2f1rrUbs/edit) (working on week of 4/23)
- [ ] Legal signoff on Privacy Notice - this starts with the metrics.md
- [ ] Legal signoff on ToS
- [ ] short PN written in markdown and documented in the testpilot-meta repo
- [ ] Product demo/walkthrough
- [x] confirm ability to reference "External Contributor"s in Test Pilot website

**Comment by sandysage** [comment]
Some additional considerations after meeting with @mafeld today:

[ ] Future markets consideration as we determine a name
[ ] Name decision
[ ] Trademark vetting

**Comment by sandysage** [comment]
Privacy notice format for Test Pilot is here: https://github.com/mozilla/testpilot/blob/master/docs/content/reference.md#measurements

**Comment by sandysage** [comment]
Legal has provided the qualified OK to proceed on the name with the conditions:
1. only in Test Pilot (not approved beyond the experiment)
2. must use both words “FIREFOX LOCKBOX” - ie should not refer to as just Lockbox.

**Comment by devinreams** [comment]
Per discussion in Slack, added "confirm ability to reference "External Contributor"s in Test Pilot website": https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/issues/47

**Comment by sandysage** [comment]
Tracking this checklist in bugzilla now. Closing this as 'complete' for our purposes.
