### ISSUE TITLE
Tables allow headings and things scroll on top of other cells

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#205]
I noticed a few little bugs that may be worth prioritizing and cleaning up:

- [x] Settings table section headings remain anchored when scrolling backwards but the text scrolls over top the cells below (design needed on expected UI and interactions)
  ![img_2492](https://user-images.githubusercontent.com/49511/38319997-9120dbd8-37f0-11e8-859b-a34f6163b4d8.png)

- [x] Auto Lock blurb ("Select when..") remains anchored when scrolling backwards but the text scrolls over top the cells below (design needed on expected UI and interactions)
  ![img_2493](https://user-images.githubusercontent.com/49511/38319998-91371f2e-37f0-11e8-8716-d07f5ce1f33b.png)

-  "Search your entries" entry list filter does not remain anchored and can scroll away from the top title bar (is that expected? design needed on expected UI and interaction)
  ![img_2494](https://user-images.githubusercontent.com/49511/38319999-9155ebfc-37f0-11e8-875f-7a8c65efd8e1.png)

**Comment by nickbrandt** [comment]
@devinreams here are my thoughts based on how I would expect it to appear, as well as how similar things are handled in iOS Settings. Let me know if actual designs are needed vs. comments regarding this.

1. Do not anchor table headings. They should flow with their content when scrolling.
2. Similar, let's not anchor the text for the Lock Options, and let it flow up with the content when reverse scrolling.
3. I think this is actually fine as-is.

@changecourse chime in if you have any differing opinions.

**Comment by changecourse** [comment]
My only additional thought around 3 would be to consider a search enhancement involving not having the search bar fixed by default, but sliding in after someone has scrolled down the list (obscuring it from view) and then scrolling up to have it appear.... Future story.
