### ISSUE TITLE
Backwards navigation implemented inconsistently

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#208]
I believe the way the settings views have a "< Back" button is different from the item detail views (and others)?

**Comment by joeyg** [comment]
The only difference I notice is that item detail says "Back" and the one in settings says "Settings" which is consistent with the Settings app on iOS.

![simulator screen shot - iphone 8 - 2018-04-06 at 14 26 28](https://user-images.githubusercontent.com/490833/38445010-86f4b9ec-39a6-11e8-8b79-6a6a59b25d2d.png)
![simulator screen shot - iphone 8 - 2018-04-06 at 14 26 35](https://user-images.githubusercontent.com/490833/38445011-8887111a-39a6-11e8-8033-b5d3d5d51d7c.png)

**Comment by devinreams** [comment]
I think I added my own “back-button” imageset. 

I also believe the horizontal alignment in the top left is not the same. 

And I think the code itself to implement them in settings vs. item detail were different.

**Comment by joeyg** [comment]
@devinreams ahh! I hadn’t noticed that.

**Comment by devinreams** [comment]
Now a duplicate of #251
