### ISSUE TITLE
Autolock timer to lock the app

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#214]
When I configure the biometric timer, from either onboarding or from settings, I want the app to lock according to my selection.

## Acceptance critiera
- Timer selection should lock the app after that time period configured
- Default of '5 minutes' should lock the app after 5 minutes
- If 'Never' is selected, this configuration should not lock the app
- Timer should lock after each user interaction, which means the app may lock while still open

**Comment by sandysage** [comment]
> when does the timer get reset for locking the app?

@sashei Let's plan on the timer being 'accurate' from a user's perspective and have that lock after each user interaction and recognize that the app may lock while it's still open.

I'll create a subsequent story for a P2 to have an interaction to indicate lock and unlock as a way to inform the user what is happening if it happens while in the app.

**Comment by joeyg** [comment]
@sashei is this available to be worked on?

**Comment by sashei** [comment]
@joeyg apologies for the delayed response. It is indeed available to be worked on.
