### ISSUE TITLE
Design review and reconciliation

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#223]
A checkpoint for @mozilla-lockbox/ux to see where the designs vs. actual implementation aren't quite right so we can: prioritize and batch work, avoid rework, and remove debt as much as possible.

Perhaps once the review has happened adding a checklist here to this issue so we can then arrange/group/create new issues and get them scheduled accordingly?

**Comment by changecourse** [comment]
@nickbrandt & I will audit the current app experience relative to the designs and prepare design refactoring stories for consideration in the MVP

**Comment by nickbrandt** [comment]
Went through and performed an audit on the latest build. The following doc highlights what was found, as well as whether or not there is already a story associated with the change. Will be going through this with Ryan and Devin to prioritize the work.
https://docs.google.com/document/d/1Mt-MxCerH4RaN7k1iR4t3bwigrMyVZWbo2HZSfq6vQg/edit?usp=sharing

**Comment by changecourse** [comment]
@nickbrandt now that we've created/accounted for the issues in the audit, is this good to close?

**Comment by devinreams** [comment]
I just added "Related to #223" to each of the resulting issues so they link back here ☝️ and we can quickly cross-reference.

I find those extra references sometimes get helpful as we get further into a project and need to go back and see what we were thinking / saying / doing at the time...

**Comment by changecourse** [comment]
Great, thanks for doing that!

**Comment by devinreams** [comment]
Just looked at all of these with @sandysage. Some have been tackled. Some are almost done. 

The rest are intentionally prioritized (or not) for MVP. Thanks, @changecourse @nickbrandt for combing back through the work.
