### ISSUE TITLE
App Icon corner radius is a little off

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#225]
See the black showing through? 😔 

![screen shot 2018-04-10 at 3 48 49 pm](https://user-images.githubusercontent.com/49511/38585340-bad3f86c-3cd6-11e8-820b-a12324ee734b.png)

**Comment by devinreams** [comment]
@changecourse why the black background/rounded mask? It still looks like there are uses where the black can bleed through. Like a split second when I tap to launch or return "home", the icon grows/shrinks to get the zoom effect and I see some black. 😔 

Apple [says](https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/) the icons should be "square with no rounded corners". Presumably this means we'll be future-proofed in case the radius ever changes on Apple's side, allows for good masking on settings screen, etc.

FWIW, when I upload to BuddyBuild even _it_ still rounds the corners a bit differently so it crops weird: https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/settings/app-name-and-icon

![screen shot 2018-04-11 at 3 28 00 pm](https://user-images.githubusercontent.com/49511/38644203-fb8dc5b0-3d9c-11e8-99c7-540b9aa44edb.png)

**Comment by changecourse** [comment]
[ios App Icon.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/1900596/ios.App.Icon.zip)

Then this one?

**Comment by changecourse** [comment]
I was under the impression that the app icon spec dictated the rounded corners mask to be preserved for export, but perhaps I was wrong in that regard... the documentation was hard to find for this sort of thing :/

**Comment by devinreams** [comment]
>I was under the impression that the app icon spec dictated the rounded corners mask to be preserved for export

Hmm ok. 🤔 The docs are all over the place, some hidden from public, but from the few things [I've found](https://developer.apple.com/library/content/qa/qa1686/_index.html) they're not really wanting any masking and its noted as a "know issue" that could cause unexpected issues.

I'll try replacing the icons without the mask and see if we spot any locations that causes issues. 🤞

**Comment by devinreams** [comment]
Oh yeah, that's working _real nice_: https://github.com/mozilla-lockbox/lockbox-ios/pull/237
