### ISSUE TITLE
Lock & unlock transition while the application is foregrounded

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#227]
When the app locks (#214), I to be aware of the "lock" action happening if I happen to be in the app at the moment.

## Acceptance criteria
* Should inform the user that a "lock" is happening based on their timer settings
* Should mirror an "unlock" action for a visual alignment
* Should convey visual sense of securing (informing / reinforcing underlying security value)

**Comment by nickbrandt** [comment]
@sandysage Does #35 cover this in terms of what would happen if the app locked while a user was in the app (bringing up the returning user/sign-in screen)?

**Comment by sashei** [comment]
We are no longer locking in the foreground.
