### ISSUE TITLE
Updated Entry Detail Header

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#229]
_This is a design refactoring story due to the limitations of our original design posed; now we're using an apple component header for large titles._ 

**InVision**
https://mozilla.invisionapp.com/share/BQEUSO0S2#/267560603_Entry_Detail

**Zeplin**
https://zpl.io/2EjmMex

Related to #223

**Comment by changecourse** [comment]
@sandysage ready to be moved into the backlog pending your blessing

**Comment by changecourse** [comment]
@mozilla-lockbox/mobile-engineering ready for review and placement into the backlog.

**Comment by devinreams** [comment]
The "off the shelf" large navigation title format is only available to iOS 11+.

1. So, what you see today would just be our sensible "fall back" right?
2. And would you expect large titles elsewhere? It's pretty easy to let that happen (eg: on "Settings")
3. And are you super duper tied to the gradient? :smirk: From what I'm playing with, it gets a bit weird to support a gradient in a space that can come and go and grow and shrink (status bar + nav bar). 

Resources:

- https://developer.apple.com/ios/human-interface-guidelines/bars/navigation-bars/
- https://developer.apple.com/documentation/uikit/uinavigationbar/2908999-preferslargetitles

**Comment by nickbrandt** [comment]
@devinreams If we updated the gradient to be horizontal (vs. mostly vertical currently), would this resolve the conflict? That way both components (navigation bar and large title area) could share the same horizontal gradient and match up without issue? Or would there still be complications?

<img width="916" alt="screen shot 2018-04-16 at 2 00 32 pm" src="https://user-images.githubusercontent.com/5185090/38832046-90123308-417e-11e8-9828-e3beba278195.png">

**Comment by devinreams** [comment]
>If we updated the gradient to be horizontal (vs. mostly vertical currently), would this resolve the conflict?

**Comment by devinreams** [comment]
>If we updated the gradient to be horizontal (vs. mostly vertical currently), would this resolve the conflict? 

Actually, I think I accidentally got this working so the gradient can fit and work in all cases.... I think?

![gradient](https://user-images.githubusercontent.com/49511/38841466-c87a9bf4-41a1-11e8-81ba-3c6743b0386a.gif)

>Currently, we haven't identified any other areas where we feel this treatment is needed.

Understood, in other words: this is the only screen where you'd want/expect the large title. I'll see if I can get that wired up correctly...
