### ISSUE TITLE
Confirmation Dialog for Unlinking Account

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#234]
When unlinking my account for Lockbox, I should be given a confirmation dialog to ensure that I want to complete the action of blowing away my data on my device. 

**Invision**
https://mozilla.invisionapp.com/share/BQEUSO0S2#/268020745_Settings_-_Account_-_Unlink

**Zeplin**
https://zpl.io/2GzN1j9

Related to #223

**Comment by changecourse** [comment]
@sandysage this is ready for Backlog pending your approval/acceptance criteria

**Comment by Descartess** [comment]
I would like to pick this up as my first contribution to this project.

**Comment by devinreams** [comment]
@Descartess awesome! We would certainly appreciate your help. :+1:
