### ISSUE TITLE
fxa exploration

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#24]

**Comment by sashei** [comment]
FxA authentication for iOS already implemented here: https://github.com/mozilla-mobile/firefox-ios/tree/master/Account

**Comment by linuxwolf** [comment]
Does this flow support the OAuth-style scoped keys, with the **exact** same results here versus OAuth?

**Comment by sashei** [comment]
Nope. Doesn't look like they use OAuth at all so their implementation isn't useful for us.
