### ISSUE TITLE
Change fxa-sync to OAuth login

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#242]
Follow up to #141

To get the Sync key from OAuth

Needs to be discussed from an engineering perspective and prioritized with product

**Comment by devinreams** [comment]
Proposal from @rfk shared and over to us to review:

https://docs.google.com/document/d/1zWrAjvQsy_SM5GJo11CPOelWTGlpYIeSiLEuXFxrTtc/edit?ts=5add893a#heading=h.lnh76276kke7

My initial reaction, considering the timeline:

- we (Lockbox) can commit to the work to get "old auth and Sync" linked up with the existing code being wired up at #283 by @jhugman and @sashei (next week, in person?)
- once that's in place and no risk of missing our "feature complete" / app submission date in May, we continue down the dev path in parallel with the FxA team (test against the production / preffed-off work)
- then make a go/nogo decision as to whether we use the OAuth work for 1.0 app submission (enough time for testing, PI, etc.?) vs. line it up for a point release around mid May

What do you think @jhugman @sashei?

**Comment by rfk** [comment]
> once that's in place and no risk of missing our "feature complete" / app submission date in May

If we do want to ship the "old auth" version, are there FxA-side changes we would need to make to the login flow UI, or is it shippable as-is?

**Comment by devinreams** [comment]
>are there FxA-side changes we would need to make to the login flow UI, or is it shippable as-is?

I think we've all agreed we have to say the auth flow remains "shippable as-is" and we get the new hotness only with the .. new hotness (OAuth). I'll chat with @changecourse more on this to make sure we're all set...

**Comment by linuxwolf** [comment]
Bugzilla to update the existing OAuth client - < https://bugzilla.mozilla.org/show_bug.cgi?id=1460646 >

**Comment by sashei** [comment]
[eng note] Make sure to test email confirmation flow (i.e., cancelling, email confirm, re-login problems) as described in #292 and #293
