### ISSUE TITLE
Only show search on listing after user has scrolled

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#249]
Follow up to #205 from @mozilla-lockbox/ux 

"My only additional thought around [the search filter] would be to consider a search enhancement involving not having the search bar fixed by default, but sliding in after someone has scrolled down the list (obscuring it from view) and then scrolling up to have it appear.... Future story."

**Comment by nickbrandt** [comment]
Closing this as #560 is a duplicative issue and covers this functionality.
