### ISSUE TITLE
Add toggle to enable/disable sending metrics (Telemetry)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#258]
Related to #180 
Related to #58 

As a user I want to disable the ability to send usage / Telemtry data to Mozilla Firefox.

Use the same style as Firefox iOS.

![5acdc3c8-f5fa-4f7a-a0c5-c51f5bea0e21](https://user-images.githubusercontent.com/49511/38879640-1029e67e-4221-11e8-9173-cb111009aeff.jpeg)

Default “Send Usage Data” to enabled. If disabled, stop sending any and all events.

**Comment by sandysage** [comment]
@devinreams Is this blocked by anything? Or can we move this to the backlog?

**Comment by devinreams** [comment]
I'll move it to the backlog. 

We'll likely want to consider (and possibly) tackle it at the same time as #58.

**Comment by sandysage** [comment]
@joeyg That's a great question! It will eventually need to deep link to a question/answer in our FAQ: https://lockbox.firefox.com/faq.html

We're currently working on the content for this FAQ and expect to have that better defined next week. I'll be sure to update this issue when that is in place.
