### ISSUE TITLE
Test Data does not have fully formed URLs

### ISSUE THREAD

**Issue by joeyg** [mozilla-lockbox/lockbox-ios#265]
The test data in the app has URLs like "www.amazon.com" and not "https://www.amazon.com" this results in them not opening when tapped if your preferred browser is safari (default). Per [pr feedback](https://github.com/mozilla-lockbox/lockbox-ios/pull/216#discussion_r180508639) we should expect the URLs to be fully-formed.

**Comment by devinreams** [comment]
Good call out.

Since I think I broke the test data once already at #231 I'll take a look at this and see if I can fix both birds at once... so to speak. 🐦
