### ISSUE TITLE
Provide cryptography export compliance

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#266]
Follow up to #211 #260 

>Is your app designed to use cryptography or does it contain or incorporate cryptography? (Select Yes even if your app is only utilizing the encryption available in iOS or macOS.)

Yes

![screen shot 2018-04-18 at 9 14 40 am](https://user-images.githubusercontent.com/49511/38941153-2cef3f0c-42e9-11e8-94e8-cc9d8a9e87f9.png)

![screen shot 2018-04-18 at 9 15 06 am](https://user-images.githubusercontent.com/49511/38941154-2d02fc5e-42e9-11e8-8797-cd349d3e9253.png)

>Does your app qualify for any of the exemptions...?

No

![screen shot 2018-04-18 at 9 15 12 am](https://user-images.githubusercontent.com/49511/38941155-2d182dcc-42e9-11e8-8088-d19bf4f1d207.png)

>Does your app implement any encryption algorithms that are proprietary or yet-to-be-accepted as standards by international standard bodies (IEEE, IETF, ITU, etc.)?

Yes

![screen shot 2018-04-18 at 9 15 20 am](https://user-images.githubusercontent.com/49511/38941157-2d2e9bfc-42e9-11e8-9739-396b26901896.png)

>Is your app going to be available on the French App Store?

No (not yet)

![screen shot 2018-04-18 at 9 15 39 am](https://user-images.githubusercontent.com/49511/38941159-2d50b67e-42e9-11e8-8bc1-5530dd356744.png)

![screen shot 2018-04-18 at 9 15 49 am](https://user-images.githubusercontent.com/49511/38941160-2d66c126-42e9-11e8-8e3c-edd530d3a03a.png)

What are export regulations and how do I comply with them?: https://itunespartner.apple.com/en/apps/faq/Managing%20Your%20Apps_Export%20Compliance

Export compliance documentation for encryption: https://help.apple.com/itunes-connect/developer/#/devc3f64248f

Provide export compliance documentation for encryption: https://help.apple.com/itunes-connect/developer/#/dev88f5c7bf9

**Comment by linuxwolf** [comment]
To the best of my knowledge:

> "Does your app implement any encryption algorithms that are proprietary or yet-to-be-accepted as standards by international standard bodies (IEEE, IETF, ITU, etc.)?"

**No.**  All cryptographic algorithms in use are standardized by the IETF.

> "Is your app designed to use cryptography or does it contain or incorporate cryptography? (Select Yes even if your app is only utilizing the encryption available in iOS or macOS.) "

**Yes.**  It utilizes AES-GCM using 256-bit keys and Elliptic Curve Cryptography using curve P-256.  This support is largely provided by a third-party library, but some platform-native support is also utilized.

**Comment by devinreams** [comment]
>>

    "Does your app implement any encryption algorithms that are proprietary or yet-to-be-accepted as standards by international standard bodies (IEEE, IETF, ITU, etc.)?"



>No. All cryptographic algorithms in use are standardized by the IETF.

@linuxwolf Ah OK, thank you. ✅ 

@sashei We are now export compliance compliant and able to begin internal testing via iTunes Connect. 💃 

https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/1314000270/activity/ios/builds/1.0/644/details

![screen shot 2018-04-18 at 9 32 17 am](https://user-images.githubusercontent.com/49511/38942185-69c964be-42eb-11e8-841e-814d95d55095.png)
