### ISSUE TITLE
Settings button not displayed on iOS 10.3

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#278]
master 614cc5c9
iPhone SE/iPhone 6 (iOS 10.3.3)

1. Install Lockbox. 
2. Login with a valid account.

Expected: The "Settings" button should be displayed in the top-right corner.

Actual: The button is not displayed.

![screen shot 2018-04-19 at 16 07 15](https://user-images.githubusercontent.com/1866605/38993308-f080ddf6-43eb-11e8-86ee-56633f8b0eb4.png)

**Comment by devinreams** [comment]
@csuciu in case it wasn't clear, the fix for this is now live on `master` for any final confirmation
