### ISSUE TITLE
Re-installing the app after signing out will automatically re-sign in the account when the app is launched 

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#279]
master 614cc5c9
iPhone SE ( iPhone 10.3.3)

1. Install Lockbox via Xcode.
2. Sign in with a valid account.
3. Sign out.
4. Re-install Lockbox via Xcode

Result: The account is automatically re-signed in when the app is launched.

**Comment by devinreams** [comment]
May have been fixed with keychain clearing fix.

Needs to be re-tested and reproduced to see if still applies.

**Comment by devinreams** [comment]
I just re-attempted/tested this with iPhone SE (10.3) at 1abcbe7ebcc1e43e905e44f94ef6f841a0bdf2f2

1. Open iPhone SE in Simulator
2. Hardware > Erase all Content and Settings
3. Install and "Run" Lockbox in iPhone SE in (cleared) Simulator
4. Sign in with valid account
5. Settings > Account > Disconnect (aka Sign Out)
  - <img width="252" alt="screen shot 2018-05-18 at 11 30 17 am" src="https://user-images.githubusercontent.com/49511/40249163-5a825608-5a8f-11e8-8dae-a716dadf616b.png">
  - Result: the "Welcome" (Get Started) screen appears
6. "Stop" and Re-"Run" Lockbox in Xcode

Previous Result: The account is automatically re-signed in when the app is launched.

Current Result: The app opens to the "Welcome" (Get Started) screen. Tapping "Get Started" does retain the FxA webview cache/cookies and ask me to enter (just) the password of the test account. In other words, the email/login is remembered.. but I _do_ have to sign in with the account again.

<img width="252" alt="screen shot 2018-05-18 at 11 33 28 am" src="https://user-images.githubusercontent.com/49511/40249150-51893076-5a8f-11e8-81c5-d279f6183310.png">


This is working as expected as the app does _not_ "re-sign in the account when the app is launched" in Xcode/Simulator.

@csuciu if you're able to reproduce this again somehow please let us know. 😁
