### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#28]

**Comment by sashei** [comment]
@devinreams @m8ttyB any thoughts on what else I should include in the docs section of the app?

**Comment by devinreams** [comment]
@sashei Oh I have a few ideas, actually!

1. Can you please add these for consistency with the others?
  - code of conduct
  - contributing

2. And perhaps update the top-level README to roughly match the other repos

3. And perhaps a guide or some detail around the binaries (what are they, why are they there, how would someone update dependencies / versions if not in those) where you see fit? 

4. And consider copying over the mkdocs config and set it so your "docs" can _also_ then power a website? (and then actually publish the site to the gh-pages branch here and config the repo to host it)

5. and then update the link in the mozilla-lockbox.github.io to point to that site ☝️ 

I know I know, a lot of ideas... feel free to break them out if you prefer to track and work on separately.
