### ISSUE TITLE
Revisit API definition

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#284]
Follow on to #243
Requires #314
Requires #331 
Requires #242

Stabilize logging in / auth flow (and initial first sync) definition

**Comment by devinreams** [comment]
We may no longer be defining this and simply be informed/consulted in the decisions being made as part of Sync.next. To revisit in Inbox if a priority.

**Comment by sashei** [comment]
This is no longer relevant with the app-services Rust logins library.
