### ISSUE TITLE
Sign in fails with "Type error" after canceling the sign in confirmation dialog

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#292]
master 5c5d018464
iPhone SE ( iPhone 10.3.3)

1. Install Lockbox.
2. Sign in with an account that needs confirmation.
3. Go to the email client and confirm the sign in.
4. Press "Cancel" in the "Sign in confirmation" dialog.
5. Try to sign in again with the same account. 

Result: Sign in fails with "Type error" message. 
I can reproduce this issue only on this particular device. 

Note: Despite the failing sign in, the "New sign-in to Lockbox iOS" mail is received in the email client.

**Comment by csuciu** [comment]
I can reproduce this issue on one other device:
 - iPod Touch 5'th Gen running iOS 10.3.3

**Comment by devinreams** [comment]
Likely only applies when using OAuth flow which has been removed as of #314.

Will close and add reference in the OAuth issue to consider it when re-introduced. #242
