### ISSUE TITLE
Sign in confirmation dialog is never dismissed on iPhone SE/iOS 10.3.3

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#293]
master 5c5d018
iPhone SE ( iPhone 10.3.3)

1. Sign in with an account that needs confirmation.
2. Open the email client and confirm the sign in.
3. Open Lockbox and check the sign in confirmation dialog.

Expected: The dialog should be dismissed shortly after confirming the sign in.

Actual: The dialog is never dismissed. 

This might be the root cause of https://github.com/mozilla-lockbox/lockbox-ios/issues/292

**Comment by devinreams** [comment]
Applies to OAuth which has since been removed. To consider when re-implemented at #242
