### ISSUE TITLE
Tap to open URL not working as expected

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#298]
When playing around with the app on my iphone 7+, via the TestFlight app, I run into issues tapping the URL to open:

### Firefox & Firefox Focus
* set browser selection to either Firefox for iOS or Firefox Focus
* navigate to entry list, and open an entry
* tap on the URL (tried with test entries that include the www. and don't)
* the browser opens (as expected) but no URL is passed in: it just appears as an blank page with no URL that is attempting to load

### Safari
* set browser selection to either Firefox for iOS or Firefox Focus
* navigate to entry list, and open an entry
* tap on the URL (tried with test entries that include the www. and don't)
* the browser does not open (URL doesn't appear to be linked)

### Native app
* navigate to entry list, and open an entry
* tap on the URL of an entry that has a corresponding native app installed (I did this with twitter)
* the URL attempts to open in the browser and not the installed app

**Comment by sandysage** [comment]
Chrome works fine for me.

**Comment by devinreams** [comment]
@sandysage I'm wondering if your app has the old "test data".

Do you see `http` or `https` in front of the URLs? Or something like "www.amazon.com" without a protocol? If not, then can you try deleting the app from your phone and re-installing it from TestFlight?

**Comment by sandysage** [comment]
Shwew! That was it. Closing out. Thanks for the help here @devinreams
