### ISSUE TITLE
Add XCUITest target and initial tests

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#303]
This issue involves: 

 * adding a target to invoke XCUITests
 * importing mozilla-mobile/MappaMundi to the test target.
 * writing an initial MappaMundi map of the app to bootstrap the testing effort.
 * a few initial tests.

Moved from mozilla-lockbox/lockbox-extension#691

**Comment by changecourse** [comment]
![440px-Nat_3oh3_logo.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dceb6aea96b60011b662a2/125516c66e82c728ace21e0d46bcc0ca339ace878efd8010ab55a3ab2549207c6b48e13b628ae92dbc56395b4d5a47f8450c5747fffdda7ff0b13e708a5e0ee8853e0925902f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e58e8d4e3d1e06188efb5f27ed.jpg)

**Comment by joeyg** [comment]
Is the plan to use a test account or mocked data for this?

**Comment by devinreams** [comment]
>Is the plan to use a test account or mocked data for this?

@joeyg Good question. `isabel_rios` just asked the same and hopes to be able to help us with some of this work soon...

Anyway, we're currently planning to use a test account: `dreams+appletest@mozilla.com` which has also been shared with Apple for app store/beta testing. Any concerns with that approach @joeyg @sashei @jhugman?

**Comment by devinreams** [comment]
>I've made some progress here. Already have some tests working locally using Mappamundi.
If using a test account is still the approach, I could create a PR with this changes soon. 

Hey @isabelrios, that's great news! Thank you for your help. 😁 😁 

>Do we have any news about the test account? Could we use that one?

Yes, we can use the `dreams+appletest@mozilla.com` account. I just now sent the password via email to the PI team.

Thanks again 👍
