### ISSUE TITLE
Content updates

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#307]
Parent of #306
Parent of #305
Parent of #321
Parent of #323
Parent of #352

**Comment by devinreams** [comment]
We're going to consider these "Blocked" on some final decisions and possibly some user-facing testing...

**Comment by devinreams** [comment]
Unblocked by @changecourse 🎉

**Comment by devinreams** [comment]
All items in this "epic" have been merged. Closing down 💥
