### ISSUE TITLE
"No Entries" Empty Entry List (no logins found via Sync) State

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#308]
Handling the use case of someone successfully authenticating via FxA, but either... 

1. not having any saved logins associated with their account 
AND/OR
2. not having signed in via FxA on a browser instance that has saved login(s) associated with it

## Visual Design
**InVision**
https://mozilla.invisionapp.com/share/7JEUG47ZU#/268085847_Entry_List_-_Empty_State

**Zeplin**
https://zpl.io/VxKMpdg

**Comment by nickbrandt** [comment]
Duplicate of #44
