### ISSUE TITLE
Keyboard should be dismissible

### ISSUE THREAD

**Issue by joeyg** [mozilla-lockbox/lockbox-ios#313]
After tapping into the Search field there is no way to dismiss the keyboard. 

Expected functionality: Once you begin typing into the field, the clear button and the Cancel link appear on the right-hand side. 

## Visual Design
**InVision**
https://mozilla.invisionapp.com/share/7JEUG47ZU#/283633648_Entry_List_-_Searching

**Zeplin**
https://zpl.io/aRNpKpN

**Comment by changecourse** [comment]
Planning a design approach to handle this and will post to the description for how to move forward. 

Thanks for catching this, @joeyg

**Comment by changecourse** [comment]
Design defined and ready for work... @sandysage I'm going to add bug and MVP labels to this, but not prioritize it for now, unless you have a strong feeling about it.

**Comment by changecourse** [comment]
Spacing is too tight between close button and cancel. We also need to add the vertical separator as shown in the designs...
