### ISSUE TITLE
Close the keyboard upon leaving entry list

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-ios#316]
When a user invokes the keyboard to filter their entry list and then navigates away (to an entry detail or settings), the keyboard should be dismissed so when they return it is not blocking their view of the entry list.

**Comment by joeyg** [comment]
@nickbrandt Good to know - seems like iOS apps do it differently. Settings and iMessage seem to bring back the keyboard but iCal didn't.

**Comment by devinreams** [comment]
I'm just swinging back through and re-testing old stuff...

>When a user invokes the keyboard to filter their entry list and then navigates away (to an entry detail or settings), the keyboard should be dismissed so when they return it is not blocking their view of the entry list.

To re-state, as of 1189 the keyboard **DOES** disappear:

- after tapping in/out settings (the filter already input is still active, just no "cursor" in it to accept more typing)

The keyboard does **NOT** disappear:

- when tapping in/out of the sorting options (filter already input still active, keyboard up ready to continue typing)
- when tapping in/out of a detail item view (filter already input still active, keyboard up ready to continue typing)

If the user manually dismisses the keyboard (hit "Done" return key) before either of the two above actions then the state is maintained: no keyboard when you come back to the list view.

**Comment by changecourse** [comment]
IF I'm reading this correctly, this still feels like a bug to me for the second bullet point (detail item view), though not the first...

> - when tapping in/out of a detail item view (filter already input still active, keyboard up ready to continue typing)
