### ISSUE TITLE
Explore sharing data or strings from DataStore errors to improve error handling

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#32]

**Comment by sashei** [comment]
git submodules? this issue could be moved to the datastore repo, also.

@jimporter @linuxwolf

**Comment by linuxwolf** [comment]
Personally, i'm ok with git submodules.  Some care needs to be taken on what branch/tag is linked, but that seems solvable.

Currently DataStoreError is a subclass of Error, with an extra `reason` of type `Symbol` to (ideally) help with differentiating behaviors.  If the javascript binding to iOS (and presumably Android) can't handle subclasses or `Symbol` properties, those can be changed fairly easily to use Error and a String property.  However, if the binding can't even handle extra Error properties, we'll have to work something out with the Error.message **ick**.

**Comment by jimporter** [comment]
I'm not a fan of submodules; every time I've used them, they've added complexity rather than reducing it. We could try subtrees, although I haven't really messed with them, so I'd have to look into the pros/cons more.

**Comment by jimporter** [comment]
We talked about this today. Here are some ideas for how we can handle this:

* Have one message handler per function in the datastore (the code already does this); this means success *and* failure responses go through the same handler. As a result, we probably need a way to indicate whether the function succeeded and what the result is for success. The message returned could look like this:
  ```js
  {
    // `error` is null if the function succeeded
    "error": { "type": "error_id", "message": "something bad happened" },

    // `result` is null if the function failed
    "result": "anything"
  }
  ```
* Create a higher-order function that wraps the calls to the real datastore code so we don't have to repeat the error handling.

**Comment by sashei** [comment]
Cool, I like that idea Jim, and the available Encodable stuff in Swift can make those into actual Swift objects with a standard format without too much work from me. Can the `type` piece live in the datastore? Where will that get enumerated?

**Comment by linuxwolf** [comment]
It looks like `type` is analogous to the existing `reason`, so I think `reason` suffices (once it's converted from a JavaScript `Symbol` to a string).  Those are enumerated in datastore already.

**Comment by jimporter** [comment]
Yeah, `reason` is the right term. I just threw that snippet together without consulting `lockbox-datastore` first.

As a side note, the above is very similar to how we did async before JS Promises existed in Firefox OS. :)

**Comment by sashei** [comment]
Great. I've made a followup issue #94, & will close this out.
