### ISSUE TITLE
Onboarding confirmation with security theatre (onboarding)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#325]
When I’ve successfully authenticated with FxA, I want to know that my logins have been added to my Lockbox and that I am ready to use the app

## Acceptance criteria 
* Should showcase the security of the product
* Should include an option to learn more about the security which deep links to an FAQ
* Should confirm that a user is finished with the first-run setup and ready to launch their Lockbox.
* Should be the final step as part of the first-run onboarding experience.

## Visual Design
**InVision**
https://mozilla.invisionapp.com/share/7JEUG47ZU#/294915219_Security_Theater

**Zeplin**
https://zpl.io/VkmvpLK

**Comment by sandysage** [comment]
We've consistently heard throughout user research that there are concerns about the 'safety' of a solution especially when that solution has access to lots of passwords (not just one account). This is an opportunity to convey strong security along with the access product benefits.

**Comment by nickbrandt** [comment]
Designs have been added, ready for Product/Engineering review.

**Comment by changecourse** [comment]
@devinreams yes sir, makes sense to me.

**Comment by devinreams** [comment]
>makes sense to me

@changecourse ok 🙆‍♂️ 

@sandysage this has "need-product", assuming you want to re-review, make sure designs, criteria, etc. are accurate and the priority is right?

**Comment by sandysage** [comment]
From the product perspective, this covers the requirements requested, providing the value of the app + the reassurance that passwords are safe.

This also potentially addresses another area of concern: informing users that biometrics are used to unlock the app.

This remains a P2 as it's not a blocker to launch. It's a key consideration for the next / first release after apple acceptance.

**Comment by devinreams** [comment]
@sashei I'm thinking the same as the FAQ: https://en.wikipedia.org/wiki/Galois/Counter_Mode

**Comment by changecourse** [comment]
Actually, lets have it go to our anchored FAQ link addressing security first (https://lockbox.firefox.com/faq.html#What-security-technology-does-Firefox-Lockbox-use/) or whatever it is... 

Then a user can navigate to the wiki beyond that...

**Comment by sashei** [comment]
@changecourse @nickbrandt cool, should the title just be FAQ or something else?

**Comment by changecourse** [comment]
yes, that makes sense.

FWIW, all links going to the FAQ should have the same title of FAQ in that vein... should I open up a separate issue to address?
