### ISSUE TITLE
Handle FxA email confirmation and quitting the app while logging in

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#328]
Case to handle:

- User does email / password via FxA & gets email prompt screen
- User hard quits lockbox app, losing that screen
- User confirms email & returns to lockbox app

**Comment by devinreams** [comment]
Note to selves: this should also handle the scenario / bug at #360 where no force quit happens but a user simply drops from sign in form into the app (and doesn't realize there is an email confirmation waiting/expected).

**Comment by changecourse** [comment]
My hope for this issue would be that we also account for always having the placeholder image and content on an empty state of the entry list... see the problem I encountered below on a previous build...

>I did encounter something strange where the entry list container was completely empty for approx 1-2 seconds, and then the empty state placeholder and text 'popped' onto the screen, with the sync overlay... though this could have to do with a delay caused by the email confirmation... our assumption here is that even if the email confirmation is in a pending state, we should still have the placeholder image and content immediately upon first load of the entry list, correct?
