### ISSUE TITLE
Finish MDP from the API doc

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#331]
tasks:

- [ ] remove all `open` and `public` facing methods from the current `lockbox-ios-fxa-sync` 
- [ ] encode `protocol` as outlined in MDP document
- [ ] move `DataStore` methods into protocol implementation EXCEPT AUTHENTICATION
- [ ] rename `DataStore` to `LoginStore`
- [ ] consult about `Sync` vs. `Storage` states
- [ ] explore authentication boundary for move to OAuth (issue #242)

**Comment by jhugman** [comment]
Or: 

Move all Rx/Logins work into another project `lockbox-ios-sync-api` which houses all Rx'y app specific code.
