### ISSUE TITLE
iOS 10.3 - "Settings" button is cut off in the "Account" page

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#337]
master a153a6101
iPhone 6 (10.3)
iPhone SE (10.3)

1. Go to Lockbox settings and tap on "Account".
2. Check the "Settings" button.

Result: The "Settings" button is cut off.

This is not reproducible on iOS 11.
 
![screen shot 2018-05-08 at 15 03 30](https://user-images.githubusercontent.com/1866605/39756131-0be86de0-52d1-11e8-916f-4ca1ac970e79.png)

**Comment by devinreams** [comment]
Likely related to #251
