### ISSUE TITLE
If device pin/biometrics not set, provide instructions to do so

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#338]
With changes from issue #314, lock capabilities  are unusable in the settings screen when users do not have any available device authentication methods.

We need to communicate and support users to set this up without requiring device authentication to use the app.

## Requirements

- display the passcode prompt (when appropriate) on `Get Started` button tap in the welcome page
- if the user taps `Skip`, just route to FxA
- if the user hits set passcode, route to the settings page and remain on the welcome screen in the application
- don't bother storing the `Skip` preference, just launch it (when warranted) every time the user hits `Get Started`

## Visual Design
**InVision**
https://mozilla.invisionapp.com/share/7JEUG47ZU#/296414673_No_PIN

**Zeplin**
https://zpl.io/V4JW1Jz

Note: "Set Passcode" button would direct user to Touch ID & Passcode section of Settings app.

See also #339

**Comment by changecourse** [comment]
reviewing with content... will unblock once approved...

**Comment by nickbrandt** [comment]
@sandysage @devinreams this is ready for product/eng review. Content has been approved on this as well.

**Comment by devinreams** [comment]
>and listen for feedback around using device authentication without an app-level preference.

In other words, "Skip" would not be a preference or something the app remembers? It would just be essentially a "Dismiss" button _every_ time we checked whether a passcode was set (was not), right?

**Comment by devinreams** [comment]
Just discussed and re-stated: we will _always_ check if a passcode is set.

1. if user does have a passcode, regardless if they did before or not, make sure autolock is enabled with their previously-set pref (or set the default, 5 minute)
2. if the user does not have one, always check if user has hit "Skip" (we store this until uninstall)
  - if user did not press "Skip" before, throw the alert! ⚠️ 
  - if user did press "Skip" before, skip (and save that)...

**Comment by sashei** [comment]
Per conversation with @changecourse @nickbrandt just now, this story's specification is changing in the following ways:

- display the passcode prompt (when appropriate) on `Get Started` button tap in the welcome page
- if the user taps `Skip`, just route to FxA
- if the user hits set passcode, route to the settings page and remain on the welcome screen in the application
- don't bother storing the `Skip` preference, just launch it (when warranted) every time the user hits `Get Started`

**Comment by devinreams** [comment]
>this story's specification is changing in the following ways

Cool 👍

..and I just updated the OG description up above so we don't lose / contradict the story.

**Comment by sashei** [comment]
awesome, thank you @devinreams
