### ISSUE TITLE
Research options for populating credentials in iOS apps

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#34]
In research of the Alpha extension, we're seeing evidence that users expect autofill to recall credentials.

The expectation for mobile is that it is primarily a reference to already stored credentials, and users prioritize efficiency when accessing accounts. Given that, what are our options for streamlining authentication on iOS?

This will be helpful in informing UX as we get closer to needing an interface.

**Comment by joeyg** [comment]
@sandysage Is the focus of this ticket on populating credentials in iOS Apps or in web pages browsed in the Firefox iOS app?

**Comment by sandysage** [comment]
Great question. The purpose of this ticket is specifically for populating credentials in iOS apps.

**Comment by devinreams** [comment]
Some things we had talked about:

- share / extension
- custom keyboard
- drag/drop in iOS 11
- regular ol' clipboard

**Comment by sashei** [comment]
interesting: per (https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/CustomKeyboard.html)[https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/CustomKeyboard.html] we might want to disable the use of custom keyboards in the app because of privacy concerns.

**Comment by sashei** [comment]
[Custom keyboard](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/CustomKeyboard.html#//apple_ref/doc/uid/TP40014214-CH16-SW1): could reduce the number of clicks required to switch apps (users just have to tap the switch keyboard icon & select ours from their keyboard option list). The keyboard can access information about the containing app (for something like filtering a list of possible creds) assuming that 1. the user gives it permission and 2. the containing app allows custom keyboards. UNKNOWNS: authentication in the keyboard view

[Action extension](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/Action.html#//apple_ref/doc/uid/TP40014214-CH13-SW1): This is what other PW managers use for Safari autofill. I think this is a better option than a full share extension, as we're just editing a small piece of text, and the action extension is more lightweight. UNKNOWN: how PW managers are filling the correct fields in Safari -- possibly using this [JS execution piece](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW12)?

[Drag & Drop](https://developer.apple.com/documentation/uikit/drag_and_drop): iPad only. Seems pretty slick but you still need to open your app on half the screen. Receiving app has to implement the "drop" side of the protocol. UNKNOWNS: how widely do folks implement the drop side of the protocol on their login screens? 

Clipboard: Easy to hook into from system API from actions like button press.

**Comment by sashei** [comment]
@sandysage @changecourse needs collaboration for product direction on how to move forward with our iOS credential populating options

**Comment by sashei** [comment]
I am closing this based on UX decisions & subsequent engineering work reflected in #70, #74, #82
