### ISSUE TITLE
Hook up "Learn more" link on Welcome first run screen

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#340]
Follow up to #306 #324 

The "Learn more >" button still needs to be hooked up to the route / an actual FAQ link

Link directs to: https://lockbox.firefox.com/faq.html#how-do-i-use-lockbox

Related: https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/issues/46

FAQ link: https://lockbox.firefox.com/faq.html#how-do-i-use-lockbox

**Comment by devinreams** [comment]
FAQ link is: https://lockbox.firefox.com/faq.html#how-do-i-use-lockbox

**Comment by Descartess** [comment]
Hi @devinreams I have raised a PR #358  on this issue.
