### ISSUE TITLE
App crashes on Welcome screen

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#342]
@sashei I think there's a problem causing crashes due to biometrics.

- iPhone 7: Sign in with FxA, Settings, Lock Now > crash on Welcome (launch app = crash)
- iPhone X: launch app = immediate crash

One theory: since there is no prompt to enable Face/Touch ID at first run its crashing?

Either way, using two test devices, the app is stuck in a crashing / unrecoverable state.

**Comment by joeyg** [comment]
#I’ve gotten my phone as well as a simulator into this statue. I can confirm doing a full erase works for fixing the simulator.

**Comment by sashei** [comment]
😬 Ok, apologies y'all, been heads-down on loading state all day. I'll take a look at this first thing tomorrow.
