### ISSUE TITLE
Add back Face/Finger ID button to Welcome screen to re-prompt and unlock

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#343]
Removed at #314. 

See also #384 

Consider adding the button to unlock back to Welcome screen so users that cancel the dialog/prompt can re-authenticate and unlock without closing/reopening the app.

Assets and (unused strings) are still in there.

Flagging as MVP candidate to consider...

- add Face/Finger button/icon
- add text beneath button

## Visual Design
**InVision**
Touch ID: https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/288717368
Face ID: https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/267560535

**Zeplin**
Touch ID: https://zpl.io/V0ZW5xO
Face ID: https://zpl.io/aRNL9Ln

**Comment by changecourse** [comment]
Only other thing we may want to consider is a text label below the icon.

**Comment by devinreams** [comment]
>Only other thing we may want to consider is a text label below the icon.

Agreed. I updated the original description above so we don't miss that. I also linked to the invision screens showing this state to be super crystal clear...
