### ISSUE TITLE
Add support for iOS biometric APIs to unlock app data

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#35]
When accessing Lockbox, I want to be able to use Touch or Face ID instead of my password for security and convenience.

## Visual Design
**InVision**
Touch ID: https://mozilla.invisionapp.com/share/XCEV238ZD#/288717368_Welcome_-_Returning_User_-_TouchID
Touch ID w/ prompt: https://mozilla.invisionapp.com/share/XCEV238ZD#/267560531_Welcome_-_Returning_User_-_Touch_ID
Face ID: https://mozilla.invisionapp.com/share/XCEV238ZD#/267560535_Welcome_-_Returning_User
Face ID w/ prompt: https://mozilla.invisionapp.com/share/XCEV238ZD#/288719841_Welcome_-_Returning_User_-_Face_ID

**Zeplin**
Touch ID: https://zpl.io/V0ZW5xO
Touch ID w/ prompt: https://zpl.io/2Ewwx5M
Face ID: https://zpl.io/aRNL9Ln
Face ID w/ prompt: https://zpl.io/b6leoDd

tasks: 
- [x] launch biometric auth from `WelcomeView`
- [x] successful auth dispatches unlock action

Depends on #171

**Comment by sashei** [comment]
designs: https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/267560531

**Comment by sashei** [comment]
Ideally, this will build on the work in #168.

**Comment by sashei** [comment]
@changecourse @nickbrandt presumably, when a user taps the signin with FxA button on this page, they will be taken to the FxA signin screen (can prepopulate the email if we want to do that), and on logging in successfully be taken to the entries list. Let me know if that's the flow y'all were thinking.

**Comment by sashei** [comment]
this is dependent on #171

**Comment by sashei** [comment]
Ok, there are a few considerations for this story that we might want to get out ahead of @nickbrandt @changecourse while we're waiting for the review on #171 .

Possible error states for biometrics around presence:
- Biometrics not available (we are targeting iPhone 5 per @sandysage , which does not support Touch ID)
- Biometrics not enrolled (the user has not set up biometrics) (side note: apple's documentation talks about "enrolled fingers" which I find hilarious)

Possible error states for biometrics around authentication:
- Biometric auth fails
- User cancels biometric auth
- User selects fallback option but there is none

For the second class of problems, I would assume that we just kick users back to the Welcome screen and let them authenticate with FxA as the fallback.

For the first class of problems, my thought is that we would hide the TouchID / FaceID option in settings and the button on the lock screen.

**Comment by sandysage** [comment]
Given these conditions, and further digging on my part, let's not provide support for the first class of problems (biometrics not available per the device).

At this point, anything older than iPhone SE is not on the supported list. I've updated the PI request and apologize for the confusion/added hassle here.

**Comment by nickbrandt** [comment]
@sashei That all makes sense to me! 👍

**Comment by sashei** [comment]
@nickbrandt what color should the touchID / faceID button be when tapped?

**Comment by nickbrandt** [comment]
@sashei Let's go with what we are doing for other white elements on top of blue in the nav bar. So 60% of white.
