### ISSUE TITLE
Search/filter and keyboard not quite working as expected

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#351]
1. [x] Change "Cancel" behavior: to dismiss keyboard anytime (if text is input or not) and clear the search field (therefore hide "Cancel" button) in other words: Cancel button only, and always, appears when keyboard is up
2. [x] Fix "Cancel" bug: type one character and keyboard dismissed and search stops. also may result in a filtering loop that looks like an infinite/automatic scroll kinda like the matrix or something...
3. [x] Set the "Done" return key to dismiss the keyboardd
4. [x] Change "Clear" (x) behavior: to just clear the input and not dismiss the keyboard, so user can start typing again

---

From Build 1014 on iPhone X to demonstrate "Cancel" bug:

- open app, sign in, entries load into list view 🆗
- tap into search/filter input box
- type letter 'a', keyboard immediately dismissed ⚠️ 
- tap into search/filter input box
- type letter 'b', keyboard immediate dismissed ⚠️ 

Clearing is OK:

- tap into search/filter input box (with letters already input)
- tap clear (X) button 🆗 

Canceling does nothing?

- tap into search/filter input box
- type letter 'a'
- tap "Cancel" button, nothing happens ⚠️ 

I'm just guessing but it seems like the "Cancel" action is happening on every keypress? 🙃 

Related to #313 #319

**Comment by joeyg** [comment]
I commented out most of the cancel button code and found this still happening. This might be because the filter textview is inside the UITableView. It might make sense to pull this out of the table view or put it as the header. @sashei thoughts?

**Comment by sashei** [comment]
@joeyg this is definitely because the filter textview is inside the UITableView, it can be "fixed" by returning `nil` at line 121 in the `ItemListView` (the cell gets refreshed every time you call `cellForRow`). I'm wondering if it would be better to use the existing system clear-text button to serve the purpose of the `Cancel` button, suppose that's a question for @nickbrandt .....

**Comment by sashei** [comment]
@nickbrandt gotcha.

**Comment by sashei** [comment]
@joeyg ok, I feel that the filtercell should stay in the tableview. I think you can fix this by doing your Clear button observable bindings in the cell configuration rather than requesting the cell from the tableview to manipulate it.

**Comment by joeyg** [comment]
@sashei I had this line return nil instead of looking for the cell (https://github.com/mozilla-lockbox/lockbox-ios/blob/master/lockbox-ios/View/ItemListView.swift#L121) and I was still getting the bug where the keyboard dismisses after typing one character.

**Comment by devinreams** [comment]
>We mainly were trying to follow what other apps (as well as iOS Contacts and such) do for canceling out of a search.

Worth noting, what you're seeing there is not a system-provided component. Both have been built, which is causing some of what we're running into here now.

An argument can be made we should try to stick to what the system does provide so we don't re-invent the wheel. To understand there are two intended desires:

1. give the user the ability to dismiss the keyboard and clear the text in the input (currently Cancel up next to input)
2. give the user the ability to clear the text in the input but keep the keyboard up (currently clear "X")

What I think @sashei was saying is if we use the system-provided clear "X" then we get item 2 "for free".

On top of that we can use the "Return key" concept on the keyboard (usually a blue button in the bottom right) in lieu of "Cancel". Worth re-stating: the "Cancel" you're referring to in system apps is something Apple is custom implementing to be a top-anchored, full screen bespoke search experience.

So the hope, based on what is easily made available to iOS app is use:

1. system "Clear button": keep set to "appears while editing" (will clear the field and close keyboard)
  ![Screen Shot 2018-05-11 at 9.51.10 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57002eaed1bf020e0086d809/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f26b7191a371f1172a4f5e5f5edd3c4a4356bcbbd671f3e57862804e0ee485690b7cc53e15ffecd418bd01ba228e4ad1e5eadb1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44de14851a0103765e0702431.png)

2. add a keyboard "Return key": set to "Done" (to close keyboard)
  ![Screen Shot 2018-05-11 at 9.51.32 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57002eaed1bf020e0086d809/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f26b7191a371f1172a4f5c5d5edd3c4a4356bcbbd671f3e57862804e0ee485690b7cc53e15ffecd418bd01ba228e4ad1e5eadb1ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44de14851a0173f66e5722431.png)

What do you think?
![May-11-2018 09-59-40.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57002eaed1bf020e0086d809/125516c66e82c728ace21e0d46c595836ed3d2e4ddb9ee1be40da9d97c1f6a277946ef696097ec22ba416f43554d4ba5155c0b4cfffa8d78f2e03b728a5c09e8d4390c22976b03b0aac04ee155e57dd205d0f4ae805ec1e13724e289894f3b1a011980f95d35b2d4.gif)

**Comment by devinreams** [comment]
@changecourse Also found that typing one character resulted in an infinite /automatic scroll which I haven't seen but sounds really cool :smirk:

**Comment by devinreams** [comment]
@changecourse also suggested the Clear "X" in the field has an undesireable behavior where the keyboard is dismissed. Clear should keep the user in the input field ready to type and filter again.

---

I will re-purpose this bug to explain all the changes and desired behaviors with search/filter.

**Comment by devinreams** [comment]
OK I think @sashei and @changecourse and I haveve summarized the desired and related changes to search/filter cancel and clear as:

1. Change "Cancel" behavior: to just dismiss keyboard (and hide "Cancel" button), aka Cancel button only appears when keyboard is up. does not clear text field
2. Fix "Cancel" bug: type one character and keyboard dismissed and search stops. also may result in a filtering loop that looks like an infinite/automatic scroll kinda like the matrix or something...
3. Set the "Done" return key

@joeyg I see you're interested in exploring and helping with this but I don't want to assume/demand/expect anything of your time (we really appreciate/value your time and contributions!). Before we go down a path of looking at all of this a bit more ourselves: are you still interested in helping with this issue? 😁

**Comment by joeyg** [comment]
@devinreams  Thanks for reaching out. Depends on which sprint you would need this for. I probably won't have time to get it coded up, reviewed, and tested in sprint 5.

**Comment by changecourse** [comment]
Rereading this @devinreams I think we may need to slightly adjust the behavior for "Cancel" to not only collapse the keyobard, but also clear the search field, thereby 'resetting' the list to display all entries as well? This is how it works in most iOS contexts, as far as I can tell.

**Comment by sashei** [comment]
@changecourse @devinreams what should the "Done" button do, functionality-wise? As I have it now, tapping Done dismisses the keyboard but does not clear the text.

**Comment by changecourse** [comment]
I agree with @devinreams
