### ISSUE TITLE
The sign in/up email confirmation dialog is not displayed 

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#360]
Lockbox 1.0 (1054) (Testflight)
master 45173f6f821 

1. Start the app
2. Login with an account that needs confirmation or create a new account.

Expected: The email confirmation dialog should be displayed .

Actual: The email confirmation dialog is not displayed. The account is automatically signed in.

**Comment by devinreams** [comment]
Good catch @csuciu.

When we replaced OAuth for auth, we don't have handling for "email confirmation" step in the flow.

This is in progress and being handled, amongst a related edge case, at #328 via @jhugman.

Duplicate of #328
