### ISSUE TITLE
FxA Origin not checked in FxAView.swift message handler

### ISSUE THREAD

**Issue by pauljt** [mozilla-lockbox/lockbox-ios#371]
In the lockbox-ios-fxa-sync repo, there is a [check](https://github.com/mozilla-lockbox/lockbox-ios-fxa-sync/blob/c4a50380c1d126074c316e8cdd4bdc0d4e4fabec/FxAUtils/FxAViewController.swift#L142) to make sure that messages that are sent from accounts.firefox.com are actually from this origin.  However in FxAView we've [commented this check ]( https://github.com/mozilla-lockbox/lockbox-ios/blob/master/lockbox-ios/View/FxAView.swift#L104) out as far as I can tell. Now it's an unlikely attack vector, but this check would seem to be important to me to ensure the integrity of the sign-in process. Is there a reason why this check has been removed?

From testing with a debugger attached, there doesn't seem to be anything stopping the WkWebView which is showing accounts.firefox.com from being navigated, and then another webpage calling _webkit.messageHandlers.accountsCommandHandler.postMessage(...)_ directly. I'm not sure what the risk is here, but it seems odd to remove the check.

Related to #351

**Comment by devinreams** [comment]
>this check would seem to be important to me to ensure the integrity of the sign-in process

We agree. Prioritized and added to backlog accordingly...
