### ISSUE TITLE
"Firefox Lockbox" title not centered on small screen devices

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#372]
iPhone SE (10.3)  - 4" display
Lockbox 1.0(1090)

1. Login to Lockbox.
2. Check the logins page title.

Result: The page title is not centered. 

![screen shot 2018-05-16 at 15 29 11](https://user-images.githubusercontent.com/1866605/40117121-a5f03f64-591e-11e8-8d5f-14971f7c2ef7.png)

**Comment by devinreams** [comment]
To address at #251
