### ISSUE TITLE
The passcode dots are barely visible on iOS 10.3

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#373]
iPhone 6 (iOS 10.3)
Lockbox 1.0 (1090)

* The passcode dots are barely visible on iOS 10.3. Check the screenshot.

![screen shot 2018-05-16 at 16 43 13](https://user-images.githubusercontent.com/1866605/40121305-ed4af5ba-5929-11e8-8736-edcef4523140.png)

**Comment by sashei** [comment]
We no longer support iOS 10.
