### ISSUE TITLE
The logins become visible when interacting with the search/filter keyboard

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#376]
iPhone 8 Plus (11.3)
Build 1.0 (1128)

1. Login to Lockbox 
2. Start typing in the search/filter field.

Result: The logins become visible when typing even though they don't match the filter.

![filter logins issue](https://user-images.githubusercontent.com/1866605/40173031-2f53e4d0-59d9-11e8-82f2-ffb245a784b1.gif)

Depends on #351

**Comment by devinreams** [comment]
To re-test after #351 #368

**Comment by devinreams** [comment]
I just re-attempted/tested this with iPhone 8 Plus (Simulator at 1abcbe7ebcc1e43e905e44f94ef6f841a0bdf2f2) and iPhone X (Build 1165).

Previous Result: The logins become visible when typing even though they don't match the filter.

Current Result: After typing in the search field, when multiple items exist, the filter removes items that don't match and no non-matching items appear in the list view beneath the search/filter box.

![filtering](https://user-images.githubusercontent.com/49511/40248759-2f928e5a-5a8e-11e8-8c81-7de2cf8837b7.gif)


@csuciu I'll close this as no longer an issue, but if you're able to reproduce it again please let us know as there must be some extra condition/step needed to reproduce we're not aware of.
