### ISSUE TITLE
FxA Email Verification requirement is not clear

### ISSUE THREAD

**Issue by st3fan** [mozilla-lockbox/lockbox-ios#378]
After logging in, no logins appeared for me. I only much later found out that I had an FxA Email to verify this new application. Can that be made more clear in the sign in flow? This is part of the FxA framework on Firefox iOS - maybe we can reuse this?

**Comment by devinreams** [comment]
Thanks @st3fan. We agree its not clear and @jhugman is working on this over at #328 

I'll close this as a duplicate accordingly. Keep the feedback coming, please!
