### ISSUE TITLE
Auto Lock does not activate

### ISSUE THREAD

**Issue by st3fan** [mozilla-lockbox/lockbox-ios#379]
Steps to reproduce:

- Install lockbox, sign in, see your logins
- Background the app
- Come back later, more than 5 minutes

Expected: app asks to unlock
Actual: app opens without asking anything and shows logins

iPhone X with Face ID, iOS 11.3.1, Lockbox 1128

**Comment by devinreams** [comment]
Thanks again @st3fan. We believe we have a fix in place for this at #356.

Are you able/willing to try again with the latest buddybuild build (1134) on that branch? Just so we're super certain that bug is squashed for good. 🐛
