### ISSUE TITLE
Black screen after app is killed in the background

### ISSUE THREAD

**Issue by st3fan** [mozilla-lockbox/lockbox-ios#381]
Tested on Build 1139, iPhone X, iOS 11.3.1

- Launch application
- Background application
- Kill application from the app switcher
- Start application

The app will start up with a black screen.

This may be related to my comment about using using an NSTimer for the lock at https://github.com/mozilla-lockbox/lockbox-ios/pull/356#issuecomment-389973646

Killing the app may not sound like something users do, but they ... actually do. It is also a decent representation of what happens when iOS decided to kill the app, which could happen as soon as when you switch to another app that needs resources.

**Comment by nickbrandt** [comment]
Also experiencing this issue on iPhone 7, iOS 11.23

**Comment by sashei** [comment]
I've encountered this too. I suspect it has to do with the fix for the sync snapping. Addressing now.
