### ISSUE TITLE
App title is truncated on the home screen

### ISSUE THREAD

**Issue by st3fan** [mozilla-lockbox/lockbox-ios#382]
![img_708e6aa3fd83-1](https://user-images.githubusercontent.com/28052/40199568-ef323096-59e7-11e8-8aa2-bfd2b84728d2.jpeg)

**Comment by devinreams** [comment]
Yeah it's _just_ long enough to fit with none of the indicator lights (new, TestFlight) but if a light is on then it doesn't fit.

It also gets smushed (but not truncated) on iPhone SE.

@st3fan beyond coming up with a shorter name, I don't think there are any options to get past this, right?

**Comment by st3fan** [comment]
Call it "🦊 Lockbox" :-)

**Comment by sashei** [comment]
It also looks "smushed" to me on the iPhone 7.

Foxbox? ;)

**Comment by devinreams** [comment]
One idea: consider changing the display name to "Lockbox" on home screen. Would need approval from @mozilla-lockbox/ux and presumably the legal team...

**Comment by sandysage** [comment]
Based on feedback from legal, we cannot use "Lockbox" independent of Firefox Lockbox. I think we need to close this as 'won't fix'.
