### ISSUE TITLE
Item placeholder image not large enough on Plus-sized screens

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#386]
Item placeholder image does not reach the edges of the screen while Sync'ing on larger devices (reproduced on iPhone 8 Plus simulator)

**Comment by sashei** [comment]
Also present on iPhone 6 Plus simulator

**Comment by changecourse** [comment]
@nickbrandt this has to do with the No entries Found/Search Results placeholder screens (three rows fading out and two rows fading out)

**Comment by changecourse** [comment]
Related to #44 to account for larger placeholder imagery for one of the two areas where we use them

**Comment by nickbrandt** [comment]
@sashei here are the updated assets for when you get to this, they are based off iPhone 8 Plus size. The hopes would be this would just be anchored left so for smaller screen sizes the left portion won't be cut off. Thanks!

[syncing-placeholder-img.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/2017469/syncing-placeholder-img.zip)
