### ISSUE TITLE
Search/filter does not persist when app is locked

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#398]
I don't think this is a bug but wanted to highlight it just in case anyone else notices/asks:

- if you enter a search term and send the app to the background (tap home)
- and if the app is locked (immediately due to "on exit" setting or via timer or manually by user)

Then the search term will _not_ persist and will be gone from the app next time you unlock it.

That said, if you do not lock the app (it remains unlocked) and send it into the background: the search term will remain in the filter input.

Opening and leaving as-is for future consideration (should it be a feature? or is it working by design as-is) by product team.

Also noted at #377

---

## Acceptance criteria
* the search parameters should be retained and displayed in the search field
* the list view of results should be filtered by the retained search parameters
* if user force quits the app, the results should be cleared (consistent with the sort persistence)

**Comment by sandysage** [comment]
The decision to remove 'on exit' in #456 deprioritizes the need to have search results retained when the app is locked.

We're assuming, at this time, a user will complete their actions around search within the time the app is unlocked by their activity.

Marking this as closed, wont-fix. We can always revisit this if/when use cases arise where we need a persistent search state.
