### ISSUE TITLE
Sign in process keeps on Working... status when only the password is required

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockbox/lockbox-ios#404]
iOS 10.3.3 and 11.3.1
Lockbox: 1139

I can reproduce this very often trying to sign in when only my password is required. I enter it and then I'm unable to sign in again, it keeps on this screen forever:
![img_1864](https://user-images.githubusercontent.com/1897507/40302118-6c1a8a78-5cee-11e8-9e53-a50d8193b970.PNG)

I receive the New sign-in to Firefox email though.
Trying to repro on latest Lockbox versions. Will update the issue with the results

Depends on #328

**Comment by devinreams** [comment]
I've seen this happen too. Not just on Lockbox but I often get it when signing in with FxA to Pocket. I'm curious what's going on here.

I will contact the FxA dev team to see if we can troubleshoot "behind the scenes" a bit more unless @mozilla-lockbox/mobile-engineering has some ideas about how we can troubleshoot this more ourselves..

**Comment by devinreams** [comment]
We agreed we should hold on checking this out until @jhugman's work around #328 is in place since its likely a client-side issue and possibly addressed/improved...

**Comment by devinreams** [comment]
@isabelrios I've not encountered this in the past ~2 weeks or so since #328 was merged, have you?

**Comment by isabelrios** [comment]
No, I have not seen that recently. Thanks for asking!

**Comment by devinreams** [comment]
I think it’s OK to assume the state updates helped elimiate/reduce this...
