### ISSUE TITLE
 The app auto-locks while using it

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#405]
Lockbox 1.0 (1189)
iPhone 8 Plus (11.3)

1. Set the Auto Lock timer to 1 min.
2. Interact with the app for one min (navigate through the screens, filter logins, etc...)

Expected: The app doesn't lock while using it.  Should lock only after idling for 1 minute.

Actual: The app auto-locks while using it.

**Comment by joeyg** [comment]
I believe that is how it was supposed to work. There is a different issue to make the transition make more sense #227.

**Comment by changecourse** [comment]
I don't think this behavior is as intended... my hope would be that any time a user interacts with the app during a given session (navigate to a new screen, perform an action, etc) we would reset the autolock timer.

**Comment by joeyg** [comment]
@changecourse That would make sense - I may have misunderstood the discussion here https://github.com/mozilla-lockbox/lockbox-ios/issues/214#issuecomment-379879715

**Comment by sandysage** [comment]
Mea culpa for the confusion. I think we want:

1. the app to lock when idle according to the timer, and it doesn't matter if the app is in foreground or in background. This means if I open and authenticate into the app, and lay down my phone, the app should lock according to the timer even though it's still the app showing in the foreground on screen.
2. any actions while within the app to reset the timer. This means that after each user interaction the timer gets reset, and then the app shouldn't lock while actively using the app (viewing entries, changing settings, etc.)
3. putting the app in the background doesn't impact the timer, which is only based on the last user interaction. If I open and authenticate into the app, and am copying a username and password to get into another app, I shouldn't expect the app to lock in the few seconds navigating between apps.

The aim of my previous comment was to accept that the app may lock while it's still open, but it shouldn't lock while you're actively using it. I hope this helps.

**Comment by sandysage** [comment]
I would propose that this is pretty disruptive for users. This is top of the pile of our P2s.
