### ISSUE TITLE
Entry detail does not persist when app is locked

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#408]
Navigate to an entry detail. If the app is locked (immediately due to "on exit" setting or via timer or manually by user), the detail screen is not preserved and you are defaulted back to the entry list.

This is problematic for our primary retrieval story. If someone has the app set to lock "on exit" they cannot easily:
1. find the credential
2. tap the username to copy it
3. background Lockbox to navigate to desired app/online account to log in
4. paste the username
5. get back to Lockbox and the credential detail to copy the password
6. paste the password into the app

If you do not lock the app (it remains unlocked) and send it into the background, the entry detail persists as desired.

I'm labeling as a bug as a strong P2 candidate.

**Comment by sashei** [comment]
good catch @sandysage , I'd advocate for uplifting this one soon!!

**Comment by sashei** [comment]
question: if the app locks while the user is on a settings screen, would we also expect to be re-routed to that page, or do we only care about the item detail case?

**Comment by sandysage** [comment]
I primarily care about the item detail case.

It probably makes sense to make the experience consistent which would then suggest that the settings screen would also be persistent, but that is much lower priority at this time, if it adds any additional work/support.

**Comment by joeyg** [comment]
@sandysage is there a timer on how long this is valid? For example, if the user navigates to the detail screen closes the app and then opens it the next day should it still be on that detail screen?

**Comment by changecourse** [comment]
Given the fact that we've removed "on exit" from our available options, and the auto-lock default is 5 minutes, I'm not sure that this needs to be acted upon at this time (unless there are use cases that justify it) 

I'd go so far as to say that we should close this... 

@sandysage thoughts?

**Comment by sandysage** [comment]
@changecourse You beat me to it :). I do want to close this as 'wont fix'.

@joeyg Thanks for asking all the right questions here. We want to avoid this added complexity where we can, without the use cases to warrant it.

The decision to remove 'on exit' in #456 deprioritizes the need to have the entry detail view retained when the app is locked.

We're assuming, at this time, a user will complete their actions in that entry detail view within the time the app stays unlocked by their activity.

We can always revisit this if/when use cases arise where we need a persistent entry detail state.
