### ISSUE TITLE
Future Telemetry metrics ideas

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#414]
Placeholder to grab ideas:

- Telemetry scalars for autolock timer
- Telemetry scalars for browser option
- FxA ID
- if new FxA account registration occurred
- a version of access events as percentages 
- DAU definition could be made clear 
- FxA login vs reg FxA signin 
- FxA complete 
- retention graph n-day and week
  - strict based on intended use
  - general DAU 
- add a general version of taps per client 
- more general geo location 
- frequency of settings changes (e.g.) autolock 
- comment a query with instructions

**Comment by irrationalagent** [comment]
Some notes about dashboard additions: 
- a version of access events as percentages 
- DAU definition could be made clear 
- FxA login vs reg FxA signin 
- FxA complete 
- retention graph n-day and week
  - strict based on intended use
  - general DAU 
- add a general version of taps per client 
- more general geo location 
- frequency of settings changes (e.g.) autolock 
- comment a query with instructions
