### ISSUE TITLE
Investigate options for download

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#42]
For Alpha, we're expecting this to be invite-only.

Opening this to explore our download options with Test Flight & BuddyBuild with pros and cons with each. This will help our scope where we want to release (which platforms).

**Comment by devinreams** [comment]
Going with BuddyBuild for all our distribution needs at #14 #50.

That will give us the options we need: push to Test Pilot and have invite only, for example.
