### ISSUE TITLE
clear stored credentials and related data from FxA wkwebview when account is unlinked

### ISSUE THREAD

**Issue by pauljt** [mozilla-lockbox/lockbox-ios#422]
When you disconnect your FxA account from lockbox, I think the cookies used in the webview persist. I dont think this is a security issue, but it seems like something that shouldnt happen.

STR:
1. have a lockbox setup with a FxA account
2. choose Account -> Disconnect Lockbox
3. Choose" get started"

Result: Previous user is shown on the FxA login page

Expected: present the user with the blank default signin page

Maybe a design decision (maybe being abkle to re-login with your previous account is a common use case?) 

Anyways, probably low priority issue but flagging just in case.

**Comment by devinreams** [comment]
Good call out @pauljt. I've thought about this too. I do think it's jarring/unexpected to a user, especially of a "secure" / security product.

I'd advocate we consider clearing that cache/cookie data (as a P2). 👍

**Comment by carolkng** [comment]
We also ran into a similar issue in Notes on Android, and it was actually the DOM storage part that was persisting the credentials ([related fix](https://github.com/mozilla/notes/pull/1306/commits/8e49933e058f548408ea9b7939dd33d3f8ed6c19)). I'm not sure if iOS makes a similar distinction?
