### ISSUE TITLE
Improved Search UI (Design Refactor)

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#427]
This is a design refactor of the Search Bar insert it into a larger header view, which allows for smoother transitions between the entry list and entry detail, allows us to maintain a level of persistence while scrolling the entry list, and would align the visual look and feel to other Apple heuristics for how search is more natively handled. 

## Acceptance criteria
* Moving the search from the top of the table view to the base of the header
* Increasing the header height to accommodate 
* Maintaining all current behavior and functionality of the search 
* When a user scrolls through the entry list, maintain a fixed position of the entire header
* When a user taps into the search field, collapse the top portion of the header, hiding the sort, title, and settings (similar to how it is handled in iOS Contacts) See design for "Searching" for context.

## Visual Design
**InVision**
Entry List: https://mozilla.invisionapp.com/share/9HMZK68WA53
Scrolling (Fixed Search in Nav): https://mozilla.invisionapp.com/share/8EMZK6UWXKQ
Searching: https://mozilla.invisionapp.com/share/WDMZK77YXB5

**Zeplin**
https://zpl.io/VDOQ0Ol

*Note: Search field background is 20% opacity #0C0C0D 

_Reddit comment where user discusses not finding search functionality:_
<img width="749" alt="search" src="https://user-images.githubusercontent.com/5185090/42661326-1bc0952e-85eb-11e8-8026-6aef7e7289ba.png">

**Comment by devinreams** [comment]
One simple improvement to "maintain fixed position", which has been mentioned to me in passing, may be to anchor the current search field to the top of the table when the user is scrolling.

**Comment by joeyg** [comment]
@changecourse: A couple questions:
 - On the Invision link the whole nav (with search) scrolls away but the AC imply that the whole nav should stay put.
 - Currently the cancel button only appears if there is text. Should it appear immediately (like the Contacts app does)?

**Comment by sandysage** [comment]
This warrants more discussion between design decisions and app support. Holding off for this next point release, planning for a major release which includes this update.
