### ISSUE TITLE
Signing into mobile for the first time

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#43]
As an existing Lockbox user,* I need to first log into my Firefox Account to access my saved entries.

(*)For Alpha, to use the iOS Lockbox app, you have to already be an existing Lockbox user on desktop. There isn't a path to start first in mobile, yet.

## Acceptance criteria

- Should be able to complete the 2-factor fxa authentication with code
- Should have immediate access to read-only list of existing entries

## Visual Design
designs: https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/267560515

## ToDo
- [ ] Interstitial page with `Signin with your firefox account` button
- [ ] FxA login with `cancel` button

**Comment by sashei** [comment]
[ ] Interstitial scene
[ ] FxA login with `cancel` button

designs: https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/267560515

**Comment by sashei** [comment]
@changecourse can I get the assets for Lockie on the main screen here?

**Comment by sashei** [comment]
todo:
[ ] rebase & integrate with routing architecture

**Comment by sashei** [comment]
Just waiting on codereview now
