### ISSUE TITLE
Entries screen is incorrectly displayed when no entries are displayed

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#434]
Build: 1.0 (1280)
Device: iPhone 6 (10.3.2)

Steps to reproduce:
1. Launch Lockbox
2. Log in to FxA

Actual results:
- The Entries screen is incorrectly displayed when no entries are displayed.

![screen shot 2018-05-24 at 4 06 13 pm](https://user-images.githubusercontent.com/32130829/40487430-d0cd1b36-5f6c-11e8-839c-8670a7b75c8a.png)

**Comment by SimonBasca** [comment]
@devinreams I am seeing this message without any logins, with a new account. The issue is that I am seeing something like blurred logins. The underlined area in the screenshot looks a bit nasty. I would expect the page to be without the blurriness if no logins are synced.

![screen shot 2018-05-25 at 10 21 06 am](https://user-images.githubusercontent.com/32130829/40531616-878000bc-6005-11e8-9a26-41ae7a60c290.png)

**Comment by SimonBasca** [comment]
@devinreams I just noticed that this is by design. Probably not a bug.

**Comment by devinreams** [comment]
>this is by design. Probably not a bug.

Cool, agreed. Thanks for double checking @SimonBasca 🙇
