### ISSUE TITLE
Reset scroll position when the sort order changes

### ISSUE THREAD

**Issue by joewalker** [mozilla-lockbox/lockbox-ios#439]
Really minor issue.
STR:

1. Scroll down
2. Change the sort order from A-Z to "Recent"

Now I'm basically at a random point in time (not withstanding #416) so it would be good to reset the scroll position whenever the sort order changes.

**Comment by fluffyemily** [comment]
How do we want this behaviour to be resolved:

1. Scroll back to top as soon as the setting is changed.
2. Keep the login at the middle the same and reorder everything else around it.
3. Something else.

My preference I think would be for 1. as it's simple, although I can imagine 1. being preferable when going from A-Z to Recent and 2. when going from Recent to A-Z.

I shall implement 1, but please let me know if you would rather some other behavior.

**Comment by nickbrandt** [comment]
@fluffyemily I agree, I think #1 makes sense for this behavior. Thanks for picking this issue up!
