### ISSUE TITLE
Syncing entries notification flashes too quickly

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#444]
When I log in, first run, to Lockbox I see my list of entries appear at the same time as the loading indicator. It's really fast. Too fast to read.  Oddly enough the included gif is slowed down from the experience I had on the phone.

But then when I pull to refresh the loading indicator happens so quickly it appears as a flash.

![screenrecording](https://user-images.githubusercontent.com/850418/40568803-096bba24-603a-11e8-959f-bf68c141ad63.gif)

**Comment by sandysage** [comment]
Worth also noting, I also get a flash of the loading indicator randomly while in the list view (not initial load, not pull to refresh).

**Comment by changecourse** [comment]
@sashei this is somewhat related to the work on sync states... though let me know if you'd like this to be opened separately... 

When syncing for the first time, I'm seeing the following states of the app, in order:

1. FxA Auth
2. Syncing placholder empty state
3. Syncing overlay
**4. No entries Found**
5. Pop in of entries

![app setup 2](https://user-images.githubusercontent.com/6164801/41066213-64743050-699e-11e8-82a4-84325a4f0f1b.gif)

The issue being that "No Entries Found" placeholder displays briefly before entries are synced (first-time)

**Comment by sashei** [comment]
@changecourse I'll address that as part of this PR. thanks!
