### ISSUE TITLE
"Pull to refresh" doesn't work when the logins list is empty

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#445]
v1.0 (1343)
1. Create a new account in Lockbox iOS.
2. Connect the account on desktop.
3. Save a login on desktop.
4. Try to manually trigger (pull to refresh) a sync in Lockbox to have the previously created login transferred.

Expected: Pull to refresh should work when the logins list doesn't have any entries.

Actual: Pull to refresh doesn't work when the logins list is empty.

**Comment by sashei** [comment]
@sandysage this is an easy fix, would you like me to uplift?

**Comment by sigito** [comment]
It seems like the `tableView` has disabled scrolling if the list is empty: https://github.com/mozilla-lockbox/lockbox-ios/blob/master/lockbox-ios/Presenter/ItemListPresenter.swift#L420.
Is it intended or is it fine to enable scrolling for zero state?

**Comment by sashei** [comment]
@sigito Good find; I think that the current logic will need to be extended. Scrolling should only be disabled when the list is empty and the `DataStore.syncState` is `Syncing`.

@sandysage @changecourse @nickbrandt can you confirm that this is the behavior we want so that users can pull to refresh empty lists?

**Comment by changecourse** [comment]
Yes, that makes sense to me... someone should theoretically be allowed to pull to refresh an empty list to force sync check once again.

**Comment by devinreams** [comment]
>someone should theoretically be allowed to pull to refresh an empty list to force sync check once again.

I just tested this on `master` with the empty "appletester" account. I added a new saved login on desktop, synced from desktop, then "pulled to refresh" on the "no entries" state and the new login appeared as the one item in the list. 🤘
