### ISSUE TITLE
"Confirm your account" dialog is briefly displayed after signing in (no confirmation needed)

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#446]
v1.0 (1343)

1. Sign in with an account that needs confirmation.
2. Confirm the sign in.
3. Go to Lockbox settings => Account and hit Disconnect.
4. Immediately, re-sign in with the same account.

Result:  "Confirm your account" dialog is briefly displayed before being automatically dismissed.

**Comment by devinreams** [comment]
Engineering approach could be to add "yet another state" around the actual pending/confirmation state which arguably is not worth doing as it would go away once we change to OAuth.

Keeping in inbox and not promoting to backlog until after next week (All Hands).

**Comment by sashei** [comment]
Was this fixed by #478?

**Comment by devinreams** [comment]
No I don't believe so. I've still seen it briefly then disappear immediately.

But, only because I didn't have to actually confirm my email (most users will need to). In fact, I barely noticed it and probably only did because I knew what I was looking for...

**Comment by sashei** [comment]
No longer relevant with new FxA flow
