### ISSUE TITLE
The app auto-launches after force closing it while "Auto Lock" is set to "On app exit"

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#449]
v1.0 (1343)
iPhone 8 Plus (11.3.1)

1. Go to Lockbox settings => "Auto Lock" and select "On app exit".
2. Force close the app.

Result: The app keeps re-launching after each force close.

**Comment by sandysage** [comment]
This is no longer an issue now that we've removed 'on app exit' as an option. Closing as 'wont-fix'.
