### ISSUE TITLE
Remove 'on exit' from autolock options

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#456]
Right now the app display does not retain it's state once the app locks. This means search (#398) & sort (#425) does not persist, nor does an entry detail view (#408).

This is most problematic for those who have their autolock timer set to 'on exit'. Every time the app is sent to the background it locks. If the user is in the middle of a task, such as finding a desired list item or copying credentials from a detail view, they are interrupted mid-task when the app locks.

To keep the autolock option of 'on exit' we need to prioritize more work to make that a much less painful experience.

As such, let's remove this setting. At least for now.

If we need to add 'on exit' back to our autolock options, I need to better understand the desired use case. What benefit does this option provide that isn't achieved with the 1 minute lock option?

**Comment by devinreams** [comment]
>let's remove this setting. At least for now.

@sandysage OK, makes good sense. Thanks for laying it all out like that 👌
