### ISSUE TITLE
Search / filter list of saved entries

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#46]
## Acceptance criteria
- Typing in the search bar dynamically changes the list of entries
- Search should filter the URL, username, and entry/title
- The results should appear in the order that they're returned from the database (no additional support for organizing results at this time)
- the cancel button appears in the search bar when text has been entered
- tapping the cancel button clears the current search text & restores the full list of entries

## Visual Design
**Invision**
Default: https://mozilla.invisionapp.com/share/XCEV238ZD#/267560598_Entry_List
Filtered: https://mozilla.invisionapp.com/share/XCEV238ZD#/283633648_Entry_List_-_Searching

**Zeplin**
Default: https://zpl.io/aBOOd4L
Filtered: https://zpl.io/aRNpKpN

**Comment by sashei** [comment]
updated design link: https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/267560598

**Comment by sashei** [comment]
asset alert @nickbrandt @changecourse : search icon & (I'm presuming) cancel button

**Comment by nickbrandt** [comment]
@sashei Zeplin link included above in description now.

**Comment by sashei** [comment]
@sandysage the URL is technically the first in a list of possible origins, should I filter on all possible origins or just the "display" one (i.e., the first one)?

**Comment by sandysage** [comment]
Per chat with @sashei, the URL filtering is jsut the first in a list of possible origins.

The risk here is that we don't filter on all possible origins, which means if you have `[facebook.com, www.facebook.com]` in the origins list for an entry & start typing `www` into the search box, that entry will not be displayed.

Let's see if this presents any issues for our users and file the bug with that use case appears. Otherwise, let's leave it as is.
