### ISSUE TITLE
Sorting selection gets reset after ~5 minutes

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#461]
master 6d9b8a9e14
iPhone 8 Plus (11.4)

1. Sign in with an account that contains a list of saved logins.
2. Wait for the logins list to populate.
3. Sort the list by "Recently used".
4. Wait for ~5 minutes.

Expected: The sorting selection remains unchanged.

Actual: After ~5 minutes, the sorting selection changes automatically to "Alphabetically"

**Comment by joeyg** [comment]
Can this be retested @csuciu ? I think it might have been fixed by the "sticky" sort setting.

**Comment by sandysage** [comment]
This looks good on my end:
1. sort by recent
2. allow the timer to autolock the app (mine is set to 1 minute)
3. unlock and return to the app
4. the previous sort selection of "recent" remains as expected
5. allow 5 minutes to pass
6. the selection sort option of "recent" remains as expected

I'm closing this as complete.
