### ISSUE TITLE
Logins are missing after auto-lock

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#462]
master 6d9b8a9e1
iPhone 8 Plus (11.4)

1. Enable Touch ID on your device.
2. Log into Lockbox with a valid account and wait for the logins list to populate.
3. Set the Auto Lock timer to 1 min and wait for the app to lock.
4. Hit "Cancel" in the Touch ID prompt. (the "Get Started" button is not displayed after dismissing the Touch ID prompt, so you'll have to restart the app in order to be able to sign in again).
5. Restart the app.
6. Re-login with your credentials.

Expected: The logins list gets populated.

Actual: "No entries found".

**Comment by sashei** [comment]
I was unable to replicate this on an iOS 11.3 iPhone 7, but I'm upgrading my iOS version to see if that makes a difference.

**Comment by devinreams** [comment]
@sashei are you able to reproduce this with Isabel's steps?

I was unable to reproduce it following both ways (with iPhone X / Face ID against `master`). With Isabel's steps I was intentionally stuck on the "confirm" email screen, backgrounded the app, did not confirm and just opened it again, and then it went from confirm/preparing into the list (presumably cached data from when I was signed in previously).

>I would say that following these steps is an edge case, and also the reproducibility rate is very low so it would not be as critical

@isabelrios Agreed, and assuming @sashei can't readily reproduce this I think we can safely downgrade this from P1 (critical, must-have).

**Comment by devinreams** [comment]
Thank you for checking @csuciu 👍
