### ISSUE TITLE
“Syncing Entries..” alert flashes briefly when background syncs work

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#464]
### desired behavior:
do show HUD `Syncing your entries` spinner:
- after email confirmation (first sync)
- on unlock
- on app launch from background

not show during:
- background sync while app is open
- pull to refresh

HUD spinner is never displayed for less than 1 second (pending design approval on this detail), even when attendant sync completes earlier.

original issue:
~~Two observations:~~

~~1. While using the app after the “pull to refresh” #330 landed, it seems the “syncing entries” alert shows a bit too late in the sync process. Instead of when working on first run, it doesn’t show until the split second right before the items load in.~~

~~2. Sometimes a background sync causes the alert to “flash” just for a split second.~~

~~In both cases its unreadable and a bit jarring to the user.~~

**Comment by sashei** [comment]
the issue you're referring to with item 1 is fixed with #444

my thoughts about the times that we should show the HUD `Syncing your entries...` spinner:
- after email confirmation (first sync)
- on unlock
- on app launch from background

not show during:
- background sync while app is open
- pull to refresh

does that match your expectations @changecourse @devinreams @nickbrandt ?

**Comment by changecourse** [comment]
Yes, that makes sense to me. I think it also would be nice to show for at least 1-2 seconds (even if the sync completes sooner than that) just to ensure that it doesn't flash/flicker... to ensure that someone can understand what has occurred. (Though if we feel confident that #444 has addressed much of this behavior, I'm less concerned about that)

**Comment by sashei** [comment]
I don't think #444 has addressed that specifically, I just fixed the first-login not-showing-til-the-end behavior. LMK what you think of the amended description for this issue.

**Comment by changecourse** [comment]
LGTM!

**Comment by devinreams** [comment]
@sashei thanks for re-compiling all this, the original description looks good to me, too 👍
