### ISSUE TITLE
Incorrect prompt to unlock when the passcode is disabled and the app auto-locks 

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#467]
iPhone SE (10.3)
v1.0 (1387)

1. Turn on the passcode on your device.
2. Install the app and login with a valid account.
3. Set the auto-lock interval to 1 min.
4. Go to the iOS settings and turn off the passcode.
5. Go back to the app and wait for 1 min.

Result: The app auto locks after 1 min and the "Unlock with Touch ID" button is presented in the Welcome screen. Tapping on it unlocks the app.

Should the app auto lock if the passcode was disabled?

**Comment by devinreams** [comment]
This is a fun little edge case, thanks @csuciu.

**Comment by SimonBasca** [comment]
Following these STR will incorrectly unlock the app in v1.1(1473).  

Pre- requisites:
- Touch ID and Passcode disabled from iOS settings

STR:
1. Install the app and login with a valid account.
2. Wait for the app to lock.

Actual results:
- A prompt to "Unlock with Touch ID" is displayed. Tapping on the "Unlock with Touch ID" button will unlock the app without biometrics.

**Comment by sashei** [comment]
App no longer locks in the foreground as of #916.
