### ISSUE TITLE
Verified testing account gets disconnected and needs email verification

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockbox/lockbox-ios#480]
Not sure if there is a bug or that is expected. I would need to confirm in order to create the tests correctly in #303 .
For the testing account we are using this tool:
https://github.com/davehunt/FxACLI

Which allows to create a verified account. So that there is no need to confirm the email verification received. It works perfectly fine for sometime, but then it gets disconnected and needs to confirm the email. We would need to avoid this step in the tests otherwise we are stuck on the "Confirm email" screen.

Is there a way to keep that account (or any testing account) always as verified? 

Thanks!

**Comment by devinreams** [comment]
>Is there a way to keep that account (or any testing account) always as verified?

I've also wondered about this myself. I just asked the FxA team via Slack.

**Comment by rfk** [comment]
> Is there a way to keep that account (or any testing account) always as verified?

Not easily; we have a mechanism for forcing accounts to *always* require confirmation, but no mechanism for always disabling it.  Would it help to use an @restmail.net email address that always required confirmation, and programmatically retrieve and verify the emailed code?

**Comment by mhammond** [comment]
> that always required confirmation, and programmatically retrieve and verify the emailed code?

If it's any help, that's exactly what desktop Sync's automated tests do - https://searchfox.org/mozilla-central/source/services/sync/tps/extensions/tps/resource/auth/fxaccounts.jsm#78

**Comment by isabelrios** [comment]
Thank you @rfk and @mhammond for your reply! that's what I'm exploring now, since we use a restmail account, we could use the REST API to make requests and so have the account verified again when the email verification is needed.

**Comment by isabelrios** [comment]
Hi @rfk @mhammond please let me ask you about the issue I'm facing now...
I retrieve the verification mail with a GET request (Following the [REST service](https://restmail.net/) available for @restmail.net accounts) and from there I can extract the URL needed for the verification, as an example: 

``https://accounts.firefox.com/complete_signin?code=183a0fdd77892d802d04c5a13fabddab&uid=a4c7e41f041b404ba0265bc806d644fd&service=sync&r....._content=fx-confirm-signin``

In theory doing a GET request to that url, or to ``https://api.accounts.firefox.com/v1/verify_email?uid=....&code=.....`` according to [fx-account-server](https://github.com/mozilla/fxa-auth-server) should work. 
But I tried to do the GET from the test and since the account was not verified, tried with REST Client and this is what happens:
https://youtu.be/45FPXAQm6C8

So, it looks like the verification is done through a js, is that correct? or Am I missing something when doing the GET request? Please if you have any idea or suggestion let me know. In the meantime I'm trying to understand how that is done in the desktop tests that Mark mentioned.

Thank you in advance for your help!

**Comment by rfk** [comment]
> So, it looks like the verification is done through a js, is that correct? 

That's correct.  It is possible to do the verification via a direct request to the backend API, but the URL from the email is not the way to do it.  Instead, you will need to:

1. Get the `uid` and `code` parameters from the verification email.  These are available in the query parameters of the URL you parsed out of the email, or if it's simpler, you can get them from the "X-Uid" and "X-VerifyCode" headers on the email itself.
2. `POST` those two values in a JSON request to [`https://api.accounts.firefox.com/v1/recovery_email/verify_code`](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#post-recovery_emailverify_code).

That should be enough to verify the login session.

**Comment by isabelrios** [comment]
Thanks @rfk, that was really helpful!

@sashei PR coming soon with this solution to check during test time if the account is not verified, and verify it so that the tests do not fail due to that. I guess that that could be used for the screenshot tests too as you said sometime ago...
