### ISSUE TITLE
Autofill Extension (iOS 12)

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#486]
Follow up to #476 exploration

This is an epic where we want to capture the consolidated design/user stuff for the autofill feature, we may split out to separate engineering stories as needed.

- Project / Autofill Credential Provider configuration
-`ASCredentialIdentityStore` to store and update data
- List view
  - no need for detail entry view
  - high potential for reuse, minimal stripped-away design
- Minimal authentication view (to unlock with Face ID / Touch ID / passcode)
- User onboarding to explain autofill during first run of Lockbox app
- Telemetry events
- More content in FAQ
- Link from our settings screen to get to autofill settings

## Designs

**InVision**
Onboarding Flow to Settings
https://mozilla.invisionapp.com/share/BQEUSO0S2#/316626649_AutoFill_-_Onboarding

Example App Flow for AutoFill
https://mozilla.invisionapp.com/share/BQEUSO0S2#/316626653_AutoFill_-_App_Example

## Epic

- parent of #609
- parent of #610
- parent of #611
- parent of #612
- parent of #613
- parent of #614
- parent of #615
- parent of #616
- parent of #617
- parent of #624
- parent of #626

## Acceptance Criteria

- [x] Should be prompted during onboarding to set up autofill for apps and websites (direct user to the specific iOS autofill setting to turn on “Firefox Lockbox”)
- [x] Should be able to get back to “Firefox Lockbox” app after turning on autofill (if not able, then instructions to be provided in onboarding) 
- [x] Should have the option to set up autofill from settings
- [x] Should present user with AutoFill suggestions in the quicktype bar when focusing on a username or password from within safari or an app.
- [ ] Should highlight the domain associated in the Credential List with the ability to view all credentials.
- [x] Should display a Credential List that prioritizes filling (the only action to take from this view)
- [x] If no match is found in the Credential List, should display all options with some ability to search/filter
- [x] Should not be able to go to the credential details
- [x] Should not be able to go to settings from the Credential List
- [x] Should have a clear way to cancel (choose not to select a login)
- [x] When selecting a quicktype bar suggestion, should present the user with a choice to authenticate to autofill with those credentials (if Lockbox is locked)
- [x] When selecting the passwords link (key icon), should present the user with a choice to authenticate in order to view the credential list.
- [ ] Should have the ability to set specific Lockbox autofill settings (ex: quicktype bar suggestions) - this is a big maybe and requires some exploration

**Comment by devinreams** [comment]
Related bugzilla 🐛 for Firefox iOS work (P2, prioritized for version 13.0):
https://bugzilla.mozilla.org/show_bug.cgi?id=1466751

**Comment by changecourse** [comment]
@nickbrandt we'll need to provide coverage for two additional screen states: 

- [ ] a loading/completed indicator once someone has enabled our app within Autofill settings. This is presumably a 1-2 second handshake between the data source and apple being able to access the credentials list. Due to the short timetable, we'll probably want to default to a spinner/confirmation animation rather than expect text to be readable. 

- [ ] an error system dialog for instances where someone attempts to enable Lockbox for autofill without being authenticated via FxA in our app. We won't be able to route them to our app (would require deep-linking) but we can 'direct' them with the messaging.  

@sashei will we also need to handle any other instances where enabling Lockbox fails... and if so, will we know what has failed to be able to provide context? Additionally, please correct me if I've not addressed something as we had discussed.

**Comment by sashei** [comment]
@changecourse I think not being authenticated is the the main case to handle, I will update y'all if I discover anything else.

**Comment by sashei** [comment]
@changecourse I am breaking this down into engineering tasks, the associated story for the convo / summary above is #611.

**Comment by devinreams** [comment]
@sandysage will review this and "convert" it to an epic, make sure all stories are accounted for as well.

**Comment by sandysage** [comment]
This story is now an epic. I added a couple of new items to account for telemetry and FAQ updates.

@sashei Do we need any stories around providing autofill setup from settings? Am I overlooking that?

@nickbrandt I'm not finding any flows for when no match is found in the Credential List. How is that being handled? I think we noted that we should display all options with some ability to search/filter but without going to details or settings from within this list view. Am I just overlooking it in in Invision?

**Comment by nickbrandt** [comment]
@sandysage When going to the credential list (tapping the key), the idea is that the associated domain with whatever login screen they were coming from would be prefilled in the search bar (as seen here: https://mozilla.invisionapp.com/share/RWEHBJQH9#/304302923_AutoFill_-_App_Example_-_Credential_List). If this results in no matches found, we would present them with the same screen we did for the No Matches state in the app. From there they can clear out the search field (domain), and select a different entry if they wish. I will create an additional screen to showcase this state though.

**Comment by sashei** [comment]
@sandysage showing the option to enable Autofill in settings should be taken care of by #622. There are two set-up stories related to Settings enablement, #611 and #612.

**Comment by sandysage** [comment]
@nickbrandt @sashei thank y'all! I think I'm set here.

**Comment by devinreams** [comment]
Closing this with two acceptance criteria no longer complete:

> Should highlight the domain associated in the Credential List with the ability to view all credentials.

>Should have the ability to set specific Lockbox autofill settings (ex: quicktype bar suggestions) - this is a big maybe and requires some exploration
