### ISSUE TITLE
XCUITest - Kill simulator before running the tests

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockbox/lockbox-ios#488]
Looks like sometimes the app does not start from a clean state on BB when running the tests. Master execution:
https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5b2bb37c4b0b66000147c341#tests
Test is failing because when launching the app for the first time user is already logged in and so the test fails on checking that step

Lets add a pre test condition that kills the simulator so that we assure we start from a controlled state

Depends on #490

**Comment by sashei** [comment]
👍 I am doing this manually when running locally right now, thanks for jumping on it @isabelrios !!

**Comment by sashei** [comment]
depends on #490 getting landed so that we can leverage the shared `uispecs` target
