### ISSUE TITLE
Upgrading app does not require the user to unlock

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#495]
Split out from #492 via @st3fan 

>The app opened without asking for FaceID. I put a piece of paper on top of the front camera to make sure to test this.

**Comment by sashei** [comment]
I'm guessing that this was fixed by #514, can anyone confirm?

**Comment by devinreams** [comment]
Upon upgrade: the app maintains whatever state it was in. So if it _was_ locked, it will remain locked and prompt you.

If it was unlocked, an upgrade will not require you to unlock it. That was my experience when testing #514.

@st3fan would you mind double checking and confirming this is resolved and can be closed?
