### ISSUE TITLE
The "Welcome to Lockbox" dialog is automatically dismissed

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#500]
v1.1 (1490)

1. Install a fresh copy of Lockbox.
2. Open the app and sign in.
           => The "Welcome to Lockbox" dialog is displayed.
3. Wait for a few seconds.

Expected: The "Welcome to Lockbox" dialog is dismissed only when the user taps on the "Finish" button.

Actual: The dialog is automatically dismissed after a few seconds.

**Comment by sashei** [comment]
@csuciu This is a known issue when you don't have to confirm your account via email. It should be fixed when we move to the OAuth sign-in flow, but for this version of sign-in we assume that most users will need to confirm their email.

**Comment by devinreams** [comment]
Thanks @csuciu @sashei.

>This is a known issue when you don't have to confirm your account via email.

👍 

I just re-confirmed on 1490: when a confirmation email is required (as nearly all first-run users will experience) the Welcome screen is not dismissed.
