### ISSUE TITLE
Welcome page layout breaks after tapping on "Learn more" link

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#502]
v1.1 (1490)
iPhone SE iOS 10.3.3

Steps to reproduce:
1. Install Lockbox
2. Tap on "Learn more" link
3.  Close the "Learn more" page

Actual results:
- Welcome page layout is broken and shifted down.

![screen shot 2018-06-26 at 3 33 08 pm](https://user-images.githubusercontent.com/32130829/41911827-6799fba8-7956-11e8-8ba3-c73e0353c762.png)

**Comment by devinreams** [comment]
Thanks @SimonBasca 

@sandysage @sashei I _was_ able to reproduce this but not sure how to fix it. Do either of you think its worth trying to fix this week before public release (mark as P1 and move to top of backlog)?

**Comment by sashei** [comment]
I think it's worth trying to fix this week. Not sure what's going on but I
can look into it.

**Comment by devinreams** [comment]
If I slow animations on simulator I see what appeard to be the "large title" styling appears pushing the whole view down to fit a big nav bar. Will test and see if that's all we need to fix...

**Comment by devinreams** [comment]
Ah it's actually throwing a full on nav bar on the welcome view which is completely unnecessary on this view, from what I can see... PR coming.
