### ISSUE TITLE
Long passwords overlap with eye icon, don't wrap correctly

### ISSUE THREAD

**Issue by hafta** [mozilla-lockbox/lockbox-ios#515]
When viewing a password entry, passwords should wrap earlier, taking into account the "eye" icon.

For a long password that extends beyond the width of the screen and wraps, the hidden password dots overlap with the eye icon. Once the eye icon is tapped and the password is revealed, it overlaps with the eye icon and its difficult to read the actual password text.

<img width="320" alt="lockbox-long-password" src="https://user-images.githubusercontent.com/10162738/41997270-5cd3dfa2-7a0c-11e8-9e9c-1a659d6b7e46.png">

**Comment by devinreams** [comment]
Thank you for filing this issue @hafta. 🙇 

We should have a decent fix in place at #516. Thanks again! ❤️
