### ISSUE TITLE
Lockbox enhancement - add name account used to log in

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla-lockbox/lockbox-ios#524]
Environment:
Device: iPhone SE (11.0.1)
Lockbox version 1.1 (1552)

Steps to reproduce:
1. Open Lockbox app;
2. Go to settings -> account.

Actual results: No user/account name is displayed.
Expected results: name account should be displayed.

![image-1 1](https://user-images.githubusercontent.com/24588037/42095610-b7f840e8-7bbb-11e8-9f69-db232e3e6bfe.jpg)

**Comment by devinreams** [comment]
Thanks @SorinaFlorean. This is a known issue that's sometimes mitigated by a fix we made on our side here: #521 

And should be fully prevented due to a fix (not yet in production) completed on the server side here: https://github.com/mozilla/fxa-auth-server/issues/2491
