### ISSUE TITLE
XCUITests: New tests would be needed

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockbox/lockbox-ios#525]
Lets add more tests for:

- [ ] Entry detail view
   - [ ]  Open Website from there
   - [ ]  Copy option
 

- [ ] Search options

These are some examples without XCUITest coverage yet. Please feel free to add more so that we have test covering all the main features.

Thanks!

**Comment by isabelrios** [comment]
So this checks are already done on PR #530
- [ x] Entry detail view
   - [ x]  Open Website from there
   - [ ]  Copy option
 

- [ x] Search options

The only pending thing there is the Copy option. Need some investigation since the prompt when long taping to copy is not detected by the tests so far...

**Comment by devinreams** [comment]
>The only pending thing there is the Copy option. Need some investigation since the prompt when long taping to copy is not detected by the tests so far...

@isabelrios Sorry, I couldn't readily tell, but were you able to test the copy action? Or would it still be a good candidate for a new/follow-up issue?

**Comment by isabelrios** [comment]
@devinreams yes, not the prompt since I was not able to detect it within the tests, but the test checks that the [clipboard contains the copied user name](https://github.com/mozilla-lockbox/lockbox-ios/blob/master/LockboxXCUITests/LockboxXCUITests.swift#L188)

**Comment by devinreams** [comment]
Aha! I obviously did not search hard enough. Awesome and thank you again, @isabelrios. 🙇
