### ISSUE TITLE
When is the lock screen deployed?

### ISSUE THREAD

**Issue by teonbrooks** [mozilla-lockbox/lockbox-ios#526]
I couldn't find a related issue and sorry if this is being worked on or already noted but when I start Lockbox either after an update ~~or after it's been idle for a while~~, I expect that the first screen prompted would be the lock screen for passcode or TouchID. I've noticed that it has been my list of passwords even though I have my auto-lock set to five minutes. Is this a known issue?

**Comment by devinreams** [comment]
Hey @teonbrooks, yeah that was a known issue.

We pushed out another update yesterday (1552) that makes sure the locked state is as expected.

I see you're a version behind... would you mind updating once more and seeing if it's working as you expect?

**Comment by teonbrooks** [comment]
@devinreams, just updated to 1572, and that works as expected. do you know if there will be an About page. I couldn't find the build or version number within the app, just from TestFlight

**Comment by devinreams** [comment]
>just updated to 1572, and that works as expected

Okay great thanks for confirming. 😁 


>do you know if there will be an About page

Nice idea. I've thought about this too and we _could_ add it to the footer of the Settings screen. I'll add an issue/story to consider adding it.

But yeah, you're right: TestFlight/App Store will be the simplest way to know what you have for now...

Thanks for testing and sending us your feedback!
