### ISSUE TITLE
Add en-only disclaimer to Test Pilot page

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#532]
@linuxwolf or @devinreams can either you add a line of text to the Test Pilot page:

> Please note, Firefox Lockbox is currently an English only app available in a few regions including  Australia, New Zealand, United Kingdom, United States, and Canada.

per the request of marketing. Thanks!

**Comment by devinreams** [comment]
I can do it right now. @meandavejustice is about to tag for the release so will hurry up and sneak it into the main content area.

**Comment by devinreams** [comment]
OK it's added to the Test Pilot experiment page and on the https://lockbox.firefox.com/ homepage, too.

**Comment by devinreams** [comment]
>This means we're back at the starting point, and we're going to show English text on production.

Discussion continued here: https://github.com/mozilla/testpilot/pull/3707#issuecomment-402829805

- This is likely just a temporary disclaimer.
- We'll keep the same translation ID so none of the already-translated strings are "lost".
