### ISSUE TITLE
App locks when interacting with webviews

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#534]
A redditor pointed out that they had issues with the app locking while providing feedback as seen [here](https://www.reddit.com/r/firefox/comments/8xox1z/firefox_lockbox_for_ios_and_notes_for_android_are/e24peq5/).

I just confirmed this happens. It seems the interactions in the webview don't keep the autolock timer active:
- set the autolock timer to 1 minute
- navigate to the feedback form
- actively engage with the form for 1 minute
- the app locks while interacting with the form

I see this being a potentially serious issue for us. Even with the default timer of 5 minutes, we're going to see feedback submissions drop which will likely impact our app store rating in a negative way. If the timer is set to 1 minute, it's unlikely someone will complete the feedback form in that time.

**Comment by jhugman** [comment]
This isn't just webviews: this is all screens within the app. 

Which screens should auto-lock be suspended on? Is it _just_ the feedback screen or are there others?

**Comment by sandysage** [comment]
> This isn't just webviews: this is all screens within the app.

Hm. This hasn't been my experience within the rest of the app. With the discussion in [#405](https://github.com/mozilla-lockbox/lockbox-ios/issues/405#issuecomment-390763593) and the pull request #418, I've not seen the app lock while actively interacting with it, outside of the issues we've seen in #463. I'm only seeing it happen while actively engaging a webview: 1) scrolling the FAQ and 2) typing in the feedback form.

Where else does the app autolock while actively engaging it?

**Comment by jhugman** [comment]
@sandysage Ah: when a user action is triggered , the timer is continuously reset.

If you leave the app to soak on any screen, then the latest timer will timeout and the lock will engage after the correct time.

On a webpage, no actions are triggered, and the timer is not reset.

Two approaches possible: 

1. send actions every time the user touches a webpage (scroll, taps, etc etc),
2. pause the timer while the user is on a webpage, and restart it when they come back.
