### ISSUE TITLE
Ensure to never advance through `ServerConfigurationRequired`

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockbox/lockbox-ios#535]
From @nickalexander

> Lockbox must opt-out of all server configuration.  If a user's Sync 1.5 account is unhealthy, Lockbox can't try to restore it to health.  Concretely, we need to ensure that we never try to advance through ServerConfigurationRequired.  The state machine already handles error cycles; if we figure out how to just re-raise the relevant error, everything should be fine.
> 
> I don't have a great way to test this situation.  Generally I use some _other_ development tool (including a hand-written unit test) to authenticate to the storage server and HTTP DELETE the storage root.  Then when you connect Lockbox to that blank service, if we get some sort of "Sync is in a bad state" message, we're good.  What we don't want is for Lockbox to start POSTing meta/global records to that service, etc.

**Comment by sandysage** [comment]
@changecourse @nickbrandt When Lockbox can't load logins, we need a way to communicate to users that something is wrong and Lockbox can't fix it (eg the Sync service crashed).  We'll want to 1. inform users that something went wrong and 2. to recover, go back to Firefox (desktop or iOS) and manually initiate a sync.

**Comment by sandysage** [comment]
Labeling as P1 to avoid dataloss
