### ISSUE TITLE
Include Klar as a browser option for DE

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#540]
In our German market, Firefox Focus is not a browser option. Instead the privacy browser we can provide is Klar.

When we're looking to offer the app in Germany we'll want to replace the Firefox Focus browser option with Klar.

**Comment by joeyg** [comment]
@sandysage Do you have a suggestion on how to decide which app, Focus or Klar, to show? Or show both?

How about:
- If focus is installed: Show focus in settings
- If klar is installed: Show Klar in settings
- If neither is installed: Show focus, disabled in settings.

**Comment by linuxwolf** [comment]
Is there a similar concern with Firefox Rocket?

**Comment by joeyg** [comment]
@linuxwolf ohh - is there Rocket for iOS?

**Comment by linuxwolf** [comment]
> @linuxwolf ohh - is there Rocket for iOS? 

🤦‍♀️ nope, so I withdraw the question (-:

**Comment by sandysage** [comment]
@joeyg Let's go with only displaying what is installed at this time, without falling back to show Focus. That way we avoid potential confusion entirely.

I think we want to consider a UX that allows users to see AND download other browsers that aren't installed at a later time.

**Comment by sandysage** [comment]
@changecourse Can start with #711 and build from that one?

**Comment by sandysage** [comment]
Err...I mean #544. Bringing over a handful of issues that were unintentionally opened in the Lockbox-extension repo. :)

**Comment by changecourse** [comment]
Yep, makes sense.
