### ISSUE TITLE
Open up the iOS app to all worldwide markets

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#541]
Based on the response to the initial release, it's clear there is demand for this kind of app in other regions beyond the Tier 1 markets previously identified in [#176](https://github.com/mozilla-lockbox/lockbox-ios/issues/176#issuecomment-390737930).

Opening this issue to roll out the English-only app to all available regions. To get there, we need to:

~1. [ ] update the app store to issue a disclaimer that this app is English only~
* Apple knows what languages the app is built in and provides some information based on the device settings

~2. [ ] requires #440 provide other locales the ability to translate the app into other languages.~
   ~- this provides users an option when they want to know "why isn't this in my native language yet"~
* See alternate plan below

~3. [ ] ensure our FAQ is able to be localized~
* Less of a pressing need if rolling out without localization

~4. [ ] ensure our feedback form is able to be localized~
* Less of a pressing need if rolling out without localization

5. [X] have a response for potentially tone-deaf features in certain markets, such as #460 and #540
   - I'm not suggesting we need to make implementation changes prior to rolling out worldwide, but we do need a plan in place to respond to these known demands
* Response is to point people to open GitHub issues and/or encourage people to open new ones.

**Comment by sandysage** [comment]
@irrationalagent did some digging and discovered that more than half (56%) of clicks to the SMS 'get the app' modal during launch day were from non-en primary countries. India alone was 6% of those clicks.

**Comment by rtanglao** [comment]
SUMO is the best way to get your FAQ localized and more importantly keep it up to date as you change it, please ping joni savage or i when you want the FAQ on SUMO!. we need 2 weeks for localization and we'll need a list of strategic/preferred languages but popular languages like German should be no problem. Cheers and well done on the ongoing and  successful test pilot! ...Roland

**Comment by sandysage** [comment]
DONE!
