### ISSUE TITLE
Add documentation for developers to add their browser

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#546]
In order to support as many browsers — and user choice of browser — as possible, we should document how developers can add their browsers to the list we provide in Settings.

In Firefox-iOS we do something similar with password managers: https://github.com/mozilla-mobile/firefox-ios/blob/master/Client/Frontend/Share/ShareExtensionHelper.swift#L105

**Comment by joeyg** [comment]
@sandysage I took a stab at coming up with the minimum amount of code to add support for a new browser. Here is a branch adding support for the Duck Duck Go browser: https://github.com/mozilla-lockbox/lockbox-ios/compare/master...joeyg:duckduckgo?expand=1

**Comment by devinreams** [comment]
Thanks again for the sweet code example @joeyg, sorry I didn't write this up sooner...
