### ISSUE TITLE
Research biometrics API

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#55]

**Comment by sashei** [comment]
Findings:

It's straightforward to bring up the dialog box for built-in biometric features via the [LAContext](https://developer.apple.com/documentation/localauthentication) API. 

However, keychain items are available by default (to the app that created them) when the phone is unlocked so there is no actual unlock step needed in this case. The same is true if we're leveraging [on-disk encryption](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/StrategiesforImplementingYourApp/StrategiesforImplementingYourApp.html#//apple_ref/doc/uid/TP40007072-CH5-SW21) and storing items in the application's filesystem.

The unlocking step, then, is a way for us to be slightly more secure when users access their Lockbox account on iOS after the initial login, but isn't a requirement for retrieving anything from the keychain.

**Comment by sashei** [comment]
@sandysage @changecourse needs collaboration for product direction on how to move forward with our iOS biometric usage options, @linuxwolf may have some thoughts about security here

**Comment by sashei** [comment]
I'm closing this research story based on the UX input as seen in #35, #80, #81
