### ISSUE TITLE
Move request for email confirmation into webview 

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#553]
Depends on #242 (OAuth)

- [x] Ensure that the email confirmation step is tied to the authentication webview rather than on the entries list empty state, so the app doesn't give false expectations around being "Finished" with setup

- [ ] Consider removing the email verification from the empty state entries list (unless we want it as a fallback in instances where someone dismisses the webview and still hasn't confirmed email)

**Comment by devinreams** [comment]
>Ensure that the email confirmation step is tied to the authentication webview rather than on the entries list empty state

Tested and confirmed resolved at #242 

<img width="559" alt="screen shot 2018-07-27 at 9 39 32 am" src="https://user-images.githubusercontent.com/49511/43331095-39135236-9182-11e8-9f6d-72eddd1603e6.png">


>Consider removing the email verification from the empty state entries list (unless we want it as a fallback in instances where someone dismisses the webview and still hasn't confirmed email)

To this point, I agree with your thought and suggest we _do_ keep this state as a fallback for when the app is forcibly quit.
