### ISSUE TITLE
FxA language confusing for Lockbox users

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#555]
Some of the language around FxA verifcation is confusing, because it is not Lockbox specific.

Depends on #242 

- [x] Change "Continue to Firefox Sync" in **sign-in webview** to "Continue to Firefox Lockbox"
- [x] Change "Confirm Sign in to Firefox" in **email** to "Confirm Sign-in to Firefox Lockbox" 

_This may need to be tied to FxA efforts if it needs to be handled on their end, but placing within our repo for now so we can track against it._

**Comment by devinreams** [comment]
Confirmed the "Lockbox for iOS" app name is in place on:

- create account webview
- sign in webview
- email content
- confirmed sign-in webpage


<img width="515" alt="screen shot 2018-07-27 at 9 39 10 am" src="https://user-images.githubusercontent.com/49511/43331216-76fe904c-9182-11e8-9259-29347fe12120.png">

<img width="581" alt="screen shot 2018-07-27 at 9 49 54 am" src="https://user-images.githubusercontent.com/49511/43331231-81e405a0-9182-11e8-9237-7449f66f2145.png">

<img width="784" alt="screen shot 2018-07-27 at 9 39 53 am" src="https://user-images.githubusercontent.com/49511/43331256-927360a0-9182-11e8-9f8f-11712598c64d.png">
