### ISSUE TITLE
Switch to decoupled email FxA flow

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#556]
Depends on #242 (OAuth) and https://github.com/mozilla/application-services/issues/124

Some UR participants did not immediately know if they had an FxA account, when authenticating with Lockbox for the first time.

_Pending the completion of OAuth..._

- [x] Switch to decoupled, email-first FxA flow, instead of standard "sign-in" with email and password

**Comment by devinreams** [comment]
Noted during a quick backlog review: this may/will become the default so we may not need any code changes...

**Comment by eoger** [comment]
The fxa-client framework includes the fix in its `0.2.1` version

**Comment by devinreams** [comment]
Thanks @eoger! Bumped version and tested and confirmed at #242 

<img width="559" alt="screen shot 2018-07-27 at 10 02 41 am" src="https://user-images.githubusercontent.com/49511/43331995-3a8fd218-9184-11e8-8e02-d1ae9595aef3.png">

<img width="559" alt="screen shot 2018-07-27 at 10 03 03 am" src="https://user-images.githubusercontent.com/49511/43332016-46be2b52-9184-11e8-84b0-2201435ebd1a.png">
