### ISSUE TITLE
XCUITests: prevent failures from blocking branches and builds

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#561]
We want our CI to build so we can run test builds on buddybuild.

We also want to know if failures occur that break something.

But we don't want to be blocked if a flakey integration test is failing.

**Comment by devinreams** [comment]
@mozilla-lockbox/mobile-engineering @isabelrios For now I'm setting buddybuild to allow failures to be warnings while test 0 (or 1?) gets sorted out.

![screen shot 2018-07-16 at 4 20 48 pm](https://user-images.githubusercontent.com/49511/42786684-497c77e0-8914-11e8-9625-4c49db684026.png)


If you think we should do something else in the meantime please let me know. 😁

**Comment by isabelrios** [comment]
Thanks @devinreams I think that's fine.
In theory and hopefully, that flaky test is fixed in PR #525. Also, I'm working on another issue grouping the tests to try to make them more independent from previous tests/failures/order.

**Comment by devinreams** [comment]
>In theory and hopefully, that flaky test is fixed in PR #525. Also, I'm working on another issue grouping the tests to try to make them more independent 
 
@isabelrios Ah yes, I meant to mention I saw #525 and your other issue #531.

I figured _this_ was worth calling out separately as something to consider (and to document my config change in buddybuild) but if it all gets handled at once, excellent! Thanks for chiming in...
