### ISSUE TITLE
Send Feedback form sent without filling/selecting any option

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockbox/lockbox-ios#565]
I was just looking at this menu, being curious, and by mistake pressed the arrow button, and the form was sent, but I did not change anything from the form or added any feedback.

Just wondering if at least something should be changed in order to allow it to be sent and show the confirmation message "Thank you for your feedback..."

**Comment by devinreams** [comment]
@mozilla-lockbox/product are you aware of some (hopefully simple) configuration or layout changes in the survey software to support a clearer UX on the "next" (submit) button and a confirmation screen?

**Comment by sandysage** [comment]
@nickbrandt cleaned up the form with a bit of hacking in SurveyGizmo to use text for the submit button as seen here: 
![Screenshot_2018-08-01 Provide feedback for Firefox Lockbox - Builder - Style.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dc07ab1a9a2600115c9b6f/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc64167f3e7955e31b628af521bb473b070a0a1afe100b0454aaa6cb3bd0ef7e25dc0343fdad320c2f946259bca5926dfa58e674de0d95abace90889b46837fb99cf0d6144504bcded5727a5901fcc0cfe48e24906f0453161e676347942c04d237d3d753ab9be8e08d3da3dfdf0456d44c2f1e5fd1c13a47fdbc60d7567515fab2a32a74f.png)

He also tweaked the 'thank you' confirmation page to more clearly communicate that feedback has been submitted.
![Screenshot_2018-08-01 Provide feedback for Firefox Lockbox - Builder - Style(1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dc07ab1a9a2600115c9b6f/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc64167f3e7955e31b628af521bb473b070a0a1afe100b0454aaa6cb3bd0ef7e25dc0343fdad320c2f946259bca5926dfa58e674de0d95abace90889b4683de6929d532c5e4747d3aa0e71b29359cd51a24fb54556a7176537b071347c47961b7078383177fdeec344c5d43ef0e54d761c9da1f6f00413a976d9c20a7262515faf2f35b40a5f9b2d.png)

**Comment by sandysage** [comment]
@isabelrios can you confirm this looks good and if so close out this issue? Thank you!

**Comment by sandysage** [comment]
Also we intentionally made the decision to not make any questions required. We'll accept any feedback we can get and not force a user to enter more than they want to provide.

**Comment by isabelrios** [comment]
@sandysage The form looks great! thanks! I understand not to make the questions required, but at least the start rating so that user does not send empty feedback and the message shown is like if he has entered some info. But if that's the decision, I'm fine with that and we can close this issue :)
