### ISSUE TITLE
Autolock timer does not lock the app

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#566]
Opposite of #463 

Something may have regressed. We have two potentially related PRs #537 #551 that may have introduced a change that causes the timer not to lock. But when I tried testing against both I couldn't isolate and find which (if either) actually caused a problem ... because they both ended up working just fine for me.

@sandysage and @nickbrandt have experienced inconsistencies where some timers do work, then timers don't work at all.  So I wonder if there is a userdefaults or data problem?

Opening this issue to try to gather more data points from folks and, ideally, really consistent steps to reproduce the problem.

**Comment by nickbrandt** [comment]
I'm not able to find a pattern in which to reproduce this, but here is my latest round of testing:

Installed fresh copy of 1657 Branch (made sure to delete previous download and reinstalled)
Went to Entry List, waited 5 min > App Locked ✅ 
Changed Auto Lock to 1 min, backgrounded app, waited 1 min > App Locked ✅ 
Changed Auto Lock to 15 min, waited over 15 min > App did **not** lock ❌ 
Changed Auto Lock to 1 min, waited over 1 min > App did **not** lock ❌ 
Changed Auto Lock to 5 min, waited over 5 min > App did **not lock ❌ 
Backgrounded app, waited 5 min > App Locked ✅ 
Changed Auto Lock to 15 min, backgrounded app, waited over 15 min > App did **not** lock ❌

**Comment by devinreams** [comment]
I did push a release to Test Flight last week and haven't heard from anyone about locking not happening (or being unexpected) ... yet.
