### ISSUE TITLE
Logins are not displayed “No entries found” after restarting the app

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#571]
Build: master 6b50a172
Device: iPhone 8 iOS 11.3

Steps to reproduce:
1. Launch Lockbox after a clean install
2. Tap "Get Started"
3. Login to FxA and wait for logins to sync
4. Force close Lockbox from app switcher
5. Re-open Lockbox

Actual results:
- No logins are displayed. 

Note:
- This is also happening when Reinstalling the same version over the existing app.

**Comment by devinreams** [comment]
@SimonBasca Hmm, so you're not getting entries appearing in the list _at all_? Just a blank gray screen with a search bar above it (none of our "empty state" blurbs appearing)?

And just to be super clear: there's no FxA email confirmation sitting in your inbox anywhere?

And if you manually "Lock Now" and unlock do they appear then?

**Comment by isabelrios** [comment]
In case, it is useful...
This has happened when launching the automated tests. It is very rarely seen, but you can get to this state in which the app says No entries found using the same account with the saved entries:
https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5b586f4f0ade570001d34f4c/test/435eee0d-b022-408f-85dc-1deba1946887/f2c85067-1d01-4c6f-ab13-10614ad640cd

![captura de pantalla 2018-07-25 a las 15 32 02](https://user-images.githubusercontent.com/1897507/43203992-0aa03f30-9020-11e8-8a83-ad69d52964e3.png)
