### ISSUE TITLE
Web Address link does not launch app when browser setting is not set to Safari

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-ios#572]
When the user taps on the Web Address link (when Safari is set under "Open Websites in" options), and there is an associated app to the domain, the app is launched for the user instead of loading the URL in the browser.

Ideally, this would work the same if a user had chosen one of the other options (Firefox, Chrome, etc)  in the "Open Websites in" setting. Currently though, it does not work with anything other than Safari.

This issue is to evaluate the level of effort it would take to implement this across the browser options and to then prioritize this feature.

**Comment by joeyg** [comment]
I have been looking into what other apps that let the user chose a browser do. So far I’ve looked at Slack and Google Inbox. It seems like for some apps (Twitter, LinkedIn, OpenTable) Inbox knows to open the app even if Chrome is set as the default browser. I’m not sure if this is generally available or if certain apps are hard coded.
