### ISSUE TITLE
The app auto locks immediately after unlocking it

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#573]
iPhone X (11.4)
master 6b50a172

I don't have STR's for this but I saw it happening a few times on this build.

Basically, I've unlocked the app and waited for the logins list to populate. After waiting a couple of seconds, the app auto locked (The auto lock option was set to 5 minutes.)   

Will do some more tests around this to see if I can find precise STR.

**Comment by devinreams** [comment]
Interesting. 🤔 Thanks @csuciu.

We've seen somewhat relating locking-when-not-expecting it. Cross-linking for posterity: #463

**Comment by devinreams** [comment]
With the refactor at #586 and my continued testing (Build 1846 was latest today) I believe we can confidently close this as the locking timer is now improved for both the storage locking and user experience.

Please feel free to re-open if anyone finds this happening again...

**Comment by devinreams** [comment]
This was encountered and reported again by PI. Re-opening...

**Comment by changecourse** [comment]
Is this still an issue experienced on some of our latest builds?

**Comment by csuciu** [comment]
I saw this happening a few times while testing build 1.3.1 (2517).
After manually locking the app then unlocking it, the app auto-locks immediately, prompting again for the passcode.

**Comment by sashei** [comment]
This should no longer be an issue now that we do not lock in the foreground.
