### ISSUE TITLE
Remove `ActionHandlers`

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#578]
Described by tech debt comments in https://github.com/mozilla-lockbox/lockbox-ios/blob/master/docs/architecture.md

This should be a simple change but will touch a lot of files / be fairly tedious.

**Comment by sigito** [comment]
What exactly is necessary to be done here? Do you want to remove entirely `ActionHandler` protocol, and move code in every existing implementation inside of corresponding Presenters?

**Comment by sashei** [comment]
@sigito A little bit of both; the `ActionHandler` protocol will be removed entirely, yes. `Presenter`s will dispatch actions directly to the dispatcher rather than going through an `ActionHandler`. Only a few of the `ActionHandler`s actually do any work, and those that do should have the implementation moved to a corresponding `Store`. 

I just took a quick look through, and the `ActionHandler`s that will need to become `Store`s are:

- [ ] `CopyActionHandler`
- [ ] `LinkActionHandler`
- [ ] `SettingActionHandler`

The bulk of the work here will be updating the tests. If you are interested in doing pieces of the implementation, feel free to push in-progress commits and I'd be happy to help out with the more tedious parts.

**Comment by sigito** [comment]
@sashei, thanks for your reply. I go through the action handlers one by one and cleanup them. Would you prefer a big ongoing PR with all the migrations being added over time, or a PR per handler?

**Comment by sashei** [comment]
@sigito, I'd prefer a large ongoing PR associated with this issue (it's hard to attach PRs to issues and close them in an ongoing way). Thank you!!

**Comment by sigito** [comment]
@sashei, I have removed all the basic ones. Could you help with more details on how to transform the last ones to stores?

**Comment by sashei** [comment]
@sigito This PR is looking awesome! And you're updating specs! 🎉 

To transform the `LinkActionHandler`and `CopyActionHandler` into `Store`s, I would do the following:

- `LinkActionHandler`: Move all the functionality into a `Store` that subscribes to the `Dispatcher for `ExternalLinkAction` and `SettingLinkAction`. It can call the `openURL` or `openSettings` functions from inside of the `Dispatcher` subscription as appropriate. Possible gotcha: make sure to instantiate the new `ExternalLinkStore.shared` singleton, maybe in the `AppDelegate`.
- `CopyActionHandler`: Rename the `CopyConfirmationDisplayStore` to the `CopyStore`. Listen for `CopyAction`s from the `Dispatcher` and do the relevant `UIPasteboard` work (from `CopyActionHandler`). I think we can get rid of the `CopyConfirmationDisplayAction`s and just have an `Observable<CopyField>` on the new `CopyStore`, updated after successful copying actions are dealt with. 

I think that the `SettingActionHandler` would be best transformed as part of #519, so feel free to leave that one `ActionHandler` alone for now.

**Comment by sigito** [comment]
@sashei, thanks. I would try to follow your suggestions. 
Also, I am traveling this week, so I would not update the PR until next week.

**Comment by sigito** [comment]
@sashei 
1. I am working on `CopyActionHandler`. It passes data to telemetry by dispatching the action. However now the store itself listens to these actions. Is there a different way to pass data to telemetry?

> I think we can get rid of the CopyConfirmationDisplayActions and just have an Observable<CopyField> on the new CopyStore, updated after successful copying actions are dealt with.
2. Excuse my total lack of Rx knowledge, but could you help with this too?
3. I do not recall that `TelemetryActionHandler` existed when I started, or I simply missed it. It also should be migrated, right?

**Comment by sashei** [comment]
@sigito yesss, I noticed the `TelemetryActionHandler` too last week and thought of this task...

I think we can leave the `TelemetryActionHandler` for now. I'll put in the changes for `CopyActionHandler` this morning and then I think this PR will be good to go!!

**Comment by sigito** [comment]
@sashei, ok. Thanks. It's all yours then.
