### ISSUE TITLE
Fix XCUITests around OAuth login flow

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#582]
Merging #533 broke the uispecs :(

**Comment by isabelrios** [comment]
@sashei do you mean the XCUITests or something else? If it is about the XCUITest, I fixed them on the #530 PR...

**Comment by sashei** [comment]
@isabelrios yes! mis-typed

**Comment by sashei** [comment]
I added a note in #530 to reflect this.

Thank you @isabelrios !!!

**Comment by isabelrios** [comment]
:) Okay! assigning it to myself then. Do you agree on fixing them on that PR or prefer a new one?

**Comment by sashei** [comment]
@isabelrios fixing them on that PR is fine :)
