### ISSUE TITLE
Update `contributing.md` or relevant doc to point people to specs

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#584]
Every first-time contributor we've had does not include test updates in their PR; I poked around in the documentation and we don't actually mention specs or give instructions about how to run them in the getting started documentation.

**Comment by sashei** [comment]
@linuxwolf do you have any thoughts about where this should go?

**Comment by linuxwolf** [comment]
I think it's acceptable to add to a **How to Contribute Code** section to `docs/contributing.md`, and outline the basics that a new contributor ought to be aware of.  The [extension's contribution page](https://github.com/mozilla-lockbox/lockbox-extension/blob/master/docs/contributing.md) might be a good starting point (although it doesn't say anything about tests, in hindsight it ought have).
