### ISSUE TITLE
FxAccount Management Page is open when starting the app after disconnecting the account

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockbox/lockbox-ios#588]
Latest master: 7047fac
iOS 11.4 iPhone 6s

Steps:
From Lockbox main page go to Settings -> Account
Disconnect from Lockbox
Tap on Get Started

Actual
The FxAccount Management page is shown
![img_0013](https://user-images.githubusercontent.com/1897507/43465016-b5d0ec04-94dc-11e8-8edd-be114ee75fe7.PNG)

Expected
Not sure where user should be taken but to a screen where he could log in again as it happened before. Now it is not possible to do anything...loging out to try to log in again take us to issue #587 

related to #440

Depends on #496 
Depends on #422

**Comment by devinreams** [comment]
Thanks, @isabelrios. This is a side effect of us changing to use OAuth now and will make sure we clear credentials at #422 soon so the user doesn't reach this screen and fully "signs out".

**Comment by devinreams** [comment]
I did run into this again after force quitting and dropping to the welcome screen to “Get Started” at #592 

Keeping this closed but cross-linking to that issue as users still should never see this...
