### ISSUE TITLE
Disconnect and Reconnect results in the app stuck showing “No matching entries” state

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#592]
Steps to reproduce:

- install app
- “Get Started” and sign in to test account
- confirm via email if needed, click “Finish”
- Settings > “Disconnect”
- “Get Started” and sign in to test account again
- click “Finish” and then land on entries screen

Expected: see all my entries
Actual: see the “No matching entries” blurb
Workaround: force quit app and re-launch and sign in

Related bug: #571 (“no entries found” blurb)

**Comment by devinreams** [comment]
if I force quit the app and re-open, it takes me to the Welcome “Get Started” screen, not the entries list.

When I click “Get Started” I’m on the Firefox Accounts management screen, not the email-first sign in flow.


Suggesting the sign in mostly but doesn’t “fully” complete? Or something?

**Comment by devinreams** [comment]
And then when I force quit again it took me to the entries screen signed in with my entries just fine. So it fixed itself?

**Comment by isabelrios** [comment]
I have seen this when running the XCUITest, that disconnect/connect the account and that launch the app each time. But did not get consistent steps. See comment in issue #571 sorry thought it was the same and did not open a new issue for this... 
As you say, this happens in a test but in the next one entries are shown fine, the app recovers itself.
This happened at the very beginning, I was not seeing it a lot until last week or so, where it is happening more frequently.

**Comment by csuciu** [comment]
This might be the same issue #571

**Comment by devinreams** [comment]
I think we have two issues and to help distinguish them I renamed the other one accordingly:

1. “No matching entries” state which is what you would expect to see if you were typing in a search and couldn’t find any matches (this bug) but are seeing it for some reason

2. The “no entries found” state which is when we don’t get any logins back from the Sync service, or we’re not handling something properly (issue #571)

They may be happening at the same time or for the same reason, but since they are different “blurbs” I’d be surprised if that’s the case.

**Comment by isabelrios** [comment]
Oh @devinreams sorry! I was reading here No entries found...sorry for the confusion!
I was able to repro the No matching entries message too with the steps you said disconnecting the account.

**Comment by nickbrandt** [comment]
Tested this on build 1950

1. Downloaded build > Signed In > Entries Synced ✅  > Disconnected
2. Re-signed In > No Matching Entries screen ❌  > Lock Now > Directed to Get Started / Welcome
3. Re-signed In > No Matching Entries screen ❌  > Disconnected
4. Re-signed In > No Matching Entries screen still ❌ 

Is there a specific build that I should be testing this against?

**Comment by devinreams** [comment]
I tried:

- downloaded old 1.1.1.1717 tag build
- signed in
- entries sync ✅ 
- upgrade over with build 1950
- sign in again due to OAuth
- entries sync ✅ 
- upgrade with Sasha's latest branch build 1954 (631-preserve-version)
- disconnect
- sign in again
- entries sync with no "no matching entries" error ✅ 
- disconnect
- sign in again
- "no matching entries" ❌ 

So I'm able to reproduce this still...

**Comment by devinreams** [comment]
I'd like to downgrade this bug since there is a work around and it only happens when users disconnect and immediately try to re-connect.

I don't want it to block a 1.2 release...

**Comment by joeyg** [comment]
@devinreams I think this might also be fixed by #752. Could you test again on that branch?

**Comment by devinreams** [comment]
@joeyg I agree. the "No matching entries" state appears but _temporarily_ as expected. Not permanently, as was happening here. I updated your PR to connect here. Thanks for circling back here! 🥇
