### ISSUE TITLE
Sometimes hitting the "Disconnect" button does not disconnect the account 

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#595]
I'm not sure what could trigger this but I saw it happening a couple of times.

1. Unlock the app with FaceID.
2. Go to Lockbox Settings -> Account.
3. Press "Disconnect Firefox Lockbox".
4. In the confirmation pop up, hit again "Disconnect"

Expected: The account is disconnected and the app goes to the "Get Started" screen.

Actual: **Sometimes**, the confirmation pop up is dismissed, but the account is not disconnected. The app remains on the "Account" page.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1866605/43513689-14d3b4d4-9587-11e8-9a3e-d552cef6b766.gif)

**Comment by devinreams** [comment]
@csuciu and this is happening against the latest `master` code, right? Not the 1.1.1 tag?

**Comment by csuciu** [comment]
No, it's happening on 1.1.1.1717.

**Comment by devinreams** [comment]
Ah ok, thank you. I will also try hammering and see if we can reproduce it.

We’ll also decide if this is a bad enough bug to prioritize and block the release or aim to fix it later...

**Comment by devinreams** [comment]
I was testing this a lot today, especially at #592 and haven't encountered it again (I definitely did before). Since we tweaked the disconnect at #591 this may have been solved so will close for now.

Please feel free to re-open if anyone finds this happening again...
