### ISSUE TITLE
UnitTest Failure: ItemListPresenterSpec: ItemListPresenter___onViewReady____

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockbox/lockbox-ios#601]
While checking the XCUITest, I have seen this test failing lately:
ItemListPresenter___onViewReady____

Here the logs details:
https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5b62c1617144010001771bcb/test/179efb40-8047-46c8-8a9e-e9e9e729329b/780128ea-4318-4138-b42c-62e0f767a239

Just in case it is not tracked yet.

**Comment by devinreams** [comment]
Thanks @isabelrios.

If I read it right, this was passing at Build 1740 (#533)

But then I think it started failing at 1754 (#591)

Note to self to re-enable failing builds if tests fail after the XCUITests PRs are merged: #530
