### ISSUE TITLE
UnitTest Crash: AccountStoreSpec tests

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockbox/lockbox-ios#604]
There are four unit tests failing, starting when this commit landed: 

0bdeb6d0e764e71e725e38f711849bc34b46c739 (#599)
Please see logs: 
https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5b635ddd80ad240001af53cc/test/bc0a24d0-4787-4451-ae5a-847e62b25c98/61149c64-5396-4785-860d-fe735d4a8215

**Comment by devinreams** [comment]
Thanks again @isabelrios. I should have double checked. 

@jhugman can you please look into these tests? I don’t think it’s worth reverting the PR but if you think we should we certainly can.
