### ISSUE TITLE
Display disclaimer if user enables Lockbox as autofill credential provider without authenticating

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#611]
### Acceptance Criteria

Install Lockbox without logging in
Enable Lockbox as a credential provider from Settings

Behavior: Extension displays a disclaimer directing users to authenticate in Lockbox.app

### Visual Design

**InVision**
https://mozilla.invisionapp.com/share/BQEUSO0S2#/313162524_AutoFill_-_Autofill_Passwords_-_Enable_-_Not_Authenticated

**Zeplin**
https://zpl.io/VKqWZP8

Note: "Sign In" button would navigate users to the FxA sign in flow within the Lockbox app.
If we go the low level of effort route, and not direct the user to our app, we would need to update the copy on the button to "OK" instead of "Sign In".

depends on #612

**Comment by sashei** [comment]
Potentially route back to Lockbox with a button? Need some eng exploration

**Comment by devinreams** [comment]
Spectrum of elegance®:

1. Continue drops you back into Settings (so user has to know to go to Lockbox and sign in - low)
2. Drop user to Lockbox welcome screen (universal linking required)
3. Throw user all the way into Lockbox FxA screen (may be same effort as 2)

To consider: how often will this happen? First time install and didn't launch the app to sign in...

**Comment by devinreams** [comment]
Closed at #673
