### ISSUE TITLE
Provide entry when requested via the QuickType bar

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#615]
When a user selects an entry via the QuickType bar, provide the full entry to populate the text field.

Don't forget to `touch` the item so that its use is reflected in `Recently Used`

NOTE: this story assumes that the application is unlocked. Locking / unlocking is handled in #610.

depends on #612

**Comment by devinreams** [comment]
Tested the filling for both apps and website forms at #666 👍 

Also confirmed the datastore / item is "touched" so it appears as recently used at https://github.com/mozilla-lockbox/lockbox-ios/pull/639/commits/167688d96e6ee810b86d1b6f1de42cec3c01f282#diff-e8d990c7e6eabaabfe549bdaffbf0014R64 👍
