### ISSUE TITLE
Entry list

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#616]
When navigating to the list of entries, display a pre-filtered list based on the `ASCredentialServiceIdentifier` (eg, `url` or `domain`). 

Important details:
- `Cancel` button cancels the autofill request entirely (calls `self.extensionContext.cancelRequest(withError: NSError(domain: ASExtensionErrorDomain, code: ASExtensionError.userCanceled.rawValue))`
- No access to settings or sorting options
- Filter still has same behavior
- Selecting an entry closes the extension, provides the complete `ASPasswordCredential` to the requesting application, and `touch`es the item so that its last-used date is reflected in `Recently Used`

Note that this story assumes that Lockbox is unlocked, the locked case is handled in #610

Requires #612

### Visual Design

**InVision**
Example App Flow for AutoFill
https://mozilla.invisionapp.com/share/BQEUSO0S2#/316626653_AutoFill_-_App_Example
Credential List*
https://mozilla.invisionapp.com/share/BQEUSO0S2#/316128721_AutoFill_-_App_Example_-_Credential_List
*The "Select a password to fill" copy would be persistent, EXCEPT when the user searches/filters the list to the No matching entries state (then we hide). After they clear the search it would reappear.

Credential List (showing how it will look when enhanced search is complete)
https://mozilla.invisionapp.com/share/BQEUSO0S2#/316128720_AutoFill_-_App_Example_-_Credential_List_-improved_Search-

Credential List - No Entries Found (none match provided domain)*
https://mozilla.invisionapp.com/share/BQEUSO0S2#/316626654_AutoFill_-_App_Example_-_Credential_List_-_No_Matches
*The "No matches found" copy would be persistent, EXCEPT when the user has entered anything in the search field (& on the No matching entries state for searching)

**Comment by devinreams** [comment]
Discussed today during planning: @sashei will hand this story off so @jhugman can write some code of his own tomorrow. 🙌
