### ISSUE TITLE
Preserve user's settings and authentication state when moving to Autofill

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#626]
Currently, we just assume that everything "exists" in the shared UserDefaults and Keychain world with the Autofill extension. 

However, all users on upgrade will still have their settings and authentication stored in the app-only versions. When we detect the upgrade, we need to read from the app-only Keychain and UserDefaults into the shared ones.

depends on #496 
depends on #609

**Comment by devinreams** [comment]
If we do _not_ do this story, then the user will be required to sign in again from the Welcome screen, right?

**Comment by sashei** [comment]
Correct. We should be able to manage this update from the background with no disruption to users though. I'm going to do this story next.

**Comment by devinreams** [comment]
Closed at #664
