### ISSUE TITLE
audit accessibility of view components

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#63]
[iOS Accessibility Documentation](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/iPhoneAccessibility/Accessibility_on_iPhone/Accessibility_on_iPhone.html#//apple_ref/doc/uid/TP40008785-CH100-SW3)

**Comment by sandysage** [comment]
This is now a duplicate of #99
