### ISSUE TITLE
Reauthentication Required on every launch

### ISSUE THREAD

**Issue by sigito** [mozilla-lockbox/lockbox-ios#631]
Every time I build and launch a simulator I get `Reauthentication Required` dialog.
<img width="559" alt="2018-08-22 22 30 42" src="https://user-images.githubusercontent.com/1129082/44489237-379beb00-a65b-11e8-8aed-c6c87ece95d4.png">

**Comment by sashei** [comment]
@sigito I am having trouble replicating this. Does it still occur if you run `xcrun simctl erase all` and launch the app after all the simulators have been cleared?
