### ISSUE TITLE
Access detail view for saved entry

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#64]
When I need to access an account, I want to see an entry's details to either copy credentials to my clipboard or view the username / password, so that I can easily put those credentials into the app or mobile browser.

## Acceptance criteria
- Should be able to get to the details of a saved entry including URI, username, password, notes if available
- Should not see notes field if not populated

## Visual design
https://mozilla.invisionapp.com/d/main#/console/12774944/267560603/preview
https://mozilla.invisionapp.com/share/XCEV238ZD#/279614760_Entry_Detail_-_Empty
https://mozilla.invisionapp.com/share/XCEV238ZD#/279614759_Entry_Detail_-_Address_Filled
https://mozilla.invisionapp.com/share/XCEV238ZD#/279655252_Entry_Detail_-_With_Notes

## Expected behavior
- tap row in list to go to "detail view"
- view details of that entry
  - hide notes not populated
  - show placeholder text for username, password, and URL if not populated

**Comment by sandysage** [comment]
This task does not encompass entry detail onboarding nor 'reveal' actions that can happen from this screen. Those can be created separately.

**Comment by sashei** [comment]
for "hide if not populated", does that apply to every possible entry field or just the notes field?

**Comment by sashei** [comment]
@changecourse @nickbrandt 
two things: I am going to need assets for the "shown" and "hidden" states on the password field, and what should the placeholder text be when there is not a username, password, or URL?

**Comment by nickbrandt** [comment]
@sashei 
Assets should now be available in Zeplin.

In terms of the placeholder text, we have decided to not show anything and have blank fields for those items, excluding Entry Name. We may instead be using the placeholder text in the Edit state, though we are still figuring some of that out. For Entry Name, if there is no URL provided, will default to "New Entry". If they provide a URL, ideally we would like to strip out the prefix and suffix of that URL and use it for the Entry Name. Below are a couple concepts showing how this would work. Let me know if there are any questions!

https://mozilla.invisionapp.com/share/XCEV238ZD#/279614760_Entry_Detail_-_Empty

https://mozilla.invisionapp.com/share/XCEV238ZD#/279614759_Entry_Detail_-_Address_Filled

**Comment by sashei** [comment]
What should be shown for the Entry Name if there is no provided entry name then?

**Comment by sashei** [comment]
@changecourse @nbrandt
design detail: apparently SFMono (Apple system monospace) is licensed to only be used in Apple-related apps. there are two system monospace fonts in iOS, `Menlo` and `Courier` -- which one of those (or third party) monospace font would y'all like to use here?

**Comment by nickbrandt** [comment]
I would say lets go with Menlo then, it appears almost identical. (ps. my tag is @nickbrandt :)
