### ISSUE TITLE
Start up crash due to FxAUtils

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#640]
browser profile related. see Build 1940 crash logs...

**Comment by devinreams** [comment]
@jhugman and @sashei spoke and asked James to _briefly_ look at this (like no more than an hour) and come back to autofill stories if no obvious solution to the crashes.

**Comment by devinreams** [comment]
Since the upgrade to 1.3 the number of crashes has effectively gone to 0. 

<img width="999" alt="screen shot 2018-09-24 at 4 12 22 pm" src="https://user-images.githubusercontent.com/49511/45982097-a54d8500-c014-11e8-88da-4a6e83543946.png">

@sandysage Let's consider closing this?

**Comment by sandysage** [comment]
Yup. The number of clients by app version also indicates that most everyone has upgraded to 1.3 by now: https://sql.telemetry.mozilla.org/queries/58761#152326

Closing.
