### ISSUE TITLE
Adjust event tracking of "successful login"

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-lockbox/lockbox-ios#645]
As a marketer I want to be able to distinguish the quality of users onboarded through various acquisition channels. The quality of these users will be evaluated based on their progression through the sign-in process (sign in, confirm accounts).

In order to track this quality across acquisition channels, we will need to configure Adjust event tokens for the following unique, user specific events (tokens in parentheses):
sign-in (cuahml) 
Confirm Account (pff1na)

Adjust documentation on how to track these events can be found here: https://github.com/adjust/ios_sdk#event-tracking

**Comment by joeyg** [comment]
@lwa-moz @sandysage What is the action that happens for the `Confirm Account`. The app presents the screen and then informs the user to go check their email. Is this event for the user going back to the app after that?

**Comment by lwa-moz** [comment]
The intended action would be completing confirmation, so the "event for the user going back to the app after" checking their email. 
The goal here is to track that the user has completed all actions required to access their passwords in Lockbox. I can rename the action in Adjust if there's an existing term that's preferred.

**Comment by joeyg** [comment]
I haven't found a good way to track the first event (sign-in). I think we want the event between these two screens - but they are both in the webview and there is no page change between them. @devinreams any ideas if this is done in other apps?

![simulator screen shot - iphone 8 plus - 2018-08-27 at 12 42 15](https://user-images.githubusercontent.com/490833/44681913-cc556e80-a9f6-11e8-94ee-31dddfdbaf72.png)

![simulator screen shot - iphone 8 plus - 2018-08-27 at 12 38 15](https://user-images.githubusercontent.com/490833/44681916-ceb7c880-a9f6-11e8-8889-487d937a1d05.png)

**Comment by devinreams** [comment]
>I haven't found a good way to track the first event (sign-in). I think we want the event between these two screens...

@joeyg Ah yes, you're right. I'll ask around and see if others are doing this.

@lwa-moz to help shortcut some searching around, are you able to get this level of reporting in other mobile or web apps right now? The new OAuth stuff we have here puts everything in the web page itself so the app doesn't _quite_ know when they transitioned from email entry to password entry (or sign up entry) to email confirmation to actually looking at their entries...

@mozilla-lockbox/mobile-engineering Do you all also have some initial reactions or ideas here?

**Comment by sashei** [comment]
I think tracking what happens in the webview would need to happen on the FxA side. Theoretically, we will be able to link the app with the FxA account analytics to merge those once we do #661 .

**Comment by lwa-moz** [comment]
@devinreams we've tagged in-app events in the past using Adjust tokens. Adjust does allow for tracking of events that occur in an App's web view, but the [documentation](https://github.com/adjust/ios_sdk/blob/master/doc/english/web_views.md) seems to suggest it would be a significant effort.

Are there any in-app events that could be tagged to determine, by proxy, that the user has entered a logged-in state? That would be my suggestion of what to lead with.

**Comment by sashei** [comment]
@lwa-moz definitely! this only gets tricky on our end when tracking in-progress login actions (wrong password submitted, waiting for email conf, etc). We can fairly easily track "successfully completed log-in" events.

**Comment by lwa-moz** [comment]
@sandysage revisiting this to see if connecting the Adjust token to the login event is doable in future releases.

**Comment by sandysage** [comment]
I'm moving this to the backlog to implement the relevant Adjust token (cuahml) to track "successfully completed log-in" events. This will allow us shared insight with our marketing partners around FxA registrations (a bottom line metric) to evaluate the quality of different traffic sources (like Leanplum).

This is relevant as we plan our next Leanplum campaigns which include “autofill w/ lockbox” and “get lockbox when you register an FxA”.
