### ISSUE TITLE
Update legacy screenshot in app store

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-ios#647]
One of the current screenshots in the app store showcases a legacy unlock screen. This needs to be updated with the new screenshot below.

![access](https://user-images.githubusercontent.com/5185090/44673464-dc665180-a9e8-11e8-9bbb-44145275eeb8.png)

**Comment by devinreams** [comment]
Hey @nickbrandt, I just swapped this out in the 1.2 version (pending) in App Store Connect.

It will go live when we publish the actual app update to the store.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/49511/44675602-3ae1fe80-a9ee-11e8-9f1b-b4ceb6ed8dd1.png">
