### ISSUE TITLE
Remove instances where a lock screen would be presented for users without biometrics or passcode setup

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-ios#650]
It was found that users who did **not** have biometrics or a passcode setup on their device were confused to see the unlock screen presented to them. Since this doesn't provide any added security to the user, we are opting to remove those instances of the lock screen for these users.

Research findings:
https://docs.google.com/spreadsheets/d/1t9bFIleS0IZ4Bt5IM149vlI6fSxxozbtDGkXQp_gqz0/edit?usp=sharing

**Comment by sashei** [comment]
This will be addressed in #786.
