### ISSUE TITLE
When signing in, the adress email is cut off on small screen devices

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#654]
iPhone SE (11.4)
Lockbox 11.2 (2018)

![simulator-screen-shot---iphone](https://user-images.githubusercontent.com/1866605/44723440-b15b2b00-aad8-11e8-8bb7-95475bc95199.png)

**Comment by devinreams** [comment]
Ah yes, I see this every day. I believe the FxA team is tracking the UI fix needed over here:

https://github.com/mozilla/fxa-content-server/issues/6396

...so I’ll close this as a duplicate. Thanks @csuciu 😁
