### ISSUE TITLE
After scheme split uitests screenshots aren't captured

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#672]
I think I broke the screenshotting feature at #642 

You can see screenshots on build 1996 but not since 2011. My bad. 😔 

FYI for @isabelrios but I'll look at this since I was the one who touched the schemes last

**Comment by devinreams** [comment]
Yeah this is entirely due to moving stuff around at #642. (if I revert that commit the ui tests build _and_ catch screenshots)

But I can't quite tell what needs to move from the Lockbox scheme into the uitests scheme to get the shots working again. I'll keep playing around with it at `fix-screenshots-maybe` branch...

**Comment by devinreams** [comment]
Yeah this is entirely due to moving stuff around at #642. (if I revert that commit the ui tests build _and_ catch screenshots)

But I can't quite tell what needs to move from the Lockbox scheme into the uitests scheme to get the shots working again. I'll keep playing around with it at `fix-screenshots-maybe` branch...

**Comment by devinreams** [comment]
I duplicated the `lockbox` scheme into `uispecs` and they're running OK but still not storing screenshots as expected / where they want them, it seems:

```
Problem writing screenshot: 02EntryListUICTContentSizeCategoryL to file:///Users/buddybuild/Library/Caches/tools.fastlane/screenshots/iPhone%208-02EntryListUICTContentSizeCategoryL.png
Error Domain=NSCocoaErrorDomain Code=4 "The file “iPhone 8-02EntryListUICTContentSizeCategoryL.png” doesn’t exist." UserInfo={NSFilePath=/Users/buddybuild/Library/Caches/tools.fastlane/screenshots/iPhone 8-02EntryListUICTContentSizeCategoryL.png, NSUnderlyingError=0x600000443150 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

Compare [lockbox](https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5b8f14aedffd180001c75c70/test/f54bfbb7-d7f0-4335-b049-aab2ce241e25/e0bab07d-abbf-48be-bccb-274d15c30f2b) scheme build with screenshots ✅ and [uispecs](https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5b8f14b1dffd180001c75c73/test/9c963cbe-3c5b-4e26-afe6-1e19e2490ba2/09ae426d-35a5-4465-9944-5f8b479de451) without ❌.

_Ignore the fact they are pass/failing opposite of each other..._

**Comment by isabelrios** [comment]
> FYI for @isabelrios but I'll look at this since I was the one who touched the schemes last

Sorry @devinreams I just read this. I'm not very familiar with all the screenshots environment but I can try to help to get this fixed. Will look into this

**Comment by devinreams** [comment]
Thanks @isabelrios. I'm wondering (out loud) if it has to do with the target being different from the app here perhaps? So maybe its storing files in one place (target name) but expecting them to be named the other (app, or vice versa)? Hmmmm 🤔

**Comment by isabelrios** [comment]
Thanks for sharing your thoughts :) Honestly, so far, I have no idea :) I will investigate and see if I get to the cause of the problem... 🤞

**Comment by isabelrios** [comment]
@devinreams A few findings after some tests...
I think we have to updated the `SnapshotHelper.swift`. I went to a previous commit to your patch and it was failing too. After I run `fastlane snapshot update` I got the screenshots and the html report when running `fastlane snapshot` working correctly. I went back to the latest commit, and it also worked.
But when running a single test, I was still seeing the error message. Since the `~/Library/Caches/tools.fastlane/` was created successfully with previous command, I manually added the screenshot folder, `~/Library/Caches/tools.fastlane/screenshots` and everything worked...
So, that is locally and half manually... not sure how we can reproduce the second part so that we get everything completely working again....

**Comment by isabelrios** [comment]
Not sure if this is a valid solution as a workaround, I have added a post build action for the uispecs schema ```mkdir -p ~/Library/Caches/tools.fastlane/screenshots```,  the error is gone and the screenshots saved...

**Comment by devinreams** [comment]
> the error is gone and the screenshots saved...

That's awesome! And you beat me to trying exactly that (myself). If it works I say we commit it and let it run. Thank you very much for the help here @isabelrios! And sorry for accidentally creating work for you. 😔
