### ISSUE TITLE
"Never" autolock timer setting always unlocks app even after "Lock Now"

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#693]
Encountered at https://github.com/mozilla-lockbox/lockbox-ios/pull/666#pullrequestreview-153960306 and briefly discussed with @sandysage and @sashei.

Placeholder to prioritize and then revisit the user story/expectations and if we want to change anything about the current behavior.

Right now (and up until now) you can set your Autolock timer setting and manually lock the app, and it will unlock. In other words, the "Never" setting means it will never be locked (via timer or otherwise).

**Comment by nickbrandt** [comment]
This is a good catch. I never noticed this, as if you have it set to "Never" in Auto Lock, select "Lock Now", the app locks and still presents the unlock screen if you background and then foreground the app (as desired). Though if you force quit and reopen, I am no longer prompted.

Ideally, the Auto Lock setting would **only** apply to the app auto locking. Meaning, if a user chooses the "Lock Now" option, we would lock the app and prompt for unlock on both foregrounding as well as cold open (and any other instances of needing to unlock, i.e. AutoFill).

**Comment by sashei** [comment]
@nickbrandt that's what I would expect as well.
