### ISSUE TITLE
Upgrading from 1.2 to 1.3 requires user to sign in again

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#694]
I upgraded from 1.2 (Build 2051 on production) to 1.3 (Build 2224 on master) and it forced me to "Get Started" and sign in again on the Welcome screen:

- with existing app installed: Disconnect
- delete existing app
- install build 2051
- sign in and confirm (with `dreams@mozilla.com` which has 2FA)
- install build 2224 (upgrade)
- open app

Expected: takes me into entry list screen already signed in

Actual: shows me "Welcome" screen with "Get Started" button to sign in (and FxA page "remembers" I was using `dreams@mozilla.com` previously)

**Comment by devinreams** [comment]
@nickbrandt @sashei are either of you able to reproduce this?

One side benefit: it means I saw the very nice "AutoFill" set up screen and so I made sure to enable it. 🙃

**Comment by sashei** [comment]
@devinreams yes, can definitely repro. confusing because I feel like we had this working before, but maybe I'm mistaken :p

**Comment by devinreams** [comment]
>I feel like we had this working before

Oh we definitely [did](https://github.com/mozilla-lockbox/lockbox-ios/pull/664#pullrequestreview-151129767).

For what its worth, this is why I thought we should start gathering up test cases for _all_ scenarios at #697 (not just the branch in progress). I'll double check and make sure other major stories are captured there...

**Comment by sashei** [comment]
I'm closing this as we are primarily at 1.3 or above in ITC now.
