### ISSUE TITLE
Copy / Paste credentials from details view

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#70]
When I need to access an account, I want to copy the username or password so that I can easily paste those credentials into the native app or mobile browser where I'm logging in.*

(*) Without seamless app or browser integration, copy/paste is the best option for getting a user log in access on iOS.

## Acceptance criteria
- Should be able to copy username from details view
- Should be able to copy password from details view
- Should be informed of copied credential (see https://github.com/mozilla-lockbox/lockbox-extension/issues/318)
- Should be able to navigate out of the Lockbox app, to either app or mobile browser, to paste copied credentials

## Visual design
https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/267560603

## ToDo
- [x] username field
- [x] password field
- [x] confirmation toast

**Comment by sashei** [comment]
😬 sorry for the late notice on this @changecourse @nickbrandt  -- I need the asset for the green checkmark in the confirmation popup.

**Comment by changecourse** [comment]
Here you are! 

[confirm.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/1785837/confirm.zip)

**Comment by sashei** [comment]
🙌🏼
