### ISSUE TITLE
Selecting entry suggestions from QuicktypeBar or Navigating to Cred List doesn't prompt for authentication with Passcode

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-ios#700]
In places where we are prompting for authentication for AutoFill (selecting entry from QuicktypeBar, tapping Key icon > Lockbox), if the user does not have biometrics setup (but does have passcode), it is not prompting the user to enter their Passcode. 

- Selecting a QuicktypeBar suggestion entry (currently, from what I understand, we are letting the OS handle auth for this. we may not be able to set a fallback to passcode?)
- Navigating to the Credential List (key icon > Lockbox)

Screen captures below:

**Safari - QuicktypeBar Suggestion**
![safari-quick](https://user-images.githubusercontent.com/5185090/45385815-04e87100-b5cf-11e8-8388-bf2b68ba898e.gif)

**App - Navigating to Cred List**
![app-cred-list](https://user-images.githubusercontent.com/5185090/45385778-f306ce00-b5ce-11e8-8864-6070a62114ed.gif)

**Comment by sashei** [comment]
@nickbrandt yes, for the quicktype bar suggestions in particular the prompt comes from the system so we can't control whether they use a passcode or not

**Comment by sandysage** [comment]
Quicktype bar: we have no control over.
Credential list now falls back to. the passcode correctly. Closing this as fixed.
