### ISSUE TITLE
Add screenshot to App Store to show AutoFill?

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#709]
Seems prudent to advertise when 1.3 and iOS 12 are out

**Comment by nickbrandt** [comment]
Good idea @devinreams , thoughts on something like this? @sandysage 

![autofill](https://user-images.githubusercontent.com/5185090/45451612-c8814780-b698-11e8-8521-41dc95fac2d8.png)

**Comment by devinreams** [comment]
Looks nice, I just added the screenshot to the last slot amongst the other screenshots @nickbrandt 👌 

Will close as complete but we can swap this out if @sandysage or you have any other ideas or changes you'd like to make.
