### ISSUE TITLE
Sorting options

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#71]
- [ ] alphabetically
- [ ] recently used

## Visual Design

**InVision**
https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/268014044
Recently Used Selected: https://mozilla.invisionapp.com/share/XCEV238ZD#/285909362_Entry_List_-_Sorted_Recently

**Zeplin**
https://zpl.io/bokk6mX
Recently Used Selected: https://zpl.io/VxB3Kxk

**Comment by sashei** [comment]
I'm curious about the best way to make this component accessible for vision-impaired users.

**Comment by sashei** [comment]
@sandysage @changecourse should the alphabetic sorting rely on only the item's title, or other parameters as well / if the title is missing?

**Comment by sashei** [comment]
@changecourse @nickbrandt what should the selector in the upper left look like when the user has selected "Recently Used" as their sorting option?

**Comment by nickbrandt** [comment]
@sashei I added a screen showing how this would appear. Essentially we are just replacing the label with "Recent".

**Comment by sashei** [comment]
@nickbrandt @changecourse also, there is no "highlighted" or "selected" color for this button in Zeplin.

**Comment by nickbrandt** [comment]
Let's handle this the same way we are with the "pressed" state for the Back button on the detail page, where we reduce the opacity to 60% of the clicked item.

**Comment by sandysage** [comment]
> should the alphabetic sorting rely on only the item's title, or other parameters as well / if the title is missing?

Let's start with just the item title. It's my understanding then, any items with missing titles would appear first in the ordering. Does that seem right? And then maybe numerical titles (eg an IP address)?

**Comment by devinreams** [comment]
>should the alphabetic sorting rely on only the item's title, or other parameters as well / if the title is missing?

And I don’t know if this would be appropriate, but perhaps this is an opportunity to standardize and use a the same/similar approach to what @jimporter has implemented in the extension for alpha sorting and search matching (and fallbacks conditions)?

**Comment by sandysage** [comment]
@devinreams Yeah, that's probably the best course. What do you recommend for having shared product requirements between repos? Is there a doc that this best lives within?

As I understand it for the extension:

- Entries are alphabetically ordered by title
- Entries that don't have a title appear first in the list, but without a fallback condition for either url or username -- for instance, I have 2 entries in my Lockbox with no title and the one with a web address of "aaa" appears below one with a web address of "facebook"
- There are no sorting options in the extension. Alphabetical ordering is for the list display only.

So for this issue, I _think_ what we have offers parity with the extension in addition to the functionality @sashei has implemented for sorting.

**Comment by sandysage** [comment]
@sashei How are we determining recency? Is that an attribute in the datastore that is shared across our product offerings? I just can't recall :P

**Comment by devinreams** [comment]
>What do you recommend for having shared product requirements between repos? Is there a doc that this best lives within?


>Is that an attribute in the datastore that is shared across our product offerings?

That was the idea: @sashei just implemented the field in the datastore itself: https://github.com/mozilla-lockbox/lockbox-datastore/pull/96

And there are two corresponding stories to actually do something with it:

- this one here for iOS
- this for the extension: https://github.com/mozilla-lockbox/lockbox-extension/issues/661

Please note metadata like this _does_ exist in the existing Firefox login store: https://dxr.mozilla.org/mozilla-central/source/toolkit/components/passwordmgr/LoginStore.jsm#24-27 (date created, date last used, date changed, times used).

**Comment by sandysage** [comment]
Per discussions, the concept of "Recency" is local to Firefox desktop, is not synced.

Solution A: concept of "Last Used" has to be incorporated in the local storage, knowing any implementation would be specific to the mobile device. (DEPENDS ON: FxA storage)
Solution B: remove "Recency" if A doesn't happen(None)

If removing recency, we'll want to consider altering the sort options to Alpha and Reverse Alpha sort.

@sashei I believe this story is now on hold pending feedback on FxA storage, yes?
