### ISSUE TITLE
Current sign in shows the list of logins of a different account that was used in previous installation

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#716]
v1.3
1. Install Lockbox.
2. Sign in with Account A.
3. Uninstall Lockbox without disconnecting.
4. Re-install Lockbox.
5. Sign in with Account B.
6. Check the logins after the list gets populated.

Expected: The logins list corresponding to Account B are displayed.

Actual: The logins list corresponding to Account A are displayed.

**Comment by sandysage** [comment]
Might be related to #592
