### ISSUE TITLE
No entries empty state

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#72]
When I have no entries saved in my Lockbox app, I need to know how to get credentials on mobile.*

(*)For Alpha, there isn't a method for adding credentials via the mobile app, as the mobile version is primarily meant to access accounts as already set up on desktop.

## Acceptance criteria
- Should see a 'no entries' screen that prompts adding entries from the browser extension.
- Should not see the entries list view with no entries available

## Visual Design
https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/268085847

**Comment by sashei** [comment]
@changecourse I'll need the asset for the treasure chest when I get to this story.

**Comment by changecourse** [comment]
![chest](https://user-images.githubusercontent.com/6164801/35417039-d3937824-01e8-11e8-89dd-aa6a0e1b32ad.png)
![chest 2x](https://user-images.githubusercontent.com/6164801/35417040-d3af90ae-01e8-11e8-8958-9ac8e1e9042c.png)
![chest 3x](https://user-images.githubusercontent.com/6164801/35417041-d3c6f136-01e8-11e8-8322-f6e4ac903383.png)
