### ISSUE TITLE
Tapping on item kebab from list displays options menu

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#73]
- [ ] cancel button
(nothing else hooked up)
designs: https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/267560600
![Screenshot-2017-12-14 Entry List - Actions.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dc07ab1a9a2600115c9b6f/125516c66e82c728ace21e0d46db978826878dba87e6ab0ef60da1c36417753e7850e30e7e91f131ff6e72121b4f53bc300b1b1da3a7ca39baa47c32d5065ebe957f5566c33445a8ec8a1cbc05e974dd4887b6bc8849c5bc6e73b6dd9d532c5c5446dda0006ceacc09da52e44ae74754a1123561e177367d4e9516713e26.png)

**Comment by changecourse** [comment]
This has been deprioritized for now as all of the actions are available on the detail page, which requires the same amount of taps.

**Comment by sandysage** [comment]
It sounds like this just needs to be closed then.
