### ISSUE TITLE
Tapping Show Password from options menu displays password alert box

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#76]
- [ ] alert box
- [ ] tapping password copies & dismisses alert box
- [ ] confirmation toast

designs: https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/267560602

**Comment by changecourse** [comment]
This has been deprioritized for now as all of the actions in this drawer are available on the detail page, which requires the same amount of taps.
