### ISSUE TITLE
Browser-based info views (settings)

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#78]
- [x] provide feedback
- [x] FAQ

## Visual Designs
note: really only showing the header bar intended for app content, the page content will be served by the website.

**InVision**
FAQ: https://mozilla.invisionapp.com/share/XCEV238ZD#/267560614_FAQ
Provide Feedback: https://mozilla.invisionapp.com/share/XCEV238ZD#/267560613_Provide_Feedback

**Zeplin**
FAQ: https://zpl.io/25gWjPj
Provide Feedback: https://zpl.io/2yBno3K

**Comment by sandysage** [comment]
FAQ link will go to information on lockbox.firefox.com. Stay tuned on the 'final' address.
