### ISSUE TITLE
Account name is not full displayed 

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla-lockbox/lockbox-ios#781]
Environment:
Lockbox app installed from App Store, 1.3.1
iPhone SE(12.0.1 - 16A404)

Steps to reproduce:
1. Open Lockbox app and tap on "Get started";
2. Enter the email and tap on "Continue";
3.  See the account name/field.

Expected result: the information from the field are displayed correctly.

Actual result:

![image-1](https://user-images.githubusercontent.com/24588037/47436437-2ed8aa00-d7af-11e8-8bb7-3fd2b42e014d.jpg)

**Comment by changecourse** [comment]
To be considered and addressed by the FxA team in the future, as referenced in the issue above. 

@devinreams feel free to close if need be.

**Comment by devinreams** [comment]
>To be considered and addressed by the FxA team in the future

Thanks! Cross references include:

https://github.com/mozilla/fxa-content-server/issues/6396
https://github.com/mozilla/fxa-content-server/issues/6507
