### ISSUE TITLE
Biometric Access Timer

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#80]
Provide ability for the user to adjust the length of timer for biometric access. Previously named autolock settings, but that was removed from the intent which is the "ability to unlock with biometrics"

## Acceptance criteria
- Should default to being on
- Should default to 5 minutes until the user sets the timer
- Should be able to set via the settings page (onboarding is different story)
- Should be able to unlock from the same UI as signing in for the first time (until there is a use case for those to be different)

NOTE: This task includes building the UI and autolock setting.

- Dependent on #35
- Dependent on #77

## Visual Design

**InVision**
https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/267560622

**Zeplin**
https://zpl.io/bAGeO9o

**Comment by sandysage** [comment]
@sashei below are a few quick notes as to how I understand autolock works, how users access it, and how to get out of a locked state once an autolock setting is created. Let me know if this aligns to your understanding of the feature.

- what is the default setting? I believe it's "never" but I want to confirm
- 2 ways to set this: 1. onboarding and 2. via the settings page.
   - the settings screen is required prior to successfully enabling users to set their autolock settings
- once autolock is enabled, the user can unlock via touch id (or face id if available) or by signing back into with their FxA
   - until biometrics support (#35) is provided, the only method for unlocking the device is by signing in with FxA, correct?
   - if the most recent log in to FxA, on the device, is within 30 days, I _believe_ that additional confirmation (right now it's checking email) isn't required. But if the last log in is outside of that 30 day window, then the user will be prompted to confirm their device to unlock
- unlock is the same ux as signing in for the first time:
![Screenshot-2018-3-13 Welcome - Returning User.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dc07ab1a9a2600115c9b6f/125516c66e82c728ace21e0d46db978826878dba87e6ab0ef60da1cc64156a227a44942e7c86ec25ba0236413d0a0ae90306061aabe9ec68f3f42e6c981c49b28b380c30d43703a9b1d61beb09b9238f1cd1e0bb884cc0ea3820b3d8d91e680c190acbae0361ffc412820db459eb5f54a3193766e4763f7a41931773256f6234e6.png)

I realize I'm conflating this issue with the larger locking/unlocking functionality. Sorry about that. I'm hoping to better identify how users realize value from autolocking their device so I can craft the acceptance criteria for this.

**Comment by sandysage** [comment]
@sashei I previously stated that the default should be "never". I'm revising that to be:

> We should set a default ‘lock’ timer of 5 minutes so that a user could effortlessly switch between apps for access/copy & paste credentials between apps
