### ISSUE TITLE
Copy/Paste username and password flow is interrupted by Lockbox sync

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#802]
Build: 1.3.2
Device: iPhone 7
iOS: 12.0

Steps to reproduce:
1. Launch Lockbox
2. Tap on a login entry
3. Tap on the username to copy it to clipboard
4. From app switcher, tap on Firefox
5. Paste the username in the login field
6.  From app switcher, tap on Lockbox

Actual results:
- After returning to Lockbox, the app will sync which will direct the user to the entries screen. This is interrupting the normal flow to copy the username, paste it in the browser, return to Lockbox, copy the password and paste it to the browser.

**Comment by joeyg** [comment]
I am able to repo this on the device but not on the simulator for some reason.
