### ISSUE TITLE
Enable/disable biometric lock (settings)

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#81]
## Acceptance criteria

- user should be able to enable it from settings
  - if hasn't already been granted, will prompt user for access to biometrics
- user should be able to disable it from settings
  - which means they have to FxA Authenticate if auto lock setting enabled...

## Visual Design
**Invision**
https://mozilla.invisionapp.com/share/XCEV238ZD#/267560609_Settings_-_Touch_ID_Enabled

**Zeplin**
https://zpl.io/VKNMd5W

**Comment by devinreams** [comment]
Needs a bit more written story and acceptance criteria here.
