### ISSUE TITLE
Share Action sheet item for iOS browsers

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#82]
When I use my mobile browser, I want to be able to access login details within the context of my browsing experience, without having to switch between apps (Lockbox and Browser)

## Open questions
* Share extension toggled/enabled by default? (in which contexts?)
* Logic form detection and filling? (stuff in Firefox for iOS?)
* New interface and icon for share sheet
* Restricting origins or show them all?

## Acceptance
- Should have the Lockbox icon as an option
- Should have a share button at bottom of browser with the Lockbox icon as an option
- Selecting Lockbox icon should autofill text fields in browser with username & password

**Comment by devinreams** [comment]
@sashei Do you think we need to do some exploration #165 on this first? The icon itself is straight forward from a design need, but the real question is: where does the user go after they tap the share button?

I assume it basically opens a "mini-app" experience (the extension) that would ... be the same list view interface as the main app? Or a simplified one? Like the doorhanger would we autofill the TLD the browser was on and just show quick "Copy Username" and "Copy Password" buttons? Or fill directly into the page (feasibility)?

I suspect some exploration is needed first and then we can help inform the experience and then agree what UI/UX is needed from there. Or should we start from the ideal UI/UX and work backwards from that?

**Comment by changecourse** [comment]
Ideal UX would successfully identify the site in question, so by clicking share>Lockbox, I'd be able to select the prepopulated matching entry, which would auto-fill both the username and password to the corresponding fields, FWIW...

**Comment by nickbrandt** [comment]
Sounds good, we will wait on discovery efforts before designing out this flow.

**Comment by nickbrandt** [comment]
@sandysage Do we want to deprioritize this for the time being (and remove labels) since we aren't planning to include this in the MVP?

**Comment by devinreams** [comment]
@sandysage can this be closed in favor of #476?
