### ISSUE TITLE
Couldn't see recently added login in autofill

### ISSUE THREAD

**Issue by ckarlof** [mozilla-lockbox/lockbox-ios#830]
I added a new login on Firefox Desktop and wanted to use it to log into a new app (Gaia GPS) I downloaded. I opened the Lockbox app to verify it had been synced over, but when I used the autofill functionality in Gaia GPS, it wasn't showing the newly added login in the Lockbox autofill UI (but I could see it when I opened the Lockbox app directly). Killing Lockbox and restarting made it so that it showed up in the autofill API in Gaia GPS. Cache bug?

**Comment by devinreams** [comment]
@ckarlof We think we found a bug with the database not closing cleanly, so then it would be forcefully closed/crashed leaving the autofill data in an unusable state sometimes.

If you can, would you mind downloading 1.3.3 Build 2722 from TestFlight and running with that for a little bit to see if new entries appear in the autofill experiences (typeahead keyboard, or the full app extension)?

This may also be related to when we can run sync vs. update the autofill database and the timing may not easily allow for these new entries to load in. 🤔 

I defer to @sashei @joeyg and others if they have any other initial reactions or thoughts...

**Comment by sashei** [comment]
Interesting, I thought we re-populated the credential provider store every time the app synced, but possibly we just do it on first sync...? I'm surprised it didn't show up in the quicktype bar.

(side note, ❤️ GaiaGPS)

**Comment by ckarlof** [comment]
I just tried to reproduce now after updating, and my new login synced and showed up correctly.

**Comment by ckarlof** [comment]
Closing, WFM.
