### ISSUE TITLE
XCUITests on iPad

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockbox/lockbox-ios#842]
This issue for enabling the XCUITests on iPad once the related work is finished (#838, #840, #841, more?)

**Comment by devinreams** [comment]
Good idea, thanks for following along @isabelrios 😁

**Comment by devinreams** [comment]
iPad work is done! I'll keep this "on deck" in case it's something you (or others) are interested in helping work on.

**Comment by isabelrios** [comment]
Just talked to BB guys, it is easy to have the test running on both iPhone and iPad sims per PR and check-in in master for the uispecs schema. A new tab will be added here with the test running on iPad device:

![Screenshot 2019-04-11 at 19 21 32](https://user-images.githubusercontent.com/1897507/55977439-15f57f80-5c8f-11e9-9d5a-7cd563cd51e1.png)

Once issue #909 is fixed this can be done if that's something helpful that you would like to have @devinreams 
I thought it may be a good idea to have before the development of the new features starts that could cause (hopefully not!) some regressions...

**Comment by isabelrios** [comment]
Tests are running on iPad sim for every merge in master...
![Screenshot 2019-04-23 at 18 44 36](https://user-images.githubusercontent.com/1897507/56599925-e1bb8080-65f7-11e9-912b-36e628464093.png)
