### ISSUE TITLE
Search Results not Resetting/Clearing

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#846]
Based on testing the latest Testflight build, Firefox Lockbox 1.4.0 (2769) on iPhone Xs, 12.1

STR:
1. From the entry list, search for an entry ['st' or whatever]
2. Select an entry from the search results to go to the entry detail
3. Back out of the detail
4. Search results are still preserved on the entry list (as expected?)
5. Hit 'Cancel'

Expected: The search term would clear from the field, and all entries would be shown in the list
Actual: The search term clears, but the search results are still preserved, and you are unable to see the other entries within the list. Tapping back into the search field, and hitting cancel once more will reset the list to default.

**Comment by joeyg** [comment]
@changecourse - I mirrored the behavior of Contacts, Mail, Calendar. Is this something user testing revealed was causing a problem?
