### ISSUE TITLE
Update App Store Assets for Next Release

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#876]
- replace existing iPhone-sized assets to show new colors/styles (up to 3 [previews](https://help.apple.com/app-store-connect/#/dev4e413fcb8), 10 [screenshots](https://help.apple.com/app-store-connect/#/devd274dd925))
  - [x] 5.5" **required**
  - [ ] 6.5" (optional)
- add iPad Pro-specific assets (up to 3 [previews](https://help.apple.com/app-store-connect/#/dev4e413fcb8), 10 [screenshots](https://help.apple.com/app-store-connect/#/devd274dd925))
  - [x] 12.9" 2nd gen **required**
  - [ ] 12.9" 3rd gen (optional)

Images attached below (3 iPhone updates and 5 new iPad screens)
[ios-app-screenshots.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/2937814/ios-app-screenshots.zip)

**Comment by devinreams** [comment]
Added a checklist:

- replace existing iPhone-sized assets to show new colors/styles (up to 3 [previews](https://help.apple.com/app-store-connect/#/dev4e413fcb8), 10 [screenshots](https://help.apple.com/app-store-connect/#/devd274dd925))
  - [ ] 5.5" **required**
  - [ ] 6.5" (optional)
- add iPad Pro-specific assets (up to 3 [previews](https://help.apple.com/app-store-connect/#/dev4e413fcb8), 10 [screenshots](https://help.apple.com/app-store-connect/#/devd274dd925))
  - [ ] 12.9" 2nd gen **required**
  - [ ] 12.9" 3rd gen (optional)

**Comment by changecourse** [comment]
@devinreams added a zip file for screenshots of the required sizes to the description above. Let me know if you need anything else!

**Comment by devinreams** [comment]
Uploaded required iPhone and iPad screenshots.

Revised description to not include Test Pilot sentence.

Thanks @changecourse 👍
