### ISSUE TITLE
iPad: Lockbox crashes after tapping the sort button on iPad

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#878]
Build: 1.4.0 (2880)
Device: iPad Air 2
iOS: 11.4

Steps to reproduce:
1. Launch Lockbox
2. Tap the sort button "A-Z"

Actual results:
- Lockbox will crash after tapping the sort button on iPad.

Expected result:
- The sort alphabetically or numerical options should be displayed.

**Comment by devinreams** [comment]
I can reproduce this crash on iPad Pro every time in both portrait and landscape orientations.

I believe this is the Sentry report:
https://sentry.prod.mozaws.net/operations/lockbox-ios/issues/5316902/

(Note: there is no crash on iPhone X, just iPad it seems)
