### ISSUE TITLE
Mismatch in placement of logomark for splash screen vs. welcome screen

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#879]
See attached gif... at some point the placement of the "Firefox Lockbox" header with slogan was moved, causing a jump between the splash screen and the welcome screen. 

![screenrecording_02-24-2019 07-00-17 2019-02-25 15_50_51](https://user-images.githubusercontent.com/6164801/53374292-289d3a80-3915-11e9-92ba-8d4b986120f1.gif)

**Comment by changecourse** [comment]
I believe this is fixed with the latest Testflight build. @devinreams do you mind confirming, and closing if that checks out with you?

**Comment by devinreams** [comment]
Yes the "Lockie" launch screen fades to a full "Lockbox blue" screen before showing either a) unlock/ welcome screen or b) entry listing or detail item. 

So going from "Lockie" to "welcome" is visually "interrupted" with that blue screen and so even if there was, a visual jump may not even be noticable.

@changecourse is that acceptable to close?

**Comment by changecourse** [comment]
Perfect. Yes, closing.
