### ISSUE TITLE
"Sort entries" screen is shown on Welcome Screen after device autlocks

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#881]
Build: 1.4.0 (2880)
Device: iPhone 7
iOS: 12.1

Preconditions:
- Biometrics to lock/unlco enabled

Steps to reproduce:
1. Tap on the sort button
2. Wait for device to lock

Actual results:
- The "Sort entries" screen is shown on Welcome Screen after device autolocks.

![screen shot 2019-03-01 at 12 41 22](https://user-images.githubusercontent.com/32130829/53633377-f72bb400-3c1f-11e9-909d-b58eede911ad.png)

**Comment by sashei** [comment]
This shouldn't be an issue now that the device no longer locks in the foreground.
