### ISSUE TITLE
No credentials are displayed in the list when using autofill

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockbox/lockbox-ios#882]
Build: 1.4.0 (2880)
Device: iPhone 7
iOS: 12.1

Preconditions:
- Autofill enabled.

Steps to reproduce:
1. Open Firefox or Safari
2. Go to a login page
3. Tap on the autofill button (displayed in the keyboard)
4. Unlock Lockbox if biometrics are enabled

Actual results:
- The list is empty. 

Video link: https://youtu.be/hwCwT4G0nmM

**Comment by devinreams** [comment]
Thanks, @simonbasca. I am seeing the same.
