### ISSUE TITLE
Hide the app details in application switcher

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#884]
Much like we have on the Android app, we should consider masking or hiding the application view when its shown in the application switcher.

Why? For similar reasons banks and other sensitive apps do: so that private information is not disclosed by the user unintentionally when in the app switcher.

![img_0044](https://user-images.githubusercontent.com/49511/53888749-80593700-3fe2-11e9-9854-f41195c1aa02.png)

**Comment by joeyg** [comment]
https://developer.apple.com/library/archive/qa/qa1838/_index.html
