### ISSUE TITLE
Add sqlcipher flags to build step

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#892]
Currently, the sqlcipher flags in the app-services Logins library are tuned more for performance than security as I understand it; however Lockbox only deals with small amounts of data relative to Firefox for iOS and would benefit from some of the available features according to @justindarc .

This ticket represents the work to optimize sqlcipher use in Lockbox.

depends on #580

**Comment by justindarc** [comment]
There are two features relevant here:
- `cipher_memory_security`
- `secure_delete`

In the case of `cipher_memory_security`, I believe it is ON by default for encrypted DBs, but it can be disabled for performance using `disableMemSecurity()`:
https://github.com/mozilla/application-services/blob/master/components/logins/ios/Logins/LoginsStorage.swift#L141-L150

For `secure_delete`, it is currently OFF by default, but can be turned on using `PRAGMA secure_delete`:
https://www.sqlite.org/pragma.html#pragma_secure_delete

The API for setting the `secure_delete` option is not yet implemented. See:
https://github.com/mozilla/application-services/issues/862

**Comment by justindarc** [comment]
Apparently, `secure_delete` is now ON by default for logins. If that's the case, there may not actually be anything actionable remaining here! :-)

**Comment by thomcc** [comment]
We turn secure_delete on for logins: https://github.com/mozilla/application-services/blob/master/components/logins/src/db.rs#L46

**Comment by thomcc** [comment]
We were careful not to change the security guarantees for lockbox when we changed those flags, so you should be fine.

**Comment by sashei** [comment]
OK !!! well thanks for the hasty turnaround y'all! happy everything is as it should be 😂
