### ISSUE TITLE
Upgrade from <1.5.0 to 1.5.0

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#897]
### Acceptance criteria

With Lockbox already installed + authenticated, users upgrading to v1.5.0 (incorporating app-services Rust logins library) will maintain their session in the new version regardless of whether they are connected to the network or not.

depends on #580

**Comment by sandysage** [comment]
Cover testing and verify that upgrade works without kicking you out of the app.

**Comment by devinreams** [comment]
I tested downloading from buddybuild and simulating an upgrade from 1.4.1 to 1.5.0:

- disconnected and deleted/uninstalled app
- installed build 2945 (production branch version of 2943 aka 1.4.1)
- signed in, synced and saw logins ✅ 
- locked and backgrounded the app
- installed build 2978 from buddybuild
- was presented with unlock screen, unlocked and saw logins ✅ 
- deleted a login from Firefox desktop and made sure it sync'd
- opened app and during sync I observed the item delete/disappear from the entry list ✅ 

It seems we have this upgrade path handled.

Can anyone think of different un-happier paths to test? If not then I propose we can close this.

**Comment by sashei** [comment]
We haven't seen any follow-up issues from PI on this @devinreams, how do you feel about closing it as completed?

**Comment by devinreams** [comment]
>how do you feel about closing it as completed?

I feel good about it.

Best case right now is the upgrade path work as expected!

Worst case is it's not quite and the workaround is to sign in again (which some users are having to do anyway since they're in a buggy state).
