### ISSUE TITLE
Switch to `MozillaAppServices.framework`

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#907]
We should use the megazord'ed version of the application-services rust logins code so that they can "kill iOS components projects" -- https://github.com/mozilla/application-services/pull/932

**Comment by rfk** [comment]
Also you should get the benefit of reduced binary size because you don't end up pulling in two copies of our various rust dependencies, just in case you needed anything to sweeten the deal :-)

**Comment by eoger** [comment]
Thank you for moving to the megazord so quickly, we hope you enjoy the better start times 😀
