### ISSUE TITLE
The app is crashing when trying to login

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockbox/lockbox-ios#923]
v1.5.0(2999)
iPhone XR (12.2)

1. Have Lockbox clean installed.
2. Try to login with valid credentials.
3. Hit "Finish" after entering the credentials.

Result: The app is crashing.

The crash is not reproducible on iOS 11.4.

**Comment by isabelrios** [comment]
I was able to repro this on my iPhone 6s both from clean install and after updating to latest version via TF. Not sure if this console logs are useful, just in case, attaching them. 
[LockboxCrash.docx](https://github.com/mozilla-lockbox/lockbox-ios/files/3107426/LockboxCrash.docx)

**Comment by sashei** [comment]
I found this bug in several of the issues I've been working on and have fixed it at both #916 & #928. would like to re-test after one of those is merged.
