### ISSUE TITLE
Adjust splash screen images to fit taller iPhones

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#935]
Running Lockbox on any "new" iPhone (higher DPI?) results in a big white bar at the bottom of the "privacy" screen and the splash screen.

#### Acceptance criteria
Start + background Lockbox on any of: iPhone XS, iPhone XS Max, iPhone XR, etc. Observe the lack of big white bar beneath the pretty blue.

**Comment by devinreams** [comment]
@changecourse can you make taller assets real quick? 🤞
