### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#95]

**Comment by changecourse** [comment]
Amazon
tjacobson@yahoo.com

Facebook
tanya.jacobson

LinkedIn
tjacobson@yahoo.com

Reddit
tjacobson@yahoo.com

Twitter
tjacobson

Wordpress
tjacobson@yahoo.com

**Comment by sashei** [comment]
Note: I've made a follow-up issue for @sandysage to prioritize when we want to remove this set of test data: https://waffle.io/mozilla-lockbox/lockbox-extension/cards/5a8333b654abdb00265d7ef8
