### ISSUE TITLE
Create an iOS test plan (product integrity) with steps and acceptance criteria

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-lockbox/lockbox-ios#97]
https://testrail.stage.mozaws.net/index.php?/projects/overview/52

- [x] discovery around the features/functionality to include and how that matches to the product acceptance criteria for each

- [x] determine testing methods for each component

## Acceptance criteria
- A draft document that outlines the test approach that is then added to as we create new features
- TestRail suites documented

**Comment by devinreams** [comment]
Test suites/cases drafted and added to TestRail:
https://testrail.stage.mozaws.net/index.php?/projects/overview/52

I will continue work with PI to flesh out test steps and cases...
